Repository NG-ZORRO/ng-zorro-antd, pull requests merged in 2019-05, with the labels that each got.

#3385 fix(module:tree,tree-select): fix the styles of connecting line
  components/tree-select/style/entry.less
  components/tree-select/style/patch.less
  components/tree/style/patch.less
Labels: PR: :heavy_check_mark: Merge Ready

#3435 docs: update rxjs thirty days link
  docs/recommendation.zh-CN.md
Labels: PR: :heavy_check_mark: Merge Ready

#3410 chore: fix definitions not exported
  components/carousel/public-api.ts
Labels: PR: :heavy_check_mark: Merge Ready

#3452 docs: update typo
  components/input/doc/index.en-US.md
Labels: PR: :heavy_check_mark: Merge Ready

#3416 fix(module:cascader,checkbox,switch,tooltip): fix memory leak problem
  components/cascader/nz-cascader.component.ts
  components/checkbox/nz-checkbox-group.component.ts
  components/switch/nz-switch.component.ts
  components/tooltip/nz-tooltip.directive.ts
Labels: PR: :heavy_check_mark: Merge Ready

#3429 feat(module:card): support setting size
  components/card/doc/index.en-US.md
  components/card/doc/index.zh-CN.md
  components/card/nz-card.component.ts
  components/card/nz-card.spec.ts
Labels: PR: :heavy_check_mark: Merge Ready

#3395 feat(module:tree-select): support customized icon
  components/tree-select/demo/customized-icon.md
  components/tree-select/demo/customized-icon.ts
  components/tree-select/doc/index.en-US.md
  components/tree-select/doc/index.zh-CN.md
  components/tree-select/nz-tree-select.component.html
  components/tree-select/nz-tree-select.component.ts
  components/tree-select/nz-tree-select.spec.ts
  components/tree/nz-tree-node.component.ts
  components/tree/nz-tree.component.ts
Labels: PR: :heavy_check_mark: Merge Ready

#3367 fix(module:carousel): fix carousel in entry components
  components/carousel/nz-carousel.component.ts
  components/carousel/nz-carousel.spec.ts
Labels: PR::eyes: Need Review

#3415 fix(module:modal): content not work in confirm mode when the type is component
  components/modal/nz-modal.component.html
  components/modal/nz-modal.spec.ts
Labels: PR::eyes: Need Review

#3445 fix(module:progress): fix stroke color is not updated
  components/progress/nz-progress.component.ts
Labels: PR::eyes: Need Review

#3455 fix(module:menu): submenu should not remain highlighted
  components/menu/nz-menu.spec.ts
  components/menu/nz-submenu.component.ts
Labels: PR::eyes: Need Review

#3339 fix(module:modal): cannot to close in order of overlay opens when using esc
  components/modal/nz-modal.component.ts
  components/modal/nz-modal.service.ts
Labels: PR::eyes: Need Review

#3376 feat(module:drawer): support `nzOnCancel` for service mode
  components/drawer/doc/index.en-US.md
  components/drawer/doc/index.zh-CN.md
  components/drawer/nz-drawer-options.ts
  components/drawer/nz-drawer.component.ts
  components/drawer/nz-drawer.service.ts
  components/drawer/nz-drawer.spec.ts
Labels: PR::eyes: Need Review

#3400 fix(module:modal): should not close when mousedown in the body
  components/modal/nz-modal.component.html
  components/modal/nz-modal.component.ts
  components/modal/nz-modal.spec.ts
Labels: PR::eyes: Need Review

#3185 fix(module:breadcrumb): fix input boolean and router event not caught error
  .gitignore
  components/breadcrumb/demo/auto.ts
  components/breadcrumb/doc/index.en-US.md
  components/breadcrumb/doc/index.zh-CN.md
  components/breadcrumb/nz-breadcrumb-item.component.html
  components/breadcrumb/nz-breadcrumb.component.ts
  components/breadcrumb/nz-breadcrumb.spec.ts
  components/icon/testing/nz-icon-test.module.ts
Labels: PR::eyes: Need Review

#3469 build: hack to prevent bug of ng-packagr
  scripts/site/_site/doc/app/share/share.module.ts
Labels: 🖨Build
