Repository NG-ZORRO/ng-zorro-antd, pull requests merged in 2019-11, with the labels that each got.

#4369 test(module:calendar): change expected class name
  components/calendar/nz-calendar.spec.ts
Labels: PR: reviewed-approved

#4371 fix(module:pagination): replace full-width character with half-width
  components/pagination/nz-pagination.component.html
Labels: PR: reviewed-approved

#4363 fix(module:page-header): has footer or breadcrumb style bug
  components/page-header/nz-page-header.component.ts
  components/page-header/nz-page-header.spec.ts
Labels: PR: reviewed-approved

#4341 feat(module:monaco-editor): support static loading
  components/code-editor/doc/index.en-US.md
  components/code-editor/doc/index.zh-CN.md
  components/code-editor/nz-code-editor.definitions.ts
  components/code-editor/nz-code-editor.service.ts
  components/code-editor/style/entry.less
  components/core/config/config.ts
  docs/global-config.en-US.md
  docs/global-config.zh-CN.md
Labels: PR: reviewed-approved, PR: target-minor

#4347 fix(module:modal): `nzMaskClosable` not working in the confirm mode
  components/modal/nz-modal.service.ts
  components/modal/nz-modal.spec.ts
Labels: PR: reviewed-approved

#4368 fix(module:tree-select): default tags incorrect in strictly mode
  components/tree-select/nz-tree-select.component.ts
  components/tree-select/nz-tree-select.spec.ts
  components/tree/nz-tree.component.ts
Labels: PR: reviewed-approved

#4342 fix(module:table): support nzWidthConfig null undefined value
  components/table/doc/index.en-US.md
  components/table/doc/index.zh-CN.md
  components/table/nz-table.component.html
Labels: PR: reviewed-approved

#4309 fix(module:mention): unable to select on mobile device
  components/mention/nz-mention.component.ts
Labels: PR: reviewed-approved

#4350 refactor(module:core): add nz drag service
  components/carousel/nz-carousel.component.ts
  components/carousel/nz-carousel.spec.ts
  components/core/services/drag/index.ts
  components/core/services/drag/nz-drag.service.spec.ts
  components/core/services/drag/nz-drag.service.ts
  components/core/services/drag/public-api.ts
  components/core/services/public-api.ts
  components/core/util/dom.ts
Labels: PR: reviewed-approved

#4397 feat(module:tooltip): support changing trigger
  components/tooltip/base/nz-tooltip-base.directive.ts
  components/tooltip/nz-tooltip.spec.ts
Labels: PR: reviewed-approved

#4357 fix(module:date-picker): `nzDefaultOpenValue` not work in time panel
  components/calendar/date-table.component.ts
  components/date-picker/lib/calendar/calendar-header.component.ts
  components/date-picker/lib/popups/inner-popup.component.html
  components/date-picker/lib/popups/inner-popup.component.ts
  components/date-picker/nz-date-picker.component.spec.ts
  components/time-picker/doc/index.en-US.md
  components/time-picker/doc/index.zh-CN.md
Labels: PR: reviewed-approved, pre-release

#4392 fix(module:tooltip): fix not undefined value not updated
  components/tooltip/base/nz-tooltip-base.directive.ts
Labels: PR: reviewed-approved, PR: target-patch, PR: unreviewed

#4382 fix(module:select): prevent hidden options from being selected
  components/select/nz-select.component.spec.ts
  components/select/nz-select.service.ts
Labels: PR: reviewed-approved

#4387 fix(module:tooltip): fix tooltip accessing destroyed view
  components/tooltip/base/nz-tooltip-base.directive.ts
Labels: PR: reviewed-approved, PR: target-patch, PR: unreviewed, pre-release

#4366 fix(module:auto-complete): default value not selected
  components/auto-complete/demo/certain-category.ts
  components/auto-complete/demo/non-case-sensitive.ts
  components/auto-complete/demo/options.ts
  components/auto-complete/demo/uncertain-category.ts
  components/auto-complete/nz-autocomplete-option.component.ts
  components/auto-complete/nz-autocomplete-trigger.directive.ts
  components/auto-complete/nz-autocomplete.component.html
  components/auto-complete/nz-autocomplete.component.ts
  components/auto-complete/nz-autocomplete.spec.ts
  components/core/types/compare-with.ts
  components/core/types/public-api.ts
Labels: PR: reviewed-approved

#4306 feat(module:page-header): add `nzGhost` property
  components/core/config/config.ts
  components/page-header/demo/actions.md
  components/page-header/demo/breadcrumb.md
  components/page-header/demo/content.md
  components/page-header/demo/ghost.md
  components/page-header/demo/ghost.ts
  components/page-header/demo/responsive.md
  components/page-header/doc/index.en-US.md
  components/page-header/doc/index.zh-CN.md
  components/page-header/nz-page-header.component.ts
  components/page-header/nz-page-header.spec.ts
Labels: PR: reviewed-approved, pre-release

#4315 fix(module:date-picker): overlay panel flicker when position changes
  components/date-picker/lib/calendar/calendar-input.component.ts
  components/date-picker/picker.component.html
  components/date-picker/picker.component.ts
  docs/i18n.zh-CN.md
Labels: PR: reviewed-approved, 🤚 Blocked

#4408 release(8.5.0): release 8.5.0
  CHANGELOG.md
  components/package.json
  components/version/version.ts
  docs/changelog.en-US.md
  docs/changelog.zh-CN.md
Labels: PR: reviewed-approved

#4409 docs: update users
  README-zh_CN.md
  README.md
  docs/introduce.en-US.md
  docs/introduce.zh-CN.md
  scripts/site/_site/doc/app/app.component.html
Labels: PR: reviewed-approved, pre-release

#4418 fix(module:tooltip): fix hiding when hover popover
  components/tooltip/base/nz-tooltip-base.directive.ts
Labels: PR: reviewed-approved, pre-release

#4424 fix(module:tree-select): click label behavior is incorrect in strict mode
  components/tree-select/nz-tree-select.component.ts
Labels: PR: reviewed-approved, pre-release

#4436 fix(module:code-editor): fix config
  components/code-editor/doc/index.en-US.md
  components/code-editor/doc/index.zh-CN.md
  components/code-editor/nz-code-editor.service.ts
Labels: PR: reviewed-approved, pre-release

#4423 fix(module:drawer): content overflow when placement is top or bottom
  components/drawer/nz-drawer.component.html
  components/drawer/nz-drawer.spec.ts
  components/drawer/style/drawer.less
Labels: PR: reviewed-approved, pre-release

#4440 release(8.5.1): release 8.5.1
  CHANGELOG.md
  components/package.json
  components/version/version.ts
  docs/changelog.en-US.md
  docs/changelog.zh-CN.md
Labels: PR: reviewed-approved

#4453 chore: update to angular 9.0.0-rc.3 with ivy
  .github/semantic.yml
  .nvmrc
  .travis.yml
  angular.json
  components/anchor/nz-anchor-link.component.ts
  components/core/config/config.service.ts
  components/core/config/config.spec.ts
  components/core/testing/event-objects.ts
  components/date-picker/nz-date-picker.component.spec.ts
  components/date-picker/picker.component.ts
  components/dropdown/nz-dropdown-button.component.html
  components/dropdown/nz-dropdown-button.component.ts
  components/dropdown/nz-dropdown-context.component.html
  components/dropdown/nz-dropdown-context.component.ts
  components/dropdown/nz-dropdown.component.ts
  components/dropdown/nz-dropdown.module.ts
  components/dropdown/nz-dropdown.service.ts
  components/dropdown/nz-dropdown.spec.ts
  components/dropdown/public-api.ts
  components/form/nz-form-control.spec.ts
  components/input-number/nz-input-number.component.ts
  components/input-number/nz-input-number.spec.ts
  components/mention/nz-mention.spec.ts
  components/package.json
  components/popconfirm/nz-popconfirm.spec.ts
  components/popover/nz-popover.spec.ts
  components/progress/nz-progress.spec.ts
  components/select/nz-option-container.component.ts
  components/tabs/nz-tabs-nav.spec.ts
  components/tag/nz-tag.spec.ts
  components/tooltip/nz-tooltip.spec.ts
  components/tree/nz-tree.spec.ts
  components/tsconfig-ivy.spec.json
  components/tsconfig.lib.prod.json
  components/tsconfig.spec.json
  integration/angular-cli/angular.json
  integration/angular-cli/tsconfig.json
  integration/rollup/rollup.config.js
  integration/webpack/package.json
  now.json
  package.json
  schematics/utils/build-component.ts
  scripts/gulp/gulpfile.ts
  scripts/gulp/tasks/site.ts
  scripts/gulp/tasks/unit-test.ts
  scripts/site/_site/doc/app/app.component.html
  scripts/site/_site/doc/tsconfig-ivy.server.json
  scripts/site/_site/doc/tsconfig.app.json
  scripts/site/_site/doc/tsconfig.es5.json
  scripts/site/_site/doc/tsconfig.server.json
  scripts/site/_site/iframe/tsconfig.app.json
  scripts/site/_site/tsconfig.app.json
  scripts/surge.sh
Labels: PR: unreviewed

#4462 ci: add bundle size ci
  bundlesize.config.json
  components/package.json
  components/version/version.ts
  package.json
  scripts/gulp/tasks/site.ts
Labels: PR: unreviewed

#4402 feat(schematics): add v9 migration rules for tooltip-like
  package.json
  schematics/migration.json
  schematics/ng-add/index.spec.ts
  schematics/ng-update/data/input-names.ts
  schematics/ng-update/index.ts
  schematics/ng-update/test-cases/v9/deprecated-component-tooltip-like.spec.ts
  schematics/ng-update/test-cases/v9/input-names-tooltip-like.spec.ts
  schematics/ng-update/upgrade-data.ts
  schematics/ng-update/upgrade-rules/checks/tooltip-like-template-rule.ts
  schematics/tsconfig.json
  schematics/utils/ng-update/elements.ts
Labels: PR: unreviewed

#4390 chore(module:tooltip,popover,popconfirm): remove component API
  components/input/demo/tooltip.ts
  components/popconfirm/nz-popconfirm.component.ts
  components/popconfirm/nz-popconfirm.directive.ts
  components/popconfirm/nz-popconfirm.spec.ts
  components/popover/nz-popover.component.ts
  components/popover/nz-popover.directive.ts
  components/popover/nz-popover.spec.ts
  components/tooltip/base/index.ts
  components/tooltip/base/nz-tooltip-base-legacy.component.ts
  components/tooltip/base/public-api.ts
  components/tooltip/nz-tooltip-base.component.ts
  components/tooltip/nz-tooltip-base.directive.ts
  components/tooltip/nz-tooltip.component.ts
  components/tooltip/nz-tooltip.directive.ts
  components/tooltip/nz-tooltip.spec.ts
  components/tooltip/public-api.ts
  scripts/site/_site/doc/app/app.component.html
Labels: PR: reviewed-approved, PR: target-major, 💔 Breaking Change

#4466 feat(schematics): add v9 migration rules for dropdown
  schematics/ng-update/index.ts
  schematics/ng-update/test-cases/v9/deprecated-class-dropdown.spec.ts
  schematics/ng-update/test-cases/v9/deprecated-component-dropdown.spec.ts
  schematics/ng-update/upgrade-rules/checks/dropdown-class-rule.ts
  schematics/ng-update/upgrade-rules/checks/dropdown-template-rule.ts
  scripts/gulp/tasks/schematic.ts
Labels: PR: reviewed-approved

#4464 chore(module:calendar): delete deprecated input nzCard
  components/calendar/nz-calendar.component.ts
  components/calendar/nz-calendar.spec.ts
Labels: PR: reviewed-approved, PR: target-major, PR: unreviewed, 💔 Breaking Change

#4375 chore(module:icon): remove old api
  components/icon/doc/index.en-US.md
  components/icon/doc/index.zh-CN.md
  components/icon/nz-icon.directive.ts
  components/icon/nz-icon.service.ts
  components/icon/nz-icon.spec.ts
Labels: PR: reviewed-approved, PR: target-major, PR: unreviewed, 💔 Breaking Change

#4478 docs: fix docs size
  scripts/site/_site/doc/app/app.module.ts
  scripts/site/_site/doc/app/share/share.module.ts
Labels: PR: unreviewed

#4468 docs: fix icon link
  components/icon/doc/index.en-US.md
  components/icon/doc/index.zh-CN.md
Labels: PR: reviewed-approved

#4485 fix(module: code-editor): fix wrong initialization with diff mode
  components/code-editor/nz-code-editor.component.ts
Labels: PR: reviewed-approved

#4487 release(8.5.2): release 8.5.2
  CHANGELOG.md
  components/package.json
  components/version/version.ts
  docs/changelog.en-US.md
  docs/changelog.zh-CN.md
  scripts/site/_site/doc/app/app.component.html
  scripts/site/_site/doc/app/app.module.ts
Labels: PR: reviewed-approved
