Repository NG-ZORRO/ng-zorro-antd, pull requests merged in 2019-04, with the labels that each got.

#3169 feat(module:date-picker): support `nzOnCalendarChange`
  components/date-picker/date-picker.component.spec.ts
  components/date-picker/date-range-picker.component.html
  components/date-picker/date-range-picker.component.ts
  components/date-picker/doc/index.en-US.md
  components/date-picker/doc/index.zh-CN.md
  components/date-picker/lib/popups/date-range-popup.component.ts
  components/date-picker/range-picker.component.spec.ts
Labels: PR::eyes: Need Review

#2933 feat(module:tree, tree-select): support customize icons
  components/date-picker/date-picker.component.spec.ts
  components/date-picker/lib/popups/date-range-popup.component.ts
  components/tree-select/nz-tree-select.component.html
  components/tree-select/nz-tree-select.component.ts
  components/tree/demo/customized-icon.ts
  components/tree/doc/index.en-US.md
  components/tree/doc/index.zh-CN.md
  components/tree/nz-tree-node.component.html
  components/tree/nz-tree-node.component.ts
  components/tree/nz-tree.component.html
  components/tree/nz-tree.component.ts
  components/tree/nz-tree.module.ts
  components/tree/nz-tree.spec.ts
  tsconfig.json
Labels: PR: :heavy_check_mark: Merge Ready

#3203 fix(module:drawer): create focus trap error when `nzVisible` default value is true
  components/drawer/nz-drawer.component.ts
Labels: PR: :heavy_check_mark: Merge Ready

#3270 feat(module: tree): support nzBlockNode
  components/tree/demo/draggable-confirm.ts
  components/tree/demo/draggable.ts
  components/tree/doc/index.en-US.md
  components/tree/doc/index.zh-CN.md
  components/tree/nz-tree.component.ts
  components/tree/nz-tree.spec.ts
Labels: PR::eyes: Need Review

#3080 fix(module:i18n): fix catalan translations
  components/i18n/languages/ca_ES.ts
  components/i18n/languages/pagination/ca_ES.ts
Labels: PR: :heavy_check_mark: Merge Ready

#3194 fix(module:steps):`updateChildrenSteps` bug
  components/steps/nz-steps.component.ts
  components/steps/nz-steps.spec.ts
Labels: PR: :heavy_check_mark: Merge Ready

#3230 fix(module:upload): fix deprecated icon class property
  components/upload/demo/avatar.ts
  components/upload/demo/basic.ts
  components/upload/demo/custom-request.ts
  components/upload/demo/directory.ts
  components/upload/demo/drag.ts
  components/upload/demo/file-list.ts
  components/upload/demo/filter.ts
  components/upload/demo/manually.ts
  components/upload/demo/picture-card.ts
  components/upload/demo/picture-style.ts
  components/upload/nz-upload-list.component.html
  components/upload/upload.spec.ts
Labels: PR: :heavy_check_mark: Merge Ready

#3062 refactor(module:carousel): refactor
  angular.json
  components/breadcrumb/nz-breadcrumb.component.ts
  components/carousel/doc/index.en-US.md
  components/carousel/doc/index.zh-CN.md
  components/carousel/nz-carousel-content.directive.ts
  components/carousel/nz-carousel-definitions.ts
  components/carousel/nz-carousel.component.html
  components/carousel/nz-carousel.component.ts
  components/carousel/nz-carousel.spec.ts
  components/carousel/strategies/base-strategy.ts
  components/carousel/strategies/opacity-strategy.ts
  components/carousel/strategies/transform-strategy.ts
  components/core/util/dom.ts
  package.json
Labels: PR::eyes: Need Review

#3262 fix: click event is stopped
  components/rate/nz-rate-item.component.html
Labels: PR::eyes: Need Review

#3136 feat(module:form): support hide the label colon
  components/form/doc/index.en-US.md
  components/form/doc/index.zh-CN.md
  components/form/nz-form-item.component.ts
  components/form/nz-form-label.component.html
  components/form/nz-form-label.component.ts
  components/form/nz-form-label.spec.ts
  components/form/nz-form.directive.ts
  components/form/nz-form.spec.ts
Labels: PR::eyes: Need Review

#3265 feat(schematics): enhance component generator
  schematics/collection.json
  schematics/ng-component/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.__style__
  schematics/ng-component/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.html
  schematics/ng-component/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.spec.ts
  schematics/ng-component/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.ts
  schematics/ng-component/index.ts
  schematics/ng-component/schema.json
  schematics/ng-component/schema.ts
  schematics/utils/build-component.ts
  scripts/schematics/copy-resources.js
  scripts/schematics/demo2schematics.js
  scripts/schematics/template/index.ts.template
  scripts/schematics/template/schema.json
  scripts/schematics/template/schema.json.template
  scripts/schematics/template/schema.ts
  scripts/schematics/template/schema.ts.template
Labels: PR::eyes: Need Review

#3245 fix(module:modal): integration problem with select component
  components/modal/modal-util.ts
  components/modal/nz-modal.component.html
  components/modal/nz-modal.component.ts
Labels: PR::eyes: Need Review

#3295 feat: support server-side rendering
  README-zh_CN.md
  README.md
  components/affix/nz-affix.component.ts
  components/anchor/nz-anchor-link.component.ts
  components/anchor/nz-anchor.component.ts
  components/avatar/nz-avatar.component.ts
  components/back-top/nz-back-top.component.ts
  components/carousel/nz-carousel.component.ts
  components/carousel/nz-carousel.spec.ts
  components/icon/nz-icon.directive.ts
  components/menu/nz-submenu.component.ts
  components/select/nz-select.component.ts
  components/slider/nz-slider.component.ts
  components/statistic/nz-countdown.component.ts
  components/table/nz-table.component.ts
  components/timeline/nz-timeline.component.ts
  components/upload/nz-upload-list.component.ts
  docs/animations.en-US.md
  docs/animations.zh-CN.md
  docs/changelog.en-US.md
  docs/changelog.zh-CN.md
  docs/contributing.en-US.md
  docs/contributing.zh-CN.md
  docs/customize-theme.en-US.md
  docs/customize-theme.zh-CN.md
  docs/faq.en-US.md
  docs/faq.zh-CN.md
  docs/recommendation.en-US.md
  docs/recommendation.zh-CN.md
  docs/universal.en-US.md
  docs/universal.zh-CN.md
Labels: 🧭SSR

#3353 docs(module:tag): fix typo
  components/tag/doc/index.zh-CN.md
Labels: PR: :heavy_check_mark: Merge Ready

#3358 build: supports pre-render for docs and add sitemap generator script
  angular.json
  package.json
  scripts/build/prerender.sh
  scripts/prerender/prerender.ts
  scripts/prerender/sitemap.ts
  scripts/prerender/static.paths.ts
  scripts/prerender/tsconfig.json
  scripts/prerender/types.d.ts
  scripts/site/_site/doc/app/app.component.ts
  scripts/site/_site/doc/app/app.module.ts
  scripts/site/_site/doc/app/app.server.module.ts
  scripts/site/_site/doc/app/share/nz-codebox/nz-codebox.component.ts
  scripts/site/_site/doc/app/share/nz-nav-bottom/nz-nav-bottom.component.ts
  scripts/site/_site/doc/google854eb8b183564acb.html
  scripts/site/_site/doc/main.server.ts
  scripts/site/_site/doc/tsconfig.server.json
  scripts/site/template/demo-component.template.ts
  scripts/site/template/doc-component.template.ts
Labels: PR::eyes: Need Review

#3342 fix(module:auto-complete): enter-keydown event should not be prevent when the panel is closed
  components/auto-complete/nz-autocomplete-trigger.directive.ts
Labels: PR::eyes: Need Review
