Repository NG-ZORRO/ng-zorro-antd, pull requests merged in 2019-10, with the labels that each got.

#4256 chore(module:*): lock @types/jasmine version to avoid a bug
  package.json
Labels: PR: reviewed-approved

#4258 fix(module:*): fix style error with 3.23.6
  .editorconfig
  components/breadcrumb/style/entry.less
  components/breadcrumb/style/patch.less
  components/button/demo/icon.ts
  components/button/demo/size.ts
  components/button/doc/index.en-US.md
  components/button/doc/index.zh-CN.md
  components/button/nz-button-group.component.ts
  components/button/nz-button.component.ts
  components/button/nz-button.spec.ts
  components/button/style/index.less
  components/button/style/mixin.less
  components/card/doc/index.en-US.md
  components/card/doc/index.zh-CN.md
  components/card/nz-card-grid.directive.ts
  components/core/logger/logger.ts
  components/dropdown/demo/dropdown-button.ts
  components/dropdown/nz-dropdown.directive.ts
  components/grid/nz-col.directive.ts
  components/grid/nz-grid.spec.ts
  components/input/demo/group.ts
  components/input/demo/presuffix.ts
  components/input/doc/index.zh-CN.md
  components/skeleton/nz-skeleton.component.html
  scripts/site/_site/doc/app/app.component.html
  scripts/site/_site/doc/style/colors.less
  scripts/site/_site/doc/style/common.less
  scripts/site/_site/doc/style/markdown.less
  scripts/site/_site/doc/theme.less
Labels: PR: reviewed-approved

#4261 feat(module:select): support default value not in the option list
  components/select/demo/default-value.md
  components/select/demo/default-value.ts
  components/select/demo/hide-selected.md
  components/select/demo/hide-selected.ts
  components/select/doc/index.en-US.md
  components/select/doc/index.zh-CN.md
  components/select/nz-option-container.component.html
  components/select/nz-option.component.ts
  components/select/nz-option.pipe.ts
Labels: PR: unreviewed

#4264 docs: update animations docs
  docs/animations.en-US.md
  docs/animations.zh-CN.md
Labels: PR: reviewed-approved

#4262 fix(module:select): fix select input not grow correctly in IE
  README-zh_CN.md
  README.md
  components/select/demo/automatic-tokenization.ts
  components/select/demo/basic.ts
  components/select/demo/coordinate.ts
  components/select/demo/custom-content.ts
  components/select/demo/custom-dropdown-menu.ts
  components/select/demo/custom-template.ts
  components/select/demo/default-value.ts
  components/select/demo/frontend-search.md
  components/select/demo/frontend-search.ts
  components/select/demo/hide-selected.ts
  components/select/demo/label-in-value.ts
  components/select/demo/multiple.ts
  components/select/demo/optgroup.ts
  components/select/demo/scroll-load.ts
  components/select/demo/search-box.ts
  components/select/demo/search.ts
  components/select/demo/select-users.ts
  components/select/demo/size.ts
  components/select/demo/tags.ts
  components/select/nz-select-top-control.component.html
  components/select/nz-select-top-control.component.ts
  components/select/nz-select-top-control.spec.ts
  docs/introduce.en-US.md
  docs/introduce.zh-CN.md
Labels: PR: unreviewed

#4267 fix(module:select): fix select dropdown position error
  components/select/nz-select-top-control.component.html
  components/select/nz-select-top-control.component.ts
  components/select/nz-select.component.ts
  components/select/nz-select.service.ts
Labels: PR: unreviewed

#4270 fix(module:select): fix select focus & blur & autoFocus event
  components/select/nz-select.component.html
  components/select/nz-select.component.spec.ts
  components/select/nz-select.component.ts
Labels: PR: unreviewed

#4272 fix(module:select): fix select scroll bottom not emit with search
  components/select/nz-option-container.component.ts
Labels: PR: unreviewed

#4271 perf(module:typography, tabs): make the `destroy$` complete when destroy
  components/tabs/nz-tabset.component.ts
  components/typography/nz-text-copy.component.ts
Labels: PR: reviewed-approved

#4273 feat(module:table): support td break-word display
  components/table/demo/break-word.md
  components/table/demo/break-word.ts
  components/table/demo/dynamic-settings.md
  components/table/doc/index.en-US.md
  components/table/doc/index.zh-CN.md
  components/table/nz-td.component.ts
Labels: PR: unreviewed

#4277 feat(module:table): support extra panel with nz-th-extra selector
  components/table/demo/custom-filter-panel.ts
  components/table/nz-th.component.html
Labels: PR: unreviewed

#4274 fix(module:table): fix table fixed style when nzData change
  components/table/nz-table.component.ts
Labels: PR: unreviewed

#4127 feat(module:cascader): support option render template
  components/cascader/demo/custom-template.md
  components/cascader/demo/custom-template.ts
  components/cascader/doc/index.en-US.md
  components/cascader/doc/index.zh-CN.md
  components/cascader/nz-cascader-definitions.ts
  components/cascader/nz-cascader-li.component.html
  components/cascader/nz-cascader-li.component.ts
  components/cascader/nz-cascader-utils.ts
  components/cascader/nz-cascader.component.html
  components/cascader/nz-cascader.component.ts
  components/cascader/nz-cascader.module.ts
  components/cascader/nz-cascader.service.ts
  components/cascader/nz-cascader.spec.ts
Labels: PR: reviewed-approved, PR: target-minor, PR: unreviewed

#4149 feat(module:tree-select): support `nzCheckStrictly` property
  components/tree-select/doc/index.en-US.md
  components/tree-select/doc/index.zh-CN.md
  components/tree-select/nz-tree-select.component.html
  components/tree-select/nz-tree-select.component.ts
Labels: PR: reviewed-approved

#4257 fix(module:tag): nzNoAnimation not working
  components/tag/demo/basic.md
  components/tag/demo/basic.ts
  components/tag/demo/control.md
  components/tag/demo/module
  components/tag/doc/index.en-US.md
  components/tag/doc/index.zh-CN.md
  components/tag/nz-tag.component.ts
Labels: PR: reviewed-approved

#4215 fix(module:auto-complete): not emit changes when retype same value while open
  components/auto-complete/nz-autocomplete-trigger.directive.ts
  components/auto-complete/nz-autocomplete.spec.ts
Labels: PR: reviewed-approved

#4039 fix(module:pagination): add space between page size and slash
  components/pagination/nz-pagination.component.html
Labels: PR: reviewed-approved

#4263 feat(module:mention): support for adaptive boundary
  components/core/overlay/overlay-position.ts
  components/mention/nz-mention.component.ts
Labels: PR: reviewed-approved

#4221 feat(module:spin): support global indicator
  components/core/config/config.ts
  components/spin/doc/index.en-US.md
  components/spin/doc/index.zh-CN.md
  components/spin/nz-spin.component.ts
  components/spin/nz-spin.spec.ts
Labels: PR: reviewed-approved, PR: target-minor, PR: unreviewed

#4229 fix(module:tooltip): fix properties updated before origin is set
  components/tooltip/base/nz-tooltip-base.directive.ts
Labels: PR: reviewed-approved, PR: target-patch, PR: unreviewed

#4285 docs: add ng-china-2019 link
  scripts/site/_site/doc/app/app.component.html
  scripts/site/_site/doc/app/app.module.ts
Labels: PR: unreviewed

#4225 chore(module:editor): fix types
  components/code-editor/nz-code-editor.component.ts
  components/code-editor/nz-code-editor.definitions.ts
  components/code-editor/nz-code-editor.service.ts
Labels: PR: reviewed-approved, PR: target-patch

#4289 fix(module: tree): update when property isLeaf is changed
  components/core/tree/nz-tree-base-node.ts
Labels: PR: unreviewed

#4283 fix(module:time-picker): add null input judgement when using datefns
  components/i18n/date-helper.service.ts
Labels: PR: reviewed-approved

#4286 fix(module: tree): fix nzHideUnMatched bug
  components/core/tree/nz-tree-base.service.ts
Labels: PR: reviewed-approved

#3947 perf(module:tree): change the collapsed of the treeNode to ngIf
  components/core/animation/collapse.ts
  components/tree/nz-tree-node.component.html
  components/tree/nz-tree-node.component.ts
  components/tree/nz-tree.spec.ts
  components/tree/style/patch.less
Labels: PR: reviewed-approved

#4291 fix(module:tooltip): fix tooltip component not destory
  components/tooltip/base/nz-tooltip-base.directive.ts
Labels: PR: unreviewed

#4293 release(8.4.0): release 8.4.0
  CHANGELOG.md
  components/package.json
  components/version/version.ts
  docs/changelog.en-US.md
  docs/changelog.zh-CN.md
Labels: PR: unreviewed

#4302 typo: font-end --> front-end
  components/select/demo/frontend-search.md
Labels: PR: reviewed-approved

#4298 docs(module:tooltip etc): trigger could be null
  components/popconfirm/doc/index.en-US.md
  components/popconfirm/doc/index.zh-CN.md
  components/popover/doc/index.en-US.md
  components/popover/doc/index.zh-CN.md
  components/tooltip/base/nz-tooltip-base.directive.ts
  components/tooltip/doc/index.en-US.md
  components/tooltip/doc/index.zh-CN.md
Labels: PR: reviewed-approved, PR: target-patch, PR: unreviewed

#4329 fix(module:table): fix table nzWidth bug without the first column
  components/table/nz-table.component.html
  components/table/nz-table.spec.ts
  components/table/nz-th.spec.ts
Labels: PR: unreviewed

#4321 docs: explain how to submit TemplateRef instances in global config
  docs/global-config.en-US.md
Labels: PR: reviewed-approved

#4332 docs: add template providing cn
  docs/global-config.en-US.md
  docs/global-config.zh-CN.md
Labels: PR: reviewed-approved

#4325 fix(module:core): fix global config not working in prod mode
  components/affix/nz-affix.component.ts
  components/alert/nz-alert.component.ts
  components/anchor/nz-anchor.component.ts
  components/avatar/nz-avatar.component.ts
  components/back-top/nz-back-top.component.ts
  components/badge/nz-badge.component.ts
  components/button/nz-button.component.ts
  components/card/nz-card.component.ts
  components/carousel/nz-carousel.component.ts
  components/cascader/nz-cascader.component.ts
  components/collapse/nz-collapse-panel.component.ts
  components/collapse/nz-collapse.component.ts
  components/core/config/config.service.ts
  components/core/config/config.spec.ts
  components/descriptions/nz-descriptions.component.ts
  components/drawer/nz-drawer.component.ts
  components/form/nz-form.directive.ts
  components/icon/nz-icon.service.ts
  components/message/nz-message-container.component.ts
  components/modal/nz-modal.component.ts
  components/notification/nz-notification-container.component.ts
  components/progress/nz-progress.component.ts
  components/rate/nz-rate.component.ts
  components/spin/nz-spin.component.ts
  components/switch/nz-switch.component.ts
  components/table/nz-table.component.ts
  components/tabs/nz-tabset.component.ts
  components/time-picker/nz-time-picker.component.ts
  components/tree-select/nz-tree-select.component.ts
  components/tree/nz-tree.component.ts
  components/typography/nz-typography.component.ts
Labels: PR: reviewed-approved, PR: target-patch

#4327 docs(module:message,notification): use global configuration service
  components/message/doc/index.en-US.md
  components/message/doc/index.zh-CN.md
  components/message/nz-message-base.service.ts
  components/notification/doc/index.en-US.md
  components/notification/doc/index.zh-CN.md
Labels: PR: reviewed-approved

#4303 fix(module:page-header): fix break change on the style
  components/page-header/nz-page-header.component.ts
  components/page-header/style/index.less
Labels: PR: unreviewed

#4311 fix(module:drawer): fix the HTML structure of the drawer header
  components/drawer/nz-drawer.component.html
  components/drawer/nz-drawer.spec.ts
Labels: PR: unreviewed

#4335 release(8.4.1): release 8.4.1
  CHANGELOG.md
  components/package.json
  components/version/version.ts
  docs/changelog.en-US.md
  docs/changelog.zh-CN.md
Labels: PR: unreviewed

#4349 docs: update doc features
  README-zh_CN.md
  README.md
  docs/introduce.en-US.md
  docs/introduce.zh-CN.md
Labels: PR: unreviewed

#4355 docs(module:code-editor): fix component type
  components/code-editor/doc/index.en-US.md
Labels: PR: reviewed-approved
