Repository NG-ZORRO/ng-zorro-antd, pull requests merged in 2019-03, with the labels that each got.

#3091 fix(module:tooltip): fix tooltip not render after set
  components/tooltip/nz-tooltip.directive.ts
  components/tooltip/nz-tooltip.spec.ts
Labels: PR::eyes: Need Review

#3088 docs: add browser language detection
  scripts/site/_site/doc/app/app.component.ts
  scripts/site/_site/doc/app/app.routing.module.ts
Labels: PR::eyes: Need Review

#3065 fix(module:modal): integrate with tabs and autosize
  components/input/demo/autosize-textarea.md
  components/input/nz-autosize.directive.ts
  components/input/nz-autosize.spec.ts
  components/input/nz-input.module.ts
  components/modal/nz-modal.component.html
  components/modal/nz-modal.spec.ts
Labels: PR::eyes: Need Review

#3037 fix(module:cascader): fix columns not dropped
  components/cascader/nz-cascader-definitions.ts
  components/cascader/nz-cascader-li.component.html
  components/cascader/nz-cascader-li.component.ts
  components/cascader/nz-cascader-utils.ts
  components/cascader/nz-cascader.component.html
  components/cascader/nz-cascader.component.ts
  components/cascader/nz-cascader.service.ts
  components/cascader/nz-cascader.spec.ts
  components/cascader/public-api.ts
Labels: PR::eyes: Need Review

#3060 fix(module: tree): fix nzMultiple and rollback code
  components/tree-select/demo/async.ts
  components/tree/demo/basic.ts
  components/tree/demo/directory.ts
  components/tree/demo/draggable.ts
  components/tree/demo/dynamic.ts
  components/tree/demo/search.ts
  components/tree/doc/index.en-US.md
  components/tree/doc/index.zh-CN.md
  components/tree/interface.ts
  components/tree/nz-tree-base.service.ts
  components/tree/nz-tree-node.component.html
  components/tree/nz-tree-node.component.ts
  components/tree/nz-tree-node.ts
  components/tree/nz-tree.component.html
  components/tree/nz-tree.component.ts
  components/tree/nz-tree.module.ts
  components/tree/nz-tree.spec.ts
  components/tree/public-api.ts
Labels: PR::eyes: Need Review

#3133 fix(module:dropdown): fix the style of CDK conflicts
  components/dropdown/nz-dropdown-button.component.html
  components/dropdown/nz-dropdown.component.html
  components/dropdown/nz-dropdown.module.ts
Labels: PR: :heavy_check_mark: Merge Ready

#2732 feat(module:page-header): add page-header component
  components/components.less
  components/ng-zorro-antd.module.ts
  components/page-header/demo/actions.md
  components/page-header/demo/actions.ts
  components/page-header/demo/basic.md
  components/page-header/demo/basic.ts
  components/page-header/demo/breadcrumb.md
  components/page-header/demo/breadcrumb.ts
  components/page-header/demo/content.md
  components/page-header/demo/content.ts
  components/page-header/doc/index.en-US.md
  components/page-header/doc/index.zh-CN.md
  components/page-header/index.ts
  components/page-header/nz-page-header-cells.ts
  components/page-header/nz-page-header.component.html
  components/page-header/nz-page-header.component.less
  components/page-header/nz-page-header.component.ts
  components/page-header/nz-page-header.module.ts
  components/page-header/nz-page-header.spec.ts
  components/page-header/public-api.ts
  components/page-header/style/index.less
Labels: :star: New Component, PR: :heavy_check_mark: Merge Ready

#3089 fix(module:affix): set correct style of Affix after trigger resize
  components/affix/nz-affix.component.ts
Labels: PR: :heavy_check_mark: Merge Ready

#3114 fix(module:upload): fix missing remove event when type is drag
  components/upload/nz-upload.component.html
  components/upload/upload.spec.ts
Labels: PR: :heavy_check_mark: Merge Ready

#3135 fix(module:progress): should not set success when success percent is …
  components/progress/demo/circle-dynamic.ts
  components/progress/demo/round.md
  components/progress/demo/round.ts
  components/progress/nz-progress.component.html
  components/progress/nz-progress.component.ts
  components/progress/nz-progress.spec.ts
Labels: PR: :heavy_check_mark: Merge Ready

#3161 fix(module:transfer): fix invalid trigger checked event in blank area
  components/transfer/nz-transfer-list.component.html
  components/transfer/nz-transfer.component.ts
  components/transfer/transfer.spec.ts
Labels: PR: :heavy_check_mark: Merge Ready

#3166 fix: fix type of some API
  components/icon/page/index.ts
  components/modal/nz-modal.component.ts
  components/modal/nz-modal.type.ts
  components/table/nz-table.component.ts
  components/tooltip/nz-tooltip.component.ts
  components/tooltip/nz-tooltip.directive.ts
Labels: PR: :heavy_check_mark: Merge Ready

#3176 feat(module:menu): support `nzMenuClassName` for the submenu
  components/menu/doc/index.en-US.md
  components/menu/doc/index.zh-CN.md
  components/menu/nz-menu.spec.ts
  components/menu/nz-submenu.component.html
  components/menu/nz-submenu.component.ts
Labels: PR: :heavy_check_mark: Merge Ready

#3174 fix(module:breadcrumb): fix auto generate not working in lazy modules
  components/breadcrumb/nz-breadcrumb.component.ts
Labels: PR: :heavy_check_mark: Merge Ready

#3177 feat(module:collapse): support `nzExtra`
  components/collapse/demo/extra.md
  components/collapse/demo/extra.ts
  components/collapse/doc/index.en-US.md
  components/collapse/doc/index.zh-CN.md
  components/collapse/nz-collapse-panel.component.html
  components/collapse/nz-collapse-panel.component.ts
  components/collapse/nz-collapse.spec.ts
  components/collapse/style/index.less
  components/style/themes/default.less
  scripts/site/_site/doc/theme.less
Labels: PR: :heavy_check_mark: Merge Ready
