Repository NG-ZORRO/ng-zorro-antd, pull requests merged in 2019-12, with the labels that each got.

#4491 feat(module:i18n): support for Georgian locale
  components/i18n/languages/calendar/ka_GE.ts
  components/i18n/languages/date-picker/ka_GE.ts
  components/i18n/languages/ka_GE.ts
  components/i18n/languages/pagination/ka_GE.ts
  components/i18n/languages/time-picker/ka_GE.ts
  components/i18n/public-api.ts
  docs/i18n.en-US.md
  docs/i18n.zh-CN.md
Labels: PR: reviewed-approved

#4490 fix(module:date-picker): select date but nzDefaultOpenValue not work
  components/core/time/candy-date.ts
  components/date-picker/lib/popups/inner-popup.component.html
  components/date-picker/lib/popups/inner-popup.component.ts
  components/date-picker/nz-date-picker.component.spec.ts
  components/date-picker/standard-types.ts
Labels: PR: reviewed-approved

#4500 chore: update contributor assign
  .github/auto_assign.yml
  .github/nz-boot.yml
  README-zh_CN.md
  README.md
  docs/getting-started.en-US.md
  docs/introduce.en-US.md
  package.json
Labels: PR: unreviewed

#4518 chore: change maintainer's username
  .github/auto_assign.yml
  .github/nz-boot.yml
  components/carousel/nz-carousel.spec.ts
  components/core/types/size.ts
Labels: PR: reviewed-approved

#4450 docs: correct grammar within English docs
  components/table/demo/ajax.md
Labels: :scroll: Doc, PR: reviewed-approved, PR: unreviewed

#4512 refactor: rename private theta APIs
  components/result/public-api.ts
Labels: PR: reviewed-approved

#4499 build: remove the old builds for the site
  scripts/release/release-site.ts
Labels: PR: reviewed-approved

#4514 docs(module:layout): update breakpoint width
  components/layout/doc/index.en-US.md
Labels: PR: reviewed-approved

#4493 refactor(module:core): add isPromise generic
  components/core/util/is-promise.ts
  components/modal/nz-modal.component.ts
Labels: PR: reviewed-approved

#4479 docs: update sitemap and meta
  README-zh_CN.md
  README.md
  angular.json
  package.json
  scripts/prerender/sitemap.ts
  scripts/site/_site/doc/app/app.component.html
  scripts/site/_site/doc/app/app.component.ts
  scripts/site/_site/doc/assets/img/site-preview.png
  scripts/site/_site/doc/index.html
Labels: PR: reviewed-approved

#4495 feat(module:notification): add close icon prop
  components/notification/doc/index.en-US.md
  components/notification/doc/index.zh-CN.md
  components/notification/nz-notification.component.html
  components/notification/nz-notification.definitions.ts
  components/notification/nz-notification.module.ts
  components/notification/nz-notification.spec.ts
Labels: PR: reviewed-approved

#4533 test: fix broken test
  components/empty/nz-empty.spec.ts
Labels: PR: reviewed-approved

#4540 ci: add circleci
  .circleci/config.yml
  components/karma.conf.js
  integration/angular-cli/package.json
  integration/rollup/package.json
  integration/webpack/package.json
  package.json
  scripts/gulp/util/task-helpers.ts
  setup-shared-libs.sh
Labels: PR: unreviewed

#4542 ci: fix coverage
  .circleci/config.yml
  package.json
  setup-shared-libs.sh
Labels: PR: unreviewed

#4547 ci: set up ci with azure pipelines
  azure-pipelines.yml
  components/karma.conf.js
  package.json
Labels: PR: unreviewed

#4548 ci: azure-ci rename
  .gitignore
  .travis.yml
  README-zh_CN.md
  README.md
  azure-pipelines.yml
  components/karma.conf.js
  package.json
  scripts/gulp/tasks/site.ts
  scripts/surge.sh
Labels: PR: unreviewed

#4550 ci: add cobertura report
  .circleci/config.yml
  .gitignore
  azure-pipelines.yml
  components/karma.conf.js
Labels: PR: unreviewed

#4555 build: more strict tsconfig
  components/auto-complete/nz-autocomplete-trigger.directive.ts
  components/breadcrumb/nz-breadcrumb.component.ts
  components/core/overlay/overlay-position.ts
  components/progress/nz-progress-utils.ts
  components/tsconfig.spec.json
  tsconfig.json
Labels: PR: unreviewed

#4582 chore: update bot config
  .github/nz-boot.yml
Labels: PR: reviewed-approved

#4589 docs(module:autocomplete): fix basic demo
  components/auto-complete/demo/basic.ts
Labels: PR: reviewed-approved

#4604 docs: fix development instructions
  README-zh_CN.md
  README.md
Labels: PR: reviewed-approved
