Repository NG-ZORRO/ng-zorro-antd, pull requests merged in 2019-02, with the labels that each got.

#2856 feat(module:modal): support set `nzOkDisabled` and `nzCancelDisabled`
  components/modal/doc/index.en-US.md
  components/modal/doc/index.zh-CN.md
  components/modal/nz-modal.component.html
  components/modal/nz-modal.component.ts
  components/modal/nz-modal.spec.ts
  components/modal/nz-modal.type.ts
Labels: PR: :heavy_check_mark: Merge Ready

#2841 feat(module:input): fix *fix icon new api capability
  components/icon/nz-icon.directive.ts
  components/icon/nz-icon.spec.ts
  components/input/demo/addon.ts
  components/input/nz-input-group.component.html
  components/input/nz-input-group.spec.ts
  components/input/nz-input.spec.ts
  components/table/nz-thead.spec.ts
Labels: PR::eyes: Need Review

#2794 feat(module:rate): add tooltip support
  components/core/util/keycodes.ts
  components/core/util/public-api.ts
  components/icon/nz-icon.service.ts
  components/rate/demo/text.ts
  components/rate/doc/index.en-US.md
  components/rate/doc/index.zh-CN.md
  components/rate/nz-rate-item.component.html
  components/rate/nz-rate-item.component.ts
  components/rate/nz-rate.component.html
  components/rate/nz-rate.component.ts
  components/rate/nz-rate.module.ts
  components/rate/nz-rate.spec.ts
Labels: PR::eyes: Need Review

#2789 docs: optimize mobile experience
  scripts/site/_site/src/app/app.component.html
  scripts/site/_site/src/app/app.component.ts
  scripts/site/_site/src/app/app.module.ts
  scripts/site/_site/src/style/common.less
  scripts/site/_site/src/style/drawer.less
  scripts/site/_site/src/style/footer.less
  scripts/site/_site/src/style/icons.less
  scripts/site/_site/src/style/index.less
  scripts/site/_site/src/style/patch.less
  scripts/site/_site/src/style/responsive.less
Labels: :scroll: Doc, PR::eyes: Need Review

#2635 refactor(module:date-picker, time-picker): use OnPush as the default change detect…
  components/date-picker/abstract-picker.component.ts
  components/date-picker/date-picker.component.ts
  components/date-picker/date-range-picker.component.ts
  components/date-picker/header-picker.component.ts
  components/date-picker/lib/calendar/calendar-footer.component.ts
  components/date-picker/lib/calendar/calendar-header.component.ts
  components/date-picker/lib/calendar/calendar-input.component.ts
  components/date-picker/lib/calendar/ok-button.component.ts
  components/date-picker/lib/calendar/time-picker-button.component.ts
  components/date-picker/lib/calendar/today-button.component.ts
  components/date-picker/lib/candy-date/index.ts
  components/date-picker/lib/date-change-event.ts
  components/date-picker/lib/date/date-table.component.ts
  components/date-picker/lib/decade/decade-panel.component.ts
  components/date-picker/lib/lib-packer-supplements.spec.ts
  components/date-picker/lib/month/month-panel.component.ts
  components/date-picker/lib/month/month-table.component.ts
  components/date-picker/lib/popups/date-range-popup.component.ts
  components/date-picker/lib/popups/inner-popup.component.ts
  components/date-picker/lib/year/year-panel.component.ts
  components/date-picker/month-picker.component.ts
  components/date-picker/picker.component.ts
  components/date-picker/range-picker.component.ts
  components/date-picker/standard-types.ts
  components/date-picker/week-picker.component.ts
  components/date-picker/year-picker.component.ts
  components/time-picker/nz-time-picker-panel.component.ts
  components/time-picker/nz-time-picker.component.spec.ts
  components/time-picker/nz-time-picker.component.ts
  components/time-picker/nz-time-value-accessor.directive.spec.ts
Labels: PR::wave: Need Change

#2699 refactor(module:carousel): refactor
  components/carousel/demo/basic.ts
  components/carousel/nz-carousel-content.directive.ts
  components/carousel/nz-carousel.component.html
  components/carousel/nz-carousel.component.ts
  components/carousel/nz-carousel.spec.ts
  components/core/util/convert.ts
Labels: PR::eyes: Need Review

#2846 fix(module:cascader): fix searching error when nzOptions is an empty …
  components/cascader/nz-cascader.component.html
  components/cascader/nz-cascader.component.ts
  components/cascader/nz-cascader.spec.ts
  components/empty/demo/config.ts
  components/empty/demo/customize.ts
Labels: PR::eyes: Need Review

#2783 feat(module:collapse): support custom icon
  components/collapse/demo/custom.md
  components/collapse/demo/custom.ts
  components/collapse/doc/index.en-US.md
  components/collapse/doc/index.zh-CN.md
  components/collapse/nz-collapse-panel.component.html
  components/collapse/nz-collapse-panel.component.ts
  components/collapse/nz-collapse.spec.ts
Labels: PR::wave: Need Change, 🤚 Blocked

#2917 fix(module:core): fix the style of CDK conflicts
  components/cascader/nz-cascader.component.html
  components/cascader/nz-cascader.module.ts
  components/core/overlay/nz-connected-overlay.ts
  components/core/overlay/nz-overlay.module.ts
  components/core/style/index.less
  components/date-picker/date-picker.module.ts
  components/date-picker/picker.component.html
  components/popconfirm/nz-popconfirm.component.html
  components/popconfirm/nz-popconfirm.module.ts
  components/popover/nz-popover.component.html
  components/popover/nz-popover.module.ts
  components/select/nz-select.component.html
  components/select/nz-select.module.ts
  components/time-picker/nz-time-picker.component.html
  components/time-picker/nz-time-picker.module.ts
  components/tooltip/nz-tooltip.component.html
  components/tooltip/nz-tooltip.module.ts
  components/tree-select/nz-tree-select.module.ts
Labels: PR::eyes: Need Review

#2957 docs(module:icon): update icons
  components/icon/page/index.ts
Labels: Component: Icon

#2898 refactor(module:tree-select): refactor tree-select component
  components/core/animation/select-dropdown-animations.ts
  components/pagination/nz-pagination.spec.ts
  components/tree-select/nz-tree-select.component.html
  components/tree-select/nz-tree-select.component.ts
  components/tree-select/nz-tree-select.service.ts
  components/tree-select/nz-tree-select.spec.ts
  components/tree/interface.ts
  components/tree/nz-tree-base.service.ts
  components/tree/nz-tree-node.component.html
  components/tree/nz-tree-node.component.ts
  components/tree/nz-tree-node.ts
  components/tree/nz-tree.component.html
  components/tree/nz-tree.component.ts
  components/tree/nz-tree.service.ts
  components/tree/nz-tree.spec.ts
  components/tree/public-api.ts
Labels: PR::eyes: Need Review

#2037 fix(module:drawer): ngOnDestory may called before onInit
  components/drawer/nz-drawer.component.ts
Labels: PR::eyes: Need Review

#2767 feat(module:comment): add comment component
  components/comment/demo/basic.md
  components/comment/demo/basic.ts
  components/comment/demo/editor.md
  components/comment/demo/editor.ts
  components/comment/demo/list.md
  components/comment/demo/list.ts
  components/comment/demo/nested.md
  components/comment/demo/nested.ts
  components/comment/doc/index.en-US.md
  components/comment/doc/index.zh-CN.md
  components/comment/index.ts
  components/comment/nz-comment-cells.ts
  components/comment/nz-comment.component.html
  components/comment/nz-comment.component.ts
  components/comment/nz-comment.module.ts
  components/comment/nz-comment.spec.ts
  components/comment/public-api.ts
  components/comment/style/index.less
  components/components.less
  components/empty/nz-empty.spec.ts
  components/ng-zorro-antd.module.ts
Labels: :star: New Component, PR::eyes: Need Review

#2963 feat(module:calendar): sync some changes from ant-design (#2769)
  components/calendar/demo/basic.ts
  components/calendar/demo/select.ts
  components/calendar/doc/index.en-US.md
  components/calendar/doc/index.zh-CN.md
  components/calendar/nz-calendar.component.ts
  components/calendar/nz-calendar.spec.ts
Labels: PR::wave: Need Change
