Repository NG-ZORRO/ng-zorro-antd, pull requests merged in 2019-07, with the labels that each got.

#3694 docs(site): zorro twitter connection error
  scripts/site/_site/doc/app/app.component.html
Labels: PR: reviewed-approved

#3692 fix(module: tree): fix warning bug
  components/tree/demo/basic.ts
  components/tree/demo/directory.ts
  components/tree/nz-tree-node.component.html
  components/tree/nz-tree.component.html
  components/tree/nz-tree.component.ts
Labels: PR: reviewed-approved

#3695 fix(schematics): missing routing module in sidemenu template
  schematics/ng-generate/side-menu/files/src/app/pages/welcome/welcome-routing.module.ts.template
  schematics/ng-generate/side-menu/files/src/app/pages/welcome/welcome.module.ts.template
Labels: PR: unreviewed

#3697 release(8.0.1): release 8.0.1
  CHANGELOG.md
  components/package.json
  components/version.ts
  docs/changelog.en-US.md
  docs/changelog.zh-CN.md
  scripts/site/_site/doc/app/app.component.ts
  scripts/site/_site/doc/app/share/nz-codebox/stack-blitz.ts
Labels: PR: unreviewed

#3726 release(8.0.2): release 8.0.2
  CHANGELOG.md
  components/package.json
  components/version.ts
  docs/changelog.en-US.md
  docs/changelog.zh-CN.md
  package.json
  scripts/site/_site/doc/app/app.component.ts
  scripts/site/_site/doc/app/share/nz-codebox/stack-blitz.ts
Labels: PR: reviewed-approved

#3741 docs: Modify Component Dev Kit error link
  docs/recommendation.en-US.md
  docs/recommendation.zh-CN.md
Labels: PR: reviewed-approved

#3776 build: update icon dependency
  components/icon/nz-icon.service.ts
  components/package.json
  package.json
Labels: PR: reviewed-approved

#3783 revert: revert update icon dependency
  components/icon/nz-icon.service.ts
  components/package.json
  package.json
Labels: PR: unreviewed

#3782 fix(module:dropdown): fix dropdown contextmenu
  components/dropdown/nz-context-menu.service.ts
Labels: PR: unreviewed

#3784 fix(module:switch): fix switch ViewChild static
  components/switch/nz-switch.component.ts
Labels: PR: unreviewed

#3785 fix(module:menu): fix menu nzMatchRouter in nested menu
  components/menu/nz-menu-item.directive.ts
Labels: PR: unreviewed

#3787 fix(module:table): fix table custom filter panel
  components/table/nz-th.component.html
Labels: PR: unreviewed

#3778 docs: update faq and fix module list of breadcrumb
  components/breadcrumb/demo/module
  components/rate/demo/module
  components/slider/demo/module
  components/timeline/demo/module
  docs/faq.en-US.md
  docs/faq.zh-CN.md
Labels: PR: reviewed-approved

#3786 fix(module:input): fix input disabled OnPush
  components/input/nz-input.directive.ts
  components/input/nz-input.module.ts
  components/input/nz-input.spec.ts
Labels: PR: reviewed-approved

#3789 fix(module:all): fix singleton service
  components/empty/nz-empty.module.ts
  components/empty/nz-empty.service.module.ts
  components/empty/nz-empty.service.ts
  components/empty/public-api.ts
  components/i18n/date-helper.service.module.ts
  components/i18n/date-helper.service.ts
  components/i18n/nz-i18n.module.ts
  components/i18n/nz-i18n.service.module.ts
  components/i18n/nz-i18n.service.ts
  components/i18n/public-api.ts
  components/icon/nz-icon.module.ts
  components/icon/nz-icon.service.module.ts
  components/icon/nz-icon.service.ts
  components/icon/public-api.ts
  components/message/nz-message.module.ts
  components/message/nz-message.service.module.ts
  components/message/nz-message.service.ts
  components/message/public-api.ts
  components/notification/nz-notification.module.ts
  components/notification/nz-notification.service.module.ts
  components/notification/nz-notification.service.ts
  components/notification/public-api.ts
Labels: PR: reviewed-approved

#3790 release(8.0.3): release 8.0.3
  CHANGELOG.md
  components/package.json
  components/version.ts
  docs/changelog.en-US.md
  docs/changelog.zh-CN.md
  package.json
  scripts/site/_site/doc/app/app.component.ts
  scripts/site/_site/doc/app/share/nz-codebox/stack-blitz.ts
Labels: PR: unreviewed

#3707 fix(module:modal): buttons cannot disable when confirm mode
  components/modal/nz-modal.component.html
  components/modal/nz-modal.component.ts
  components/modal/nz-modal.spec.ts
Labels: PR: reviewed-approved

#3564 build: refactor scripts
  .gitignore
  .travis.yml
  build-config.js
  components/karma.conf.js
  components/test.ts
  docs/contributing.en-US.md
  docs/contributing.zh-CN.md
  gulpfile.js
  package.json
  scripts/build-config.ts
  scripts/build/compile-styles.js
  scripts/build/compile-styles.ts
  scripts/build/migration-styles.js
  scripts/build/migration-styles.ts
  scripts/build/replace-publish.sh
  scripts/gulp/gulpfile.ts
  scripts/gulp/tasks/clean.ts
  scripts/gulp/tasks/default.ts
  scripts/gulp/tasks/library.ts
  scripts/gulp/tasks/release.ts
  scripts/gulp/tasks/schematic.ts
  scripts/gulp/tasks/site.ts
  scripts/gulp/tasks/unit-test.ts
  scripts/gulp/tasks/universal.ts
  scripts/gulp/tsconfig.json
  scripts/gulp/util/task-helpers.ts
  scripts/prerender/prerender.ts
  scripts/prerender/sitemap.ts
  scripts/publish/publish.js
  scripts/release/git-client.ts
  scripts/release/parse-version.ts
  scripts/release/release-site.ts
  scripts/release/release.ts
  scripts/release/tsconfig.json
  scripts/schematics/copy-resources.js
  scripts/schematics/copy-resources.ts
  scripts/schematics/demo2schematics.ts
  scripts/schematics/set-theme.js
  scripts/schematics/set-theme.ts
  scripts/schematics/set-version.js
  scripts/schematics/set-version.ts
  scripts/site/generate-site.js
  scripts/site/generateColorLess.js
Labels: PR: reviewed-approved

#3769 feat(module:dropdown): allow backdrop to be disabled
  components/dropdown/doc/index.en-US.md
  components/dropdown/doc/index.zh-CN.md
  components/dropdown/nz-dropdown.directive.spec.ts
  components/dropdown/nz-dropdown.directive.ts
Labels: PR: reviewed-approved

#3781 fix(module:date-picker): missing nzUse12Hours binding
  components/date-picker/lib/popups/inner-popup.component.html
Labels: PR: reviewed-approved

#3801 fix(module:table): fix table scrollbar bug
  components/core/services/nz-measure-scrollbar.service.module.ts
  components/core/services/nz-measure-scrollbar.service.ts
  components/core/services/public-api.ts
  components/core/util/measure-scrollbar.ts
  components/core/util/public-api.ts
  components/modal/nz-modal.spec.ts
  components/table/nz-table.component.ts
  components/table/nz-table.module.ts
  components/table/nz-tbody.spec.ts
  components/table/nz-thead.spec.ts
  components/table/nz-tr.spec.ts
  package.json
Labels: PR: unreviewed

#3724 chore(module:*): introduce global dom event service
  components/carousel/nz-carousel.component.ts
  components/core/services/nz-dom-event.service.ts
  components/core/services/public-api.ts
  components/descriptions/nz-descriptions.component.ts
  components/form/nz-form-item.component.ts
  components/grid/nz-row.directive.ts
  components/input/nz-autosize.directive.ts
  components/layout/nz-sider.component.ts
  components/tabs/nz-tabs-nav.component.ts
  components/typography/nz-typography.component.ts
  components/upload/nz-upload.spec.ts
Labels: PR: reviewed-approved

#3803 fix(module:page-header): fix page-header style break change
  components/core/util/measure-scrollbar.ts
  components/page-header/demo/module
  components/page-header/nz-page-header-cells.ts
  components/page-header/nz-page-header.component.html
  components/page-header/nz-page-header.spec.ts
Labels: PR: unreviewed

#3799 fix(module:descriptions): fix span calculation
  components/descriptions/demo/responsive.ts
  components/descriptions/nz-descriptions.component.html
  components/descriptions/nz-descriptions.component.ts
  components/descriptions/nz-descriptions.spec.ts
Labels: PR: reviewed-approved

#3802 fix(module:select): fix single selection choice content display issues
  components/select/nz-select-top-control.component.html
Labels: PR: reviewed-approved

#3797 fix(module:message): fix lazy load problem
  components/breadcrumb/nz-breadcrumb.component.ts
  components/message/nz-message-base.service.ts
  components/message/nz-message.module.ts
  components/message/nz-message.service.module.ts
  components/message/nz-message.service.ts
  components/message/nz-message.spec.ts
  components/message/public-api.ts
  components/notification/nz-notification.module.ts
  components/notification/nz-notification.service.module.ts
  components/notification/nz-notification.service.ts
  components/notification/nz-notification.spec.ts
  components/notification/public-api.ts
  components/typography/nz-typography.spec.ts
Labels: PR: reviewed-approved

#3798 fix(module:descriptions): fix changes to inputs of children not working
  components/descriptions/doc/index.zh-CN.md
  components/descriptions/nz-descriptions-item.component.ts
  components/descriptions/nz-descriptions.component.ts
  components/descriptions/nz-descriptions.spec.ts
  components/page-header/doc/index.zh-CN.md
Labels: PR: reviewed-approved

#3806 fix(module:table): fix table header scroll when fixed change
  components/table/nz-table.component.ts
Labels: PR: unreviewed

#3807 refactor(module:version): add secondary entries
  components/ng-zorro-antd.module.ts
  components/version.ts
  components/version/index.ts
  components/version/package.json
  components/version/public-api.ts
  components/version/version.ts
  docs/universal.en-US.md
  docs/universal.zh-CN.md
  schematics/ng-update/index.ts
  scripts/release/release.ts
  scripts/site/_site/doc/app/app.component.ts
  scripts/site/_site/doc/app/share/nz-codebox/nz-codebox.component.ts
  scripts/site/_site/doc/app/share/nz-codebox/stack-blitz.ts
  scripts/site/generate-site.js
Labels: PR: reviewed-approved

#3812 docs: update users list
  README-zh_CN.md
  README.md
  docs/introduce.en-US.md
  docs/introduce.zh-CN.md
Labels: PR: reviewed-approved

#3800 feat(module:descriptions): support vertical mode
  components/descriptions/demo/vertical-border.md
  components/descriptions/demo/vertical-border.ts
  components/descriptions/demo/vertical.md
  components/descriptions/demo/vertical.ts
  components/descriptions/nz-descriptions-definitions.ts
  components/descriptions/nz-descriptions.component.html
  components/descriptions/nz-descriptions.component.ts
Labels: PR: reviewed-approved

#3718 feat(module:tabs): support link router
  components/descriptions/nz-descriptions.component.html
  components/tabs/demo/link-router.md
  components/tabs/demo/link-router.ts
  components/tabs/doc/index.en-US.md
  components/tabs/doc/index.zh-CN.md
  components/tabs/nz-tab-link.directive.ts
  components/tabs/nz-tab.component.html
  components/tabs/nz-tab.component.ts
  components/tabs/nz-tabs.module.ts
  components/tabs/nz-tabs.spec.ts
  components/tabs/nz-tabset.component.html
  components/tabs/nz-tabset.component.ts
  components/tabs/public-api.ts
  components/tabs/style/entry.less
  components/tabs/style/patch.less
  scripts/site/_site/doc/app/app.component.ts
  scripts/site/_site/doc/app/app.module.ts
Labels: PR: reviewed-approved

#3748 fix(module:tree): unexpected disappear of tree-node
  components/core/tree/nz-tree-base-node.ts
  components/tree/nz-tree-node.component.ts
  components/tree/nz-tree.spec.ts
Labels: PR: reviewed-approved

#3731 feat(module:result): add component
  components/components.less
  components/ng-zorro-antd.module.ts
  components/result/demo/custom.md
  components/result/demo/custom.ts
  components/result/demo/error.md
  components/result/demo/error.ts
  components/result/demo/fof.md
  components/result/demo/fof.ts
  components/result/demo/foo.md
  components/result/demo/foo.ts
  components/result/demo/fot.md
  components/result/demo/fot.ts
  components/result/demo/info.md
  components/result/demo/info.ts
  components/result/demo/module
  components/result/demo/success.md
  components/result/demo/success.ts
  components/result/demo/warning.md
  components/result/demo/warning.ts
  components/result/doc/index.en-US.md
  components/result/doc/index.zh-CN.md
  components/result/index.ts
  components/result/nz-result-cells.ts
  components/result/nz-result.component.html
  components/result/nz-result.component.ts
  components/result/nz-result.module.ts
  components/result/nz-result.spec.ts
  components/result/package.json
  components/result/partial/not-found.ts
  components/result/partial/server-error.component.ts
  components/result/partial/unauthorized.ts
  components/result/public-api.ts
  components/result/style/entry.less
  components/result/style/index.less
  components/test.ts
Labels: :star: New Component, PR: reviewed-approved, PR: unreviewed

#3729 feat(module:tree-select): add [nzHideUnMatched] property
  components/tree-select/doc/index.en-US.md
  components/tree-select/doc/index.zh-CN.md
  components/tree-select/nz-tree-select.component.html
  components/tree-select/nz-tree-select.component.ts
Labels: PR: reviewed-approved

#3036 feat(module:modal): support use directive to define the footer
  components/modal/demo/confirm.md
  components/modal/demo/footer2.md
  components/modal/demo/footer2.ts
  components/modal/demo/info.md
  components/modal/demo/locale.md
  components/modal/demo/manual.md
  components/modal/demo/position.md
  components/modal/demo/service.md
  components/modal/doc/index.en-US.md
  components/modal/doc/index.zh-CN.md
  components/modal/nz-modal-footer.directive.spec.ts
  components/modal/nz-modal-footer.directive.ts
  components/modal/nz-modal.component.ts
  components/modal/nz-modal.module.ts
  components/modal/public-api.ts
  package.json
Labels: PR: reviewed-approved

#3820 release(8.1.0): release 8.1.0
  CHANGELOG.md
  components/package.json
  components/version/version.ts
  docs/changelog.en-US.md
  docs/changelog.zh-CN.md
Labels: PR: reviewed-approved

#3836 docs: fix input demo
  components/input/demo/module
Labels: PR: reviewed-approved

#3824 docs: fix result import
  components/result/demo/module
Labels: PR: reviewed-approved

#3840 build: fix release scripts
  scripts/release/git-client.ts
  scripts/release/release-site.ts
  scripts/release/release.ts
Labels: PR: reviewed-approved

#3849 fix(module:table): fix table small sticky style
  components/table/style/patch.less
Labels: PR: reviewed-approved

#3869 fix(module:select): fix select with tokenization bug
  components/select/nz-select-top-control.component.ts
Labels: PR: unreviewed

#3856 fix(schematics): update copy-resources script to support Windows path
  scripts/schematics/copy-resources.ts
Labels: PR: reviewed-approved

#3823 fix(module:*): import PlatformModule when use platform in component
  components/affix/nz-affix.module.ts
  components/anchor/nz-anchor.module.ts
  components/avatar/nz-avatar.module.ts
  components/back-top/nz-back-top.module.ts
  components/carousel/nz-carousel.module.ts
  components/descriptions/nz-descriptions.module.ts
  components/icon/nz-icon.module.ts
  components/menu/nz-menu.module.ts
  components/select/nz-select.module.ts
  components/slider/nz-slider.module.ts
  components/statistic/nz-statistic.module.ts
  components/table/nz-table.module.ts
  components/timeline/nz-timeline.module.ts
  components/typography/nz-typography.module.ts
  components/upload/nz-upload.module.ts
Labels: PR: reviewed-approved

#3780 refactor(module:date-picker, module:calendar): merge the repeated components
  components/calendar/date-table-cell.component.html
  components/calendar/date-table-cell.component.ts
  components/calendar/date-table.component.html
  components/calendar/date-table.component.ts
  components/calendar/month-table.component.html
  components/calendar/month-table.component.ts
  components/calendar/nz-calendar-header.component.html
  components/calendar/nz-calendar-header.component.ts
  components/calendar/nz-calendar-header.spec.ts
  components/calendar/nz-calendar.component.html
  components/calendar/nz-calendar.component.ts
  components/calendar/nz-calendar.module.ts
  components/calendar/nz-calendar.spec.ts
  components/calendar/public-api.ts
  components/core/public-api.ts
  components/core/time/candy-date.spec.ts
  components/core/time/candy-date.ts
  components/core/time/index.ts
  components/core/time/public-api.ts
  components/core/time/time.ts
  components/core/util/public-api.ts
  components/date-picker/abstract-picker.component.ts
  components/date-picker/date-range-picker.component.ts
  components/date-picker/header-picker.component.ts
  components/date-picker/lib/calendar/calendar-footer.component.ts
  components/date-picker/lib/calendar/calendar-header.component.ts
  components/date-picker/lib/calendar/calendar-input.component.ts
  components/date-picker/lib/calendar/today-button.component.ts
  components/date-picker/lib/candy-date/candy-date.spec.ts
  components/date-picker/lib/candy-date/candy-date.ts
  components/date-picker/lib/date/date-table.component.html
  components/date-picker/lib/decade/decade-panel.component.ts
  components/date-picker/lib/lib-packer-supplements.spec.ts
  components/date-picker/lib/lib-packer.module.ts
  components/date-picker/lib/month/month-panel.component.html
  components/date-picker/lib/month/month-panel.component.ts
  components/date-picker/lib/month/month-table.component.html
  components/date-picker/lib/popups/date-range-popup.component.ts
  components/date-picker/lib/popups/inner-popup.component.html
  components/date-picker/lib/popups/inner-popup.component.ts
  components/date-picker/lib/util.spec.ts
  components/date-picker/lib/util.ts
  components/date-picker/lib/year/year-panel.component.ts
  components/date-picker/nz-date-picker.component.spec.ts
  components/date-picker/nz-date-picker.component.ts
  components/date-picker/nz-date-picker.module.ts
  components/date-picker/nz-month-picker.component.spec.ts
  components/date-picker/nz-month-picker.component.ts
  components/date-picker/nz-range-picker.component.spec.ts
  components/date-picker/nz-range-picker.component.ts
  components/date-picker/nz-week-picker.component.spec.ts
  components/date-picker/nz-week-picker.component.ts
  components/date-picker/nz-year-picker.component.spec.ts
  components/date-picker/nz-year-picker.component.ts
  components/date-picker/picker.component.ts
  components/date-picker/public-api.ts
  components/date-picker/standard-types.ts
Labels: PR: reviewed-approved

#3857 fix(module:tooltip): fix position change not set back
  components/tooltip/nz-tooltip.component.ts
Labels: PR: reviewed-approved

#3848 fix(schematics): fix parse module name error
  .github/nz-boot.yml
  schematics/utils/build-component.ts
  scripts/schematics/demo2schematics.ts
Labels: PR: reviewed-approved

#3831 fix(module:dropdown): restore escape and hide backdrop when disabled
  components/dropdown/nz-dropdown.directive.spec.ts
  components/dropdown/nz-dropdown.directive.ts
Labels: PR: reviewed-approved

#3709 fix(module:tabs): fix the pagnation padding-right when scrolling (#3539)
  components/core/util/text-measure.ts
  components/tabs/nz-tabs-nav.component.ts
  components/tabs/nz-tabs-nav.spec.ts
  components/tabs/nz-tabs.module.ts
Labels: PR: reviewed-approved

#3814 build(module:*): strip internal-annotated declarations
  components/tsconfig.lib.json
Labels: PR: reviewed-approved

#3880 release(8.1.1): release 8.1.1
  CHANGELOG.md
  components/package.json
  components/version/version.ts
  docs/changelog.en-US.md
  docs/changelog.zh-CN.md
Labels: PR: reviewed-approved

#3879 fix(module:slider): change mark style in horizontal mode
  components/slider/nz-slider-marks.component.ts
Labels: PR: reviewed-approved

#3843 fix(module:tree-select): should not close when the selectable is false
  components/tree-select/doc/index.en-US.md
  components/tree-select/doc/index.zh-CN.md
  components/tree-select/nz-tree-select.component.html
  components/tree-select/nz-tree-select.component.ts
  components/tree-select/nz-tree-select.spec.ts
Labels: PR: reviewed-approved

#3885 release(8.1.2): release 8.1.2
  CHANGELOG.md
  components/package.json
  components/version/version.ts
  docs/changelog.en-US.md
  docs/changelog.zh-CN.md
Labels: PR: reviewed-approved

#3894 style: fix styles error after sync with antd-3.20.7
  components/checkbox/nz-checkbox-group.component.html
  components/radio/demo/module
  components/table/style/patch.less
  components/upload/nz-upload.component.ts
  scripts/site/_site/doc/theme.less
Labels: PR: unreviewed
