Repository NG-ZORRO/ng-zorro-antd, pull requests merged in 2019-06, with the labels that each got.

#3481 fix(module:cascader): fix reset trigger redraw
  components/cascader/nz-cascader.service.ts
Labels: PR: :heavy_check_mark: Merge Ready

#3501 feat(module:carousel): support custom strategies
  components/carousel/doc/index.en-US.md
  components/carousel/doc/index.zh-CN.md
  components/carousel/nz-carousel-definitions.ts
  components/carousel/nz-carousel.component.ts
  components/carousel/nz-carousel.spec.ts
  components/carousel/public-api.ts
  tsconfig.json
Labels: PR: :heavy_check_mark: Merge Ready

#3503 feat(module:button): support link type
  components/button/demo/basic.ts
  components/button/demo/block.ts
  components/button/demo/disabled.ts
  components/button/demo/ghost.ts
  components/button/demo/size.ts
  components/button/doc/index.en-US.md
  components/button/doc/index.zh-CN.md
  components/button/nz-button.component.ts
  components/button/nz-button.spec.ts
  components/button/style/index.less
  components/button/style/mixin.less
  components/core/wave/nz-wave-renderer.ts
  components/core/wave/nz-wave.directive.ts
  components/core/wave/nz-wave.spec.ts
Labels: PR: :heavy_check_mark: Merge Ready

#3516 refactor(module:auto-complete): refactor and fix tests
  components/auto-complete/nz-autocomplete-trigger.directive.ts
Labels: PR: :heavy_check_mark: Merge Ready

#3502 build: fix migration style file path
  scripts/build/migration-styles.js
Labels: PR: :heavy_check_mark: Merge Ready

#3500 fix(module:date-picker): replace DatePipe with formatDate function
  components/i18n/date-helper.service.ts
  components/i18n/nz-i18n.module.ts
Labels: PR: :heavy_check_mark: Merge Ready

#3488 feat(module:drawer): support pressing ESC to close drawer
  components/drawer/nz-drawer.component.ts
  components/drawer/nz-drawer.spec.ts
Labels: PR: :heavy_check_mark: Merge Ready

#3517 feat(module:dropdown): support customize icons
  components/dropdown/doc/index.en-US.md
  components/dropdown/doc/index.zh-CN.md
  components/dropdown/nz-dropdown-button.component.html
  components/dropdown/nz-dropdown-button.component.ts
  components/dropdown/nz-dropdown.module.ts
  components/dropdown/nz-dropdown.spec.ts
Labels: PR::eyes: Need Review

#3442 fix(module:select): display error when in tag and search mode
  components/select/nz-select.service.spec.ts
  components/select/nz-select.service.ts
Labels: PR::eyes: Need Review

#3327 feat(module:descriptions): add component
  components/components.less
  components/core/public-api.ts
  components/core/responsive/break-point.ts
  components/core/responsive/index.ts
  components/core/responsive/public-api.ts
  components/descriptions/demo/basic.md
  components/descriptions/demo/basic.ts
  components/descriptions/demo/border.md
  components/descriptions/demo/border.ts
  components/descriptions/demo/custom-size.md
  components/descriptions/demo/custom-size.ts
  components/descriptions/demo/responsive.md
  components/descriptions/demo/responsive.ts
  components/descriptions/doc/index.en-US.md
  components/descriptions/doc/index.zh-CN.md
  components/descriptions/index.ts
  components/descriptions/nz-descriptions-definitions.ts
  components/descriptions/nz-descriptions-item.component.html
  components/descriptions/nz-descriptions-item.component.ts
  components/descriptions/nz-descriptions.component.html
  components/descriptions/nz-descriptions.component.ts
  components/descriptions/nz-descriptions.module.ts
  components/descriptions/nz-descriptions.spec.ts
  components/descriptions/package.json
  components/descriptions/public-api.ts
  components/descriptions/style/entry.less
  components/descriptions/style/index.less
  components/grid/demo/gutter.ts
  components/grid/nz-grid.spec.ts
  components/grid/nz-row.directive.ts
  components/karma.conf.js
  components/ng-zorro-antd.module.ts
  package.json
  scripts/prerender/static.paths.ts
Labels: :star: New Component, PR: :heavy_check_mark: Merge Ready

#3525 fix(module:layout): fix width type
  components/layout/demo/side.ts
  components/layout/nz-sider.component.html
  components/layout/nz-sider.component.ts
Labels: PR::eyes: Need Review

#3583 feat(module:avatar): add nzSrcSet & nzAlt properites
  components/avatar/avatar.spec.ts
  components/avatar/doc/index.en-US.md
  components/avatar/doc/index.zh-CN.md
  components/avatar/nz-avatar.component.html
  components/avatar/nz-avatar.component.ts
Labels: PR: reviewed-approved

#3588 feat(module:transfer): add nzShowSelectAll & nzRenderList properties
  components/transfer/demo/table-transfer.md
  components/transfer/demo/table-transfer.ts
  components/transfer/demo/tree-transfer.md
  components/transfer/demo/tree-transfer.ts
  components/transfer/doc/index.en-US.md
  components/transfer/doc/index.zh-CN.md
  components/transfer/interface.ts
  components/transfer/nz-transfer-list.component.html
  components/transfer/nz-transfer-list.component.ts
  components/transfer/nz-transfer.component.html
  components/transfer/nz-transfer.component.ts
  components/transfer/transfer.spec.ts
Labels: PR: reviewed-approved

#3624 docs: fix responsive
  scripts/site/_site/doc/app/app.component.ts
Labels: PR: reviewed-approved

#3440 fix(module:select): fix the bug of duplication when keyboard input ch…
  components/select/nz-select-top-control.component.ts
Labels: PR: reviewed-approved, PR::eyes: Need Review

#3575 feat(module:carousel): support dot position
  components/carousel/demo/position.md
  components/carousel/demo/position.ts
  components/carousel/demo/vertical.md
  components/carousel/demo/vertical.ts
  components/carousel/doc/index.en-US.md
  components/carousel/doc/index.zh-CN.md
  components/carousel/nz-carousel-definitions.ts
  components/carousel/nz-carousel.component.html
  components/carousel/nz-carousel.component.ts
  components/carousel/nz-carousel.spec.ts
  components/carousel/strategies/transform-strategy.ts
Labels: PR: reviewed-approved

#3552 chore: replace Chinese comments for English ones
  components/affix/affix.spec.ts
  components/anchor/nz-anchor.component.ts
  components/cascader/nz-cascader.spec.ts
  components/core/scroll/nz-scroll.service.ts
  components/core/tree/nz-tree-base-node.ts
  components/core/tree/nz-tree-base.service.ts
  components/form/style/index.less
  components/i18n/languages/date-picker/et_EE.ts
  components/i18n/languages/date-picker/sk_SK.ts
  components/tree/nz-tree-node.component.ts
  components/upload/demo/custom-request.ts
  components/upload/interface.ts
Labels: PR: reviewed-approved

#3071 feat(module:select): support custom template in select component
  components/select/demo/custom-template.md
  components/select/demo/custom-template.ts
  components/select/doc/index.en-US.md
  components/select/doc/index.zh-CN.md
  components/select/nz-select-top-control.component.html
  components/select/nz-select-top-control.component.ts
  components/select/nz-select.component.html
  components/select/nz-select.component.spec.ts
  components/select/nz-select.component.ts
Labels: PR: unreviewed

#3628 fix(module:dropdown): fix dropdown SSR bug
  components/dropdown/nz-dropdown.directive.ts
  components/dropdown/nz-dropdown.module.ts
Labels: PR: unreviewed

#3627 chore(module:divider): sync style with antd
  components/divider/divider.spec.ts
  components/divider/doc/index.en-US.md
  components/divider/doc/index.zh-CN.md
  components/divider/nz-divider.component.ts
Labels: PR: reviewed-approved

#3633 fix(module:form): fix form overlap
  components/form/nz-form-control.component.ts
Labels: PR: unreviewed

#3634 chore: fix related bugs
  components/collapse/nz-collapse-panel.component.ts
  components/core/animation/collapse.ts
  components/table/nz-table.component.html
  components/table/nz-table.component.ts
  components/table/nz-th.component.html
  components/table/nz-th.component.ts
  components/table/nz-th.spec.ts
  components/table/nz-thead.spec.ts
  components/table/style/patch.less
  components/upload/nz-upload-btn.component.ts
  components/upload/nz-upload.component.ts
Labels: PR: unreviewed

#3636 feat(module:breadcrumb): support dropdown
  components/breadcrumb/demo/dropdown.md
  components/breadcrumb/demo/dropdown.ts
  components/breadcrumb/nz-breadcrumb-item.component.html
  components/breadcrumb/nz-breadcrumb-item.component.ts
  components/breadcrumb/nz-breadcrumb.module.ts
  components/breadcrumb/nz-breadcrumb.spec.ts
Labels: PR: reviewed-approved

#3642 bugfix: nz-mention's doc error
  components/mention/doc/index.en-US.md
  components/mention/doc/index.zh-CN.md
Labels: Component: Mention, PR: reviewed-approved, PR: unreviewed

#3473 fix(module:grid): Make all properties in EmbeddedProperty optional
  components/grid/nz-col.directive.ts
Labels: Component: Grid, PR: reviewed-approved

#3649 chore: add no-selector tslint rule for spec files
  components/alert/nz-alert.spec.ts
  components/breadcrumb/nz-breadcrumb.spec.ts
  components/carousel/nz-carousel.spec.ts
  components/cascader/nz-cascader.spec.ts
  components/checkbox/nz-checkbox.spec.ts
  components/collapse/nz-collapse.spec.ts
  components/descriptions/nz-descriptions.spec.ts
  components/drawer/nz-drawer.spec.ts
  components/dropdown/nz-dropdown.spec.ts
  components/empty/nz-empty.spec.ts
  components/icon/nz-icon.spec.ts
  components/input-number/nz-input-number.spec.ts
  components/input/nz-autosize.spec.ts
  components/input/nz-input-group.spec.ts
  components/input/nz-input.spec.ts
  components/layout/nz-layout.spec.ts
  components/menu/nz-menu.spec.ts
  components/message/nz-message.spec.ts
  components/modal/nz-modal.spec.ts
  components/notification/nz-notification.spec.ts
  components/pagination/nz-pagination.spec.ts
  components/popconfirm/nz-popconfirm.spec.ts
  components/popover/nz-popover.spec.ts
  components/progress/nz-progress.spec.ts
  components/radio/nz-radio.spec.ts
  components/rate/nz-rate.spec.ts
  components/select/nz-select-unselectable.spec.ts
  components/skeleton/nz-skeleton.spec.ts
  components/spin/nz-spin.spec.ts
  components/statistic/nz-countdown.spec.ts
  components/statistic/nz-statistic-number.spec.ts
  components/statistic/nz-statistic.spec.ts
  components/statistic/nz-time-range.spec.ts
  components/steps/nz-steps.spec.ts
  components/switch/nz-switch.spec.ts
  components/table/nz-table.spec.ts
  components/table/nz-tbody.spec.ts
  components/table/nz-td.spec.ts
  components/table/nz-th.spec.ts
  components/table/nz-thead.spec.ts
  components/table/nz-tr.spec.ts
  components/tabs/nz-tabs-nav.spec.ts
  components/tabs/nz-tabs.spec.ts
  components/time-picker/nz-time-picker-panel.component.spec.ts
  components/time-picker/nz-time-picker.component.spec.ts
  components/time-picker/nz-time-value-accessor.directive.spec.ts
  components/timeline/nz-timeline.spec.ts
  components/tooltip/nz-tooltip.spec.ts
  components/tree-select/nz-tree-select.spec.ts
  components/tree/nz-tree.spec.ts
  scripts/tslint-rules/noSelectorRule.ts
  tslint.json
Labels: PR: reviewed-approved

#3651 fix(module:pagination): fix pagination nzTotal 0 bug
  components/i18n/date-helper.service.ts
  components/pagination/nz-pagination.component.html
  components/pagination/nz-pagination.spec.ts
Labels: PR: unreviewed

#3632 fix(module:mention): fix cannot to switch trigger
  components/mention/demo/controlled.ts
  components/mention/doc/index.en-US.md
  components/mention/doc/index.zh-CN.md
  components/mention/nz-mention-trigger.ts
  components/mention/nz-mention.component.ts
  components/mention/nz-mention.service.ts
  components/mention/nz-mention.spec.ts
  components/mention/public-api.ts
Labels: PR: reviewed-approved

#3654 fix(module:card): fix card tab ng-template
  components/card/nz-card-tab.component.ts
  components/progress/demo/segment.ts
  components/steps/demo/customized-progress-dot.ts
  docs/i18n.en-US.md
  docs/i18n.zh-CN.md
  integration/webpack/package.json
  package.json
  scripts/site/_site/doc/app/app.component.html
  scripts/site/_site/doc/app/share/nz-codebox/stack-blitz.ts
  setup-shared-libs.sh
Labels: PR: unreviewed

#3656 docs: update ng-zorro-antd users list
  README-zh_CN.md
  README.md
  components/carousel/doc/index.en-US.md
  components/carousel/doc/index.zh-CN.md
  docs/introduce.en-US.md
  docs/introduce.zh-CN.md
Labels: PR: unreviewed

#3658 docs: add customized theme via custom-webpack builder
  docs/customize-theme.en-US.md
  docs/customize-theme.zh-CN.md
Labels: PR: unreviewed

#3663 fix(module:descriptions): fix warning without logger
  components/descriptions/demo/border.ts
  components/descriptions/nz-descriptions.component.ts
  components/descriptions/nz-descriptions.spec.ts
Labels: PR: reviewed-approved

#3670 chore(module:*): add deprecation noti
  components/icon/nz-icon.service.ts
Labels: PR: unreviewed

#3673 docs: update docs
  components/comment/doc/index.en-US.md
  components/comment/doc/index.zh-CN.md
  components/form/doc/index.en-US.md
  components/form/doc/index.zh-CN.md
Labels: PR: reviewed-approved

#3674 feat(schematics): add template option in `ng-add`
  docs/schematics.en-US.md
  docs/schematics.zh-CN.md
  schematics/collection.json
  schematics/ng-add/index.ts
  schematics/ng-add/schema.json
  schematics/ng-add/schema.ts
  schematics/ng-generate/blank/index.ts
  schematics/ng-generate/blank/schema.json
  schematics/ng-generate/blank/schema.ts
  schematics/ng-generate/side-menu/files/src/app/app-routing.module.ts.template
  schematics/ng-generate/side-menu/files/src/app/app.component.__style__.template
  schematics/ng-generate/side-menu/files/src/app/app.component.html.template
  schematics/ng-generate/side-menu/files/src/app/app.component.ts.template
  schematics/ng-generate/side-menu/files/src/app/icons-provider.module.ts.template
  schematics/ng-generate/side-menu/files/src/app/pages/welcome/welcome.component.__style__.template
  schematics/ng-generate/side-menu/files/src/app/pages/welcome/welcome.component.html.template
  schematics/ng-generate/side-menu/files/src/app/pages/welcome/welcome.component.ts.template
  schematics/ng-generate/side-menu/files/src/app/pages/welcome/welcome.module.ts.template
  schematics/ng-generate/side-menu/index.ts
  schematics/ng-generate/side-menu/schema.json
  schematics/ng-generate/side-menu/schema.ts
  schematics/ng-generate/topnav/files/src/app/app-routing.module.ts.template
  schematics/ng-generate/topnav/files/src/app/app.component.__style__.template
  schematics/ng-generate/topnav/files/src/app/app.component.html.template
  schematics/ng-generate/topnav/files/src/app/app.component.ts.template
  schematics/ng-generate/topnav/files/src/app/pages/welcome/welcome.component.__style__.template
  schematics/ng-generate/topnav/files/src/app/pages/welcome/welcome.component.html.template
  schematics/ng-generate/topnav/files/src/app/pages/welcome/welcome.component.ts.template
  schematics/ng-generate/topnav/files/src/app/pages/welcome/welcome.module.ts.template
  schematics/ng-generate/topnav/index.ts
  schematics/ng-generate/topnav/schema.json
  schematics/ng-generate/topnav/schema.ts
  schematics/tsconfig.json
  schematics/utils/root-module.ts
  scripts/schematics/copy-resources.js
Labels: PR: reviewed-approved

#3671 docs: update 8.0 docs
  README-zh_CN.md
  README.md
  components/icon/doc/index.en-US.md
  components/icon/doc/index.zh-CN.md
  components/menu/nz-submenu.component.ts
  components/package.json
  docs/changelog.en-US.md
  docs/changelog.zh-CN.md
  docs/contributing.en-US.md
  docs/customize-theme.en-US.md
  docs/customize-theme.zh-CN.md
  docs/getting-started.en-US.md
  docs/getting-started.zh-CN.md
  docs/i18n.en-US.md
  docs/i18n.zh-CN.md
  docs/introduce.en-US.md
  docs/introduce.zh-CN.md
  docs/recommendation.en-US.md
  docs/recommendation.zh-CN.md
  scripts/release-helper.sh
  scripts/site/_site/doc/app/app.component.html
  scripts/site/_site/doc/app/app.component.ts
  scripts/site/_site/doc/style/index.less
  scripts/site/_site/doc/style/resource.less
Labels: PR: unreviewed

#3680 release(8.0.0): release 8.0.0
  CHANGELOG.md
  angular.json
  components/package.json
  components/version.ts
  docs/changelog.en-US.md
  docs/changelog.zh-CN.md
  package.json
  scripts/site/_site/doc/app/share/nz-codebox/stack-blitz.ts
  scripts/site/_site/doc/tsconfig.es5.json
  scripts/site/_site/iframe/browserslist
  scripts/site/_site/tsconfig.app.json
  tsconfig-build.json
  tsconfig.json
Labels: PR: unreviewed

#3683 fix(module:breadcrumb): fix warning startWith operators
  components/breadcrumb/nz-breadcrumb.component.ts
Labels: PR: reviewed-approved
