Repository NG-ZORRO/ng-zorro-antd, pull requests merged in 2020-07, with the labels that each got.

#5449 fix(module:tooltip): replace public api with more specific ones
  components/popconfirm/doc/index.en-US.md
  components/popconfirm/doc/index.zh-CN.md
  components/popconfirm/popconfirm.spec.ts
  components/popconfirm/popconfirm.ts
  components/popover/doc/index.en-US.md
  components/popover/doc/index.zh-CN.md
  components/popover/popover.spec.ts
  components/popover/popover.ts
  components/tooltip/base.ts
  components/tooltip/doc/index.en-US.md
  components/tooltip/doc/index.zh-CN.md
  components/tooltip/tooltip.spec.ts
  components/tooltip/tooltip.ts
Labels: PR: reviewed-approved

#5465 fix(module:list): nz-list-item-actions rendered nothing
  components/list/list-item-cell.ts
Labels: PR: reviewed-approved

#5476 fix(module:upload): fix 'uploadError' of undefined
  components/upload/upload.component.html
Labels: PR: unreviewed

#5479 test(module:*): filename typo error, componet change to component
  components/core/testing/component-bed.ts
  components/core/testing/public-api.ts
  components/date-picker/public-api.ts
  components/descriptions/descriptions.spec.ts
  components/empty/empty.spec.ts
  components/icon/icon.spec.ts
  components/message/message.spec.ts
  components/notification/notification.spec.ts
  components/popconfirm/popconfirm.spec.ts
  components/popover/popover.spec.ts
  components/result/result.spec.ts
  components/slider/slider.spec.ts
  components/timeline/timeline.spec.ts
  components/tooltip/tooltip.spec.ts
  components/tree/tree.spec.ts
Labels: PR: partially-approved

#5494 refactor(module:*): migrate the source code to Angular v10
  angular.json
  components/affix/affix.module.ts
  components/anchor/anchor.module.ts
  components/back-top/back-top.module.ts
  components/core/services/scroll.ts
  components/date-picker/lib/abstract-panel-header.ts
  components/date-picker/lib/abstract-table.ts
  components/timeline/timeline.service.ts
  components/tooltip/base.ts
Labels: PR: partially-approved

#5515 fix(module:i18n): export missing languages from public-api
  components/i18n/public-api.ts
Labels: PR: reviewed-approved

#5478 feat(module:timeline): support custom position
  components/timeline/demo/position.md
  components/timeline/demo/position.ts
  components/timeline/doc/index.en-US.md
  components/timeline/doc/index.zh-CN.md
  components/timeline/public-api.ts
  components/timeline/timeline-item.component.ts
  components/timeline/timeline.component.ts
  components/timeline/timeline.spec.ts
  components/timeline/typings.ts
Labels: PR: reviewed-approved

#5512 feat(module:tooltip): add more specific api (#5449)
  components/popconfirm/doc/index.en-US.md
  components/popconfirm/doc/index.zh-CN.md
  components/popconfirm/popconfirm.ts
  components/popover/demo/control.md
  components/popover/demo/control.ts
  components/popover/doc/index.en-US.md
  components/popover/doc/index.zh-CN.md
  components/popover/popover.ts
  components/tooltip/base.ts
  components/tooltip/doc/index.en-US.md
  components/tooltip/doc/index.zh-CN.md
  components/tooltip/tooltip.spec.ts
  components/tooltip/tooltip.ts
Labels: PR: reviewed-approved

#5488 feat(module:datapicker): add `[nzInputReadOnly]`
  components/date-picker/date-picker.component.spec.ts
  components/date-picker/date-picker.component.ts
  components/date-picker/doc/index.en-US.md
  components/date-picker/doc/index.zh-CN.md
  components/date-picker/picker.component.ts
Labels: PR: reviewed-approved

#5533 fix(module:table): fix table no data colSpan
  components/table/doc/index.en-US.md
  components/table/doc/index.zh-CN.md
  components/table/src/cell/cell-fixed.directive.ts
  components/table/src/cell/th-measure.directive.ts
  components/table/src/table-style.service.ts
  components/table/src/table/thead.component.ts
  components/table/src/table/tr.directive.ts
Labels: PR: unreviewed

#5535 fix(module:table): fix table filter false or 0 error
  components/table/src/addon/filter.component.ts
Labels: PR: unreviewed

#5536 fix(module:select): fix select scroll render buffer
  components/select/option-container.component.ts
Labels: PR: unreviewed

#5529 fix(module:date-picker): nzDateRender render incorrectly
  components/date-picker/inner-popup.component.ts
Labels: PR: reviewed-approved

#5483 feat(module:popconfirm): add `nzPopconfirmShowArrow` property
  components/popconfirm/demo/hide-arrow.md
  components/popconfirm/demo/hide-arrow.ts
  components/popconfirm/doc/index.en-US.md
  components/popconfirm/doc/index.zh-CN.md
  components/popconfirm/popconfirm.spec.ts
  components/popconfirm/popconfirm.ts
Labels: PR: unreviewed

#5537 fix(module:core): fix empty check
  components/core/config/config.service.ts
Labels: PR: partially-approved

#5525 feat(module:upload): add `nzPreviewIsImage` property
  components/upload/doc/index.en-US.md
  components/upload/doc/index.zh-CN.md
  components/upload/upload-list.component.ts
  components/upload/upload.component.html
  components/upload/upload.component.ts
  components/upload/upload.spec.ts
Labels: PR: reviewed-approved

#5498 feat(module:drawer): support get component instance for content
  components/drawer/doc/index.en-US.md
  components/drawer/doc/index.zh-CN.md
  components/drawer/drawer-ref.ts
  components/drawer/drawer.component.ts
  components/drawer/drawer.service.ts
  components/drawer/drawer.spec.ts
Labels: PR: partially-approved

#5475 feat(module:resizable): add `nzDisabled` property
  components/resizable/demo/basic.ts
  components/resizable/doc/index.en-US.md
  components/resizable/doc/index.zh-CN.md
  components/resizable/resizable.directive.ts
  components/resizable/resizable.spec.ts
  components/resizable/style/index.less
Labels: PR: partially-approved

#5539 chore(release): release 9.3.0
  CHANGELOG.md
  components/package.json
  components/version/version.ts
  docs/changelog.en-US.md
  docs/changelog.zh-CN.md
Labels: PR: reviewed-approved

#5545 feat(module:breadcrumb): add `nzRouteLabelFn` property
  components/breadcrumb/breadcrumb.component.ts
  components/breadcrumb/breadcrumb.spec.ts
  components/breadcrumb/doc/index.en-US.md
  components/breadcrumb/doc/index.zh-CN.md
Labels: PR: reviewed-approved

#5548 style(module:tabs): types filename error
  components/tabs/public-api.ts
  components/tabs/tabs-ink-bar.directive.ts
  components/tabs/tabs-nav.component.ts
  components/tabs/tabs-nav.spec.ts
  components/tabs/tabs.spec.ts
  components/tabs/tabs.types.ts
  components/tabs/tabset.component.ts
Labels: PR: partially-approved

#5542 fix(module:tooltip,*): enable cdk push
  components/popconfirm/popconfirm.ts
  components/popover/popover.ts
  components/tooltip/tooltip.ts
Labels: PR: reviewed-approved

#5551 feat(module: modal): support params and modelRef when footer is template
  components/modal/demo/service.md
  components/modal/demo/service.ts
  components/modal/modal-footer.component.ts
Labels: PR: reviewed-approved

#5507 fix(module: tree): fix nzBlockNode not work
  components/tree/tree.component.ts
  components/tree/tree.spec.ts
Labels: PR: reviewed-approved

#5559 style: update .prettierrc
  .prettierrc
Labels: PR: unreviewed

#5553 feat(module:drawer): add `nzFooter` property
  components/drawer/demo/from-drawer.ts
  components/drawer/demo/service.ts
  components/drawer/doc/index.en-US.md
  components/drawer/doc/index.zh-CN.md
  components/drawer/drawer-options.ts
  components/drawer/drawer.component.ts
  components/drawer/drawer.spec.ts
Labels: PR: merge-ready, PR: reviewed-approved

#5571 chore: bump @angular/* from 9 to 10
  angular.json
  components/carousel/carousel.component.ts
  components/code-editor/code-editor.service.ts
  components/core/config/config.service.ts
  components/core/util/convert.ts
  components/core/wave/nz-wave-renderer.ts
  components/core/wave/nz-wave.directive.ts
  components/date-picker/date-picker.component.spec.ts
  components/empty/embed-empty.component.ts
  components/empty/empty.spec.ts
  components/i18n/date-helper.service.ts
  components/icon/icon.module.ts
  components/icon/icon.spec.ts
  components/icon/testing/nz-icon-test.module.ts
  components/message/base.ts
  components/message/message.spec.ts
  components/modal/modal-confirm-container.component.ts
  components/modal/modal-container.component.ts
  components/modal/modal-container.ts
  components/modal/modal-ref.ts
  components/modal/modal.service.ts
  components/notification/notification.spec.ts
  components/package.json
  package.json
  schematics/ng-add/setup-project/register-locale.ts
  schematics/ng-update/test-cases/v9/deprecated-class-dropdown.spec.ts
  schematics/ng-update/test-cases/v9/deprecated-component-dropdown.spec.ts
  schematics/ng-update/test-cases/v9/deprecated-component-form.spec.ts
  schematics/ng-update/test-cases/v9/deprecated-component-tooltip-like.spec.ts
  schematics/ng-update/test-cases/v9/deprecated-injection-tokens.spec.ts
  schematics/ng-update/test-cases/v9/deprecated-inputs-carousel.spec.ts
  schematics/ng-update/test-cases/v9/input-names-calendar.spec.ts
  schematics/ng-update/test-cases/v9/input-names-icon.spec.ts
  schematics/ng-update/test-cases/v9/secondary-entry-points.spec.ts
  schematics/utils/root-module.ts
  tslint.json
Labels: PR: partially-approved

#5596 fix(module:modal): change back to FocusTrapFactory
  components/drawer/drawer.component.ts
  components/modal/modal-confirm-container.component.ts
  components/modal/modal-container.component.ts
  components/modal/modal-container.ts
Labels: PR: reviewed-approved

#5606 chore: remove primary entry points
  azure-pipelines.yml
  components/core/resize-observers/package.json
  components/date-picker/package.json
  components/icon/package.json
  components/modal/modal.spec.ts
  components/ng-package.json
  components/ng-zorro-antd.module.ts
  components/public_api.ts
  components/tsconfig.json
  components/tsconfig.lib.json
  tsconfig-build.json
Labels: PR: unreviewed

#5612 test(module:tabs): add test cases
  components/tabs/doc/index.en-US.md
  components/tabs/doc/index.zh-CN.md
  components/tabs/tab-add-button.component.ts
  components/tabs/tab-nav-bar.component.ts
  components/tabs/tab-nav-item.directive.ts
  components/tabs/tab-nav-operation.component.ts
  components/tabs/tab.component.ts
  components/tabs/tabset.component.spec.ts
  components/tabs/tabset.component.ts
Labels: PR: unreviewed
