Repository NG-ZORRO/ng-zorro-antd, pull requests merged in 2020-03, with the labels that each got.

#4663 refactor(module:badge): refactor and aync Ant Design 4
  components/badge/badge.component.ts
  components/badge/badge.module.ts
  components/badge/badge.spec.ts
  components/badge/nz-badge.component.html
  components/badge/public-api.ts
Labels: PR: unreviewed

#4728 refactor(module:drawer): refactor
  components/drawer/drawer-options.ts
  components/drawer/drawer-ref.ts
  components/drawer/drawer.component.ts
  components/drawer/drawer.module.ts
  components/drawer/drawer.service.module.ts
  components/drawer/drawer.service.ts
  components/drawer/drawer.spec.ts
  components/drawer/nz-drawer.component.html
  components/drawer/public-api.ts
Labels: PR: unreviewed

#4664 refactor(module:comment): refactor and aync Ant Design 4
  components/comment/comment-cells.ts
  components/comment/comment.component.ts
  components/comment/comment.module.ts
  components/comment/comment.spec.ts
  components/comment/demo/basic.ts
  components/comment/nz-comment.component.html
  components/comment/nz-comment.component.ts
  components/comment/public-api.ts
Labels: PR: unreviewed

#4662 refactor(module:avatar): refactor and aync Ant Design 4
  components/avatar/avatar.component.ts
  components/avatar/avatar.module.ts
  components/avatar/avatar.spec.ts
  components/avatar/nz-avatar.component.html
  components/avatar/public-api.ts
Labels: PR: unreviewed

#4755 refactor(module:mention): refactor
  components/mention/mention-suggestions.ts
  components/mention/mention-trigger.ts
  components/mention/mention.component.ts
  components/mention/mention.module.ts
  components/mention/mention.service.ts
  components/mention/nz-mention.component.html
  components/mention/nz-mention.spec.ts
  components/mention/public-api.ts
Labels: PR: unreviewed

#4826 refactor(module:calendar): sync to antd 4.0
  components/calendar/calendar-cells.ts
  components/calendar/calendar-header.component.ts
  components/calendar/calendar-header.spec.ts
  components/calendar/calendar.component.ts
  components/calendar/calendar.module.ts
  components/calendar/calendar.spec.ts
  components/calendar/nz-calendar-header.component.html
  components/calendar/nz-calendar.component.html
  components/calendar/public-api.ts
Labels: PR: reviewed-approved

#4661 refactor(module:autocomplete): refactor and sync Ant Design 4
  components/auto-complete/autocomplete-optgroup.component.ts
  components/auto-complete/autocomplete-option.component.ts
  components/auto-complete/autocomplete-trigger.directive.ts
  components/auto-complete/autocomplete.component.ts
  components/auto-complete/autocomplete.module.ts
  components/auto-complete/autocomplete.spec.ts
  components/auto-complete/nz-autocomplete-optgroup.component.html
  components/auto-complete/nz-autocomplete-option.component.html
  components/auto-complete/nz-autocomplete.component.html
  components/auto-complete/public-api.ts
Labels: PR: reviewed-approved

#4853 chore: add .gitattributes file
  .gitattributes
Labels: PR: reviewed-approved

#4841 docs: support dark theme
  components/dark-theme.js
  components/drawer/demo/from-drawer.ts
  components/drawer/demo/multi-level-drawer.ts
  components/page-header/demo/actions.ts
  components/page-header/demo/basic.ts
  components/page-header/demo/breadcrumb.ts
  components/page-header/demo/content.ts
  components/page-header/demo/ghost.ts
  components/page-header/demo/responsive.ts
  docs/customize-theme.en-US.md
  docs/customize-theme.zh-CN.md
  package.json
  scripts/build/compile-styles.ts
  scripts/gulp/tasks/library.ts
  scripts/gulp/tasks/site.ts
  scripts/site/_site/doc/app/app.component.html
  scripts/site/_site/doc/app/app.component.ts
  scripts/site/_site/doc/app/app.module.ts
  scripts/site/_site/doc/app/app.service.ts
  scripts/site/_site/doc/app/header/github-button.component.less
  scripts/site/_site/doc/app/header/github-button.component.ts
  scripts/site/_site/doc/app/header/header.component.less
  scripts/site/_site/doc/app/header/header.component.ts
  scripts/site/_site/doc/app/header/header.less
  scripts/site/_site/doc/app/header/logo.component.less
  scripts/site/_site/doc/app/header/logo.component.ts
  scripts/site/_site/doc/app/header/navigation.component.less
  scripts/site/_site/doc/app/header/navigation.component.ts
  scripts/site/_site/doc/app/header/searchbar.component.less
  scripts/site/_site/doc/app/header/searchbar.component.ts
  scripts/site/_site/doc/app/share/fixed-widgets/fixed-widgets.component.ts
  scripts/site/_site/doc/app/share/fixed-widgets/fixed-widgets.module.ts
  scripts/site/_site/doc/app/share/fixed-widgets/theme-icons.ts
  scripts/site/_site/doc/app/share/nz-codebox/nz-codebox.component.html
  scripts/site/_site/doc/app/share/nz-codebox/nz-codebox.component.ts
  scripts/site/_site/doc/assets/doc-search.min.css
  scripts/site/_site/doc/assets/img/GitHub-Mark-Light-64px.png
  scripts/site/_site/doc/index.html
  scripts/site/_site/doc/style/index.less
  scripts/site/_site/doc/style/patch.less
  scripts/site/_site/doc/styles.less
  scripts/site/_site/doc/theme.less
  scripts/site/generate-theme.js
Labels: PR: reviewed-approved

#4847 docs: fix dark mode cascader
  components/cascader/cascader.component.ts
  components/cascader/demo/basic.ts
  components/cascader/demo/change-on-function.ts
  components/cascader/demo/change-on-select.ts
  components/cascader/demo/custom-field-names.ts
  components/cascader/demo/custom-render.ts
  components/cascader/demo/custom-template.ts
  components/cascader/demo/default-value-and-asyn-options.ts
  components/cascader/demo/default-value-and-lazyload.ts
  components/cascader/demo/default-value.ts
  components/cascader/demo/disabled.ts
  components/cascader/demo/hover.ts
  components/cascader/demo/lazy.ts
  components/cascader/demo/modal.ts
  components/cascader/demo/reactive-form.ts
  components/cascader/demo/search.ts
  components/cascader/demo/trigger-action.ts
  components/cascader/demo/trigger.ts
Labels: PR: reviewed-approved

#4813 refactor(module:tree-select): refactor
  components/tree-select/demo/customized-icon.ts
  components/tree-select/nz-tree-select.component.html
  components/tree-select/public-api.ts
  components/tree-select/tree-select.component.ts
  components/tree-select/tree-select.module.ts
  components/tree-select/tree-select.service.ts
  components/tree-select/tree-select.spec.ts
Labels: PR: reviewed-approved

#4843 feat(module:date-picker): add some inputs
  components/date-picker/abstract-picker.component.html
  components/date-picker/abstract-picker.component.ts
  components/date-picker/date-picker.component.spec.ts
  components/date-picker/date-picker.service.ts
  components/date-picker/date-range-popup.component.ts
  components/date-picker/doc/index.en-US.md
  components/date-picker/doc/index.zh-CN.md
  components/date-picker/lib/abstract-table.ts
  components/date-picker/lib/year-table.component.ts
  components/date-picker/month-picker.component.spec.ts
  components/date-picker/picker.component.ts
  components/date-picker/range-picker.component.spec.ts
  components/date-picker/year-picker.component.spec.ts
Labels: PR: reviewed-approved

#4859 feat(module:skeleton): add nz-skeleton-element
  components/skeleton/demo/element.md
  components/skeleton/demo/element.ts
  components/skeleton/demo/module
  components/skeleton/doc/index.en-US.md
  components/skeleton/doc/index.zh-CN.md
  components/skeleton/nz-skeleton.component.html
  components/skeleton/nz-skeleton.module.ts
  components/skeleton/public-api.ts
  components/skeleton/skeleton-element.component.ts
  components/skeleton/skeleton.component.ts
  components/skeleton/skeleton.module.ts
  components/skeleton/skeleton.spec.ts
  components/skeleton/skeleton.type.ts
  scripts/site/_site/doc/style/patch.less
Labels: PR: unreviewed

#4712 refactor(module:page-header): refactor and sync Ant Design 4
  components/page-header/demo/actions.ts
  components/page-header/demo/breadcrumb.ts
  components/page-header/demo/content.ts
  components/page-header/demo/ghost.ts
  components/page-header/demo/responsive.ts
  components/page-header/doc/index.en-US.md
  components/page-header/doc/index.zh-CN.md
  components/page-header/nz-page-header.component.html
  components/page-header/nz-page-header.component.less
  components/page-header/page-header-cells.ts
  components/page-header/page-header.component.ts
  components/page-header/page-header.module.ts
  components/page-header/page-header.spec.ts
  components/page-header/public-api.ts
Labels: PR: reviewed-approved

#4670 fix(module:transfer): fix transfer nzTargetKeys property
  components/transfer/demo/table-transfer.ts
  components/transfer/nz-transfer.component.ts
  components/transfer/transfer.spec.ts
Labels: Component: Transfer, PR: unreviewed

#4878 refactor(module:back-top): refactor
  components/back-top/back-top.component.ts
  components/back-top/back-top.module.ts
  components/back-top/back-top.spec.ts
  components/back-top/nz-back-top.component.html
  components/back-top/public-api.ts
Labels: PR: reviewed-approved

#4730 chore(module:slider): refactor
  components/slider/handle.component.ts
  components/slider/marks.component.ts
  components/slider/nz-slider-definitions.ts
  components/slider/nz-slider-handle.component.html
  components/slider/nz-slider-marks.component.html
  components/slider/nz-slider-marks.component.ts
  components/slider/nz-slider-step.component.html
  components/slider/nz-slider-track.component.html
  components/slider/nz-slider.component.html
  components/slider/public-api.ts
  components/slider/slider.component.ts
  components/slider/slider.module.ts
  components/slider/slider.service.ts
  components/slider/slider.spec.ts
  components/slider/step.component.ts
  components/slider/track.component.ts
  components/slider/typings.ts
Labels: PR: unreviewed

#4723 chore(module:message,notification): refactor
  angular.json
  components/core/config/config.ts
  components/message/base.service.ts
  components/message/message-container.component.ts
  components/message/message.component.ts
  components/message/message.module.ts
  components/message/message.service.module.ts
  components/message/message.service.ts
  components/message/message.spec.ts
  components/message/nz-message-container.component.html
  components/message/nz-message.component.html
  components/message/nz-message.component.ts
  components/message/public-api.ts
  components/message/typings.ts
  components/notification/demo/module
  components/notification/demo/placement.md
  components/notification/demo/placement.ts
  components/notification/notification-container.component.ts
  components/notification/notification.component.ts
  components/notification/notification.module.ts
  components/notification/notification.service.module.ts
  components/notification/notification.service.ts
  components/notification/notification.spec.ts
  components/notification/nz-notification-config.ts
  components/notification/nz-notification-container.component.html
  components/notification/nz-notification.component.html
  components/notification/nz-notification.component.ts
  components/notification/public-api.ts
  components/notification/typings.ts
Labels: PR: unreviewed

#4869 refactor(module: tree): refactor
  components/core/tree/nz-tree-base-node.ts
  components/core/tree/nz-tree-base-util.ts
  components/core/tree/nz-tree-base.service.ts
  components/core/tree/public-api.ts
  components/tree-select/tree-select.component.ts
  components/tree-select/tree-select.spec.ts
  components/tree/demo/basic.ts
  components/tree/demo/customized-icon.ts
  components/tree/demo/directory.ts
  components/tree/demo/search.ts
  components/tree/doc/index.en-US.md
  components/tree/doc/index.zh-CN.md
  components/tree/nz-tree-indent.component.ts
  components/tree/nz-tree-node.component.html
  components/tree/nz-tree-node.component.ts
  components/tree/nz-tree.component.html
  components/tree/nz-tree.component.ts
  components/tree/nz-tree.module.ts
  components/tree/nz-tree.service.ts
  components/tree/nz-tree.spec.ts
  components/tree/public-api.ts
  components/tree/style/patch.less
Labels: PR: unreviewed

#4825 refactor(module:time-picker): sync to antd 4.0
  components/time-picker/nz-time-picker-panel.component.html
  components/time-picker/nz-time-picker.component.html
  components/time-picker/public-api.ts
  components/time-picker/time-picker-panel.component.spec.ts
  components/time-picker/time-picker-panel.component.ts
  components/time-picker/time-picker.component.spec.ts
  components/time-picker/time-picker.component.ts
  components/time-picker/time-picker.module.ts
  components/time-picker/time-value-accessor.directive.spec.ts
  components/time-picker/time-value-accessor.directive.ts
Labels: PR: unreviewed

#4881 refactor(module:list): refactor
  components/list/demo/basic.ts
  components/list/demo/grid.ts
  components/list/demo/infinite-load.ts
  components/list/demo/loadmore.ts
  components/list/demo/module
  components/list/demo/resposive.ts
  components/list/demo/simple.ts
  components/list/demo/vertical.ts
  components/list/doc/index.en-US.md
  components/list/doc/index.zh-CN.md
  components/list/list-cell.ts
  components/list/list-item-cell.ts
  components/list/list-item-meta-cell.ts
  components/list/list-item-meta.component.ts
  components/list/list-item.component.ts
  components/list/list.component.ts
  components/list/list.module.ts
  components/list/list.spec.ts
  components/list/nz-list-item-meta.component.html
  components/list/nz-list-item-meta.component.ts
  components/list/nz-list-item.component.html
  components/list/nz-list-item.component.ts
  components/list/nz-list.component.html
  components/list/nz-list.component.ts
  components/list/nz-list.module.ts
  components/list/public-api.ts
  components/style/patch.less
Labels: PR: unreviewed

#4880 fix(module:breadcrumb): fix breadcrumb link style
  components/breadcrumb/style/patch.less
Labels: PR: unreviewed

#4711 feat(module:icon): support add icon in feat modules & refactor
  components/core/testing/componet-bed.ts
  components/icon/doc/index.en-US.md
  components/icon/doc/index.zh-CN.md
  components/icon/icon.directive.ts
  components/icon/icon.module.ts
  components/icon/icon.service.ts
  components/icon/icon.spec.ts
  components/icon/icons.ts
  components/icon/nz-icon.module.ts
  components/icon/public-api.ts
  components/icon/testing/nz-icon-test.module.ts
  scripts/site/_site/doc/app/app.module.ts
Labels: PR: reviewed-approved

#4877 refactor(module:anchor): refactor
  components/anchor/anchor-link.component.ts
  components/anchor/anchor.component.ts
  components/anchor/anchor.module.ts
  components/anchor/anchor.spec.ts
  components/anchor/doc/index.en-US.md
  components/anchor/doc/index.zh-CN.md
  components/anchor/nz-anchor-link.component.html
  components/anchor/nz-anchor.component.html
  components/anchor/public-api.ts
  components/anchor/util.ts
  components/back-top/back-top.component.ts
  scripts/site/utils/generate-demo.js
  scripts/site/utils/generate-docs.js
Labels: PR: unreviewed

#4833 feat(module:date-picker): support parse input value
  components/comment/demo/basic.ts
  components/comment/demo/editor.ts
  components/comment/demo/list.ts
  components/core/time/candy-date.ts
  components/date-picker/abstract-picker.component.ts
  components/date-picker/calendar-footer.component.ts
  components/date-picker/date-picker.component.spec.ts
  components/date-picker/demo/basic.ts
  components/date-picker/demo/disabled-date.ts
  components/date-picker/demo/presetted-ranges.ts
  components/date-picker/lib/abstract-panel-header.html
  components/date-picker/lib/abstract-panel-header.ts
  components/date-picker/lib/date-header.component.ts
  components/date-picker/lib/date-table.component.ts
  components/date-picker/lib/decade-header.component.ts
  components/date-picker/lib/month-header.component.ts
  components/date-picker/lib/util.ts
  components/date-picker/month-picker.component.spec.ts
  components/date-picker/picker.component.ts
  components/date-picker/range-picker.component.spec.ts
  components/i18n/convert-tokens.ts
  components/i18n/date-config.ts
  components/i18n/date-helper.service.spec.ts
  components/i18n/date-helper.service.ts
  components/i18n/nz-i18n.interface.ts
  components/package.json
  docs/i18n.en-US.md
  docs/i18n.zh-CN.md
  package.json
  scripts/site/_site/doc/app/share/nz-codebox/stack-blitz.ts
Labels: PR: reviewed-approved

#4884 fix(module:message): fix message and notification error in prod
  README-zh_CN.md
  README.md
  components/drawer/demo/service.md
  components/drawer/demo/service.ts
  components/drawer/drawer.module.ts
  components/drawer/drawer.spec.ts
  components/empty/empty.spec.ts
  components/icon/doc/index.en-US.md
  components/icon/doc/index.zh-CN.md
  components/input/demo/allow-clear.ts
  components/message/base.service.ts
  components/message/message.module.ts
  components/message/message.service.ts
  components/message/message.spec.ts
  components/message/public-api.ts
  components/modal/demo/footer2.ts
  components/modal/demo/service.md
  components/modal/demo/service.ts
  components/modal/modal.spec.ts
  components/notification/notification-container.component.ts
  components/notification/notification.component.ts
  components/notification/notification.module.ts
  components/notification/notification.service.ts
  components/notification/notification.spec.ts
  components/notification/typings.ts
  components/popconfirm/doc/index.en-US.md
  components/popconfirm/doc/index.zh-CN.md
  components/popconfirm/popconfirm.module.ts
  components/popover/doc/index.en-US.md
  components/popover/doc/index.zh-CN.md
  components/popover/popover.module.ts
  components/tabs/demo/lazy.ts
  components/tooltip/doc/index.en-US.md
  components/tooltip/doc/index.zh-CN.md
  components/tooltip/tooltip.module.ts
  docs/getting-started.en-US.md
  docs/getting-started.zh-CN.md
  docs/global-config.en-US.md
  docs/global-config.zh-CN.md
  docs/introduce.en-US.md
  docs/introduce.zh-CN.md
  docs/recommendation.en-US.md
  docs/recommendation.zh-CN.md
  package.json
  scripts/site/_site/doc/app/share/nz-codebox/stack-blitz.ts
  scripts/site/template/demo-module.template.ts
  scripts/site/utils/generate-demo.js
Labels: PR: unreviewed

#4892 docs: fix assets paths for the site
  scripts/site/_site/doc/app/app.component.ts
  scripts/site/_site/doc/app/footer/footer.component.ts
  scripts/site/_site/doc/app/header/github-button.component.ts
  scripts/site/_site/doc/app/header/header.component.ts
  scripts/site/_site/doc/app/header/navigation.component.ts
  scripts/site/_site/doc/app/header/searchbar.component.ts
  scripts/site/_site/doc/assets/img/GitHub-Mark-Light-64px.png
  scripts/site/_site/doc/index.html
  scripts/site/_site/doc/style/patch.less
Labels: PR: unreviewed

#4889 chore(release): release 9.0.0-beta.1
  CHANGELOG.md
  components/message/message-container.component.ts
  components/message/message.component.ts
  components/message/message.module.ts
  components/notification/notification-container.component.ts
  components/notification/notification.component.ts
  components/notification/notification.module.ts
  components/package.json
  components/tabs/nz-tab-body.component.html
  components/tabs/nz-tab.component.html
  components/tabs/nz-tabs-nav.component.html
  components/tabs/nz-tabset.component.html
  components/tabs/public-api.ts
  components/tabs/style/patch.less
  components/tabs/tab-body.component.ts
  components/tabs/tab-label.directive.ts
  components/tabs/tab-link.directive.ts
  components/tabs/tab.component.ts
  components/tabs/tab.directive.ts
  components/tabs/table.types.ts
  components/tabs/tabs-ink-bar.directive.ts
  components/tabs/tabs-nav.component.ts
  components/tabs/tabs-nav.spec.ts
  components/tabs/tabs.module.ts
  components/tabs/tabs.spec.ts
  components/tabs/tabset.component.ts
  components/tsconfig.lib.json
  components/version/version.ts
  docs/changelog.en-US.md
  docs/changelog.zh-CN.md
  docs/i18n.en-US.md
  docs/i18n.zh-CN.md
  scripts/gulp/tasks/library.ts
  scripts/site/_site/doc/theme.less
Labels: PR: unreviewed

#4893 chore: use `NzSafeAny` to replace `any` type
  components/affix/affix.component.ts
  components/anchor/anchor-link.component.ts
  components/anchor/anchor.component.ts
  components/auto-complete/autocomplete-option.component.ts
  components/auto-complete/autocomplete.component.ts
  components/back-top/back-top.component.ts
  components/cascader/typings.ts
  components/core/config/config.service.ts
  components/core/config/config.ts
  components/core/logger/logger.ts
  components/core/polyfill/request-animation.ts
  components/core/scroll/nz-scroll.service.ts
  components/core/services/nz-copy-to-clipboard.service.ts
  components/core/services/nz-singleton.service.ts
  components/core/testing/event-objects.ts
  components/core/time/candy-date.ts
  components/core/tree/nz-tree-base-node.ts
  components/core/tree/nz-tree-base-util.ts
  components/core/tree/nz-tree-base.service.ts
  components/core/tree/nz-tree-base.ts
  components/core/types/common-wrap.ts
  components/core/types/compare-with.ts
  components/core/types/indexable.ts
  components/core/types/ng-class.ts
  components/core/util/check.ts
  components/core/util/convert.ts
  components/core/util/is-promise.ts
  components/core/util/scroll-into-view-if-needed.ts
  components/core/util/text-measure.ts
  components/core/util/textarea-caret-position.ts
  components/drawer/drawer-options.ts
Labels: PR: reviewed-approved

#4897 build: fix ngcc build
  components/date-picker/demo/date-render.md
  components/date-picker/demo/disabled-date.md
  components/date-picker/demo/disabled.md
  components/date-picker/demo/extra-footer.md
  components/date-picker/demo/format.md
  components/date-picker/demo/mode.md
  components/date-picker/demo/presetted-ranges.md
  components/date-picker/demo/size.md
  components/date-picker/demo/start-end.md
  components/date-picker/demo/time.md
  components/i18n/public-api.ts
  components/menu/menu-group.component.ts
  components/menu/menu.directive.ts
  components/modal/public-api.ts
  components/select/public-api.ts
  components/table/public-api.ts
  components/tsconfig.lib.json
Labels: PR: unreviewed

#4898 refactor(module:date-picker): use directive instead of extends class
  components/date-picker/abstract-picker.component.ts
  components/date-picker/calendar-footer.component.ts
  components/date-picker/date-picker.component.html
  components/date-picker/date-picker.component.spec.ts
  components/date-picker/date-picker.component.ts
  components/date-picker/date-range-popup.component.ts
  components/date-picker/inner-popup.component.ts
  components/date-picker/lib/abstract-panel-header.ts
  components/date-picker/lib/public-api.ts
  components/date-picker/lib/util.ts
  components/date-picker/month-picker.component.spec.ts
  components/date-picker/month-picker.component.ts
  components/date-picker/name.ts
  components/date-picker/picker.component.ts
  components/date-picker/public-api.ts
  components/date-picker/range-picker.component.spec.ts
  components/date-picker/range-picker.component.ts
  components/date-picker/testing/util.ts
  components/date-picker/util.spec.ts
  components/date-picker/util.ts
  components/date-picker/week-picker.component.ts
  components/date-picker/year-picker.component.spec.ts
  components/date-picker/year-picker.component.ts
Labels: PR: unreviewed

#4906 fix(module:grid): fix grid responsive bug
  components/grid/demo/gutter.ts
  components/grid/demo/module
  components/grid/demo/playground.ts
  components/grid/row.directive.ts
  components/typography/text-copy.component.ts
  components/typography/text-edit.component.ts
Labels: PR: unreviewed

#4907 fix(module:select): fix select empty status
  components/empty/demo/config.ts
  components/select/option-container.component.ts
  components/select/select.component.ts
Labels: PR: unreviewed

#4891 feat(module:form): reactive form support warning status
  components/form/demo/validate-reactive.md
  components/form/form-control.component.ts
  components/form/form-control.spec.ts
Labels: PR: unreviewed

#4909 chore(release): release 9.0.0-beta.2
  CHANGELOG.md
  components/package.json
  components/version/version.ts
  docs/changelog.en-US.md
  docs/changelog.zh-CN.md
Labels: PR: unreviewed

#4911 docs(module:date-picker): 2 missing placeholders in democode
  components/date-picker/demo/disabled-date.ts
  components/date-picker/demo/format.ts
Labels: PR: unreviewed

#4922 fix(module:table): fix nzTotal in frontend pagination false
  components/table/src/table-data.service.ts
Labels: PR: unreviewed

#4924 fix(module:empty): fix empty image style in dark mode
  components/empty/demo/customize.ts
  components/empty/partial/default.ts
  components/empty/partial/simple.ts
  components/empty/style/index.less
Labels: PR: unreviewed

#4856 refactor: add breakpoint service
  components/affix/affix.component.ts
  components/affix/affix.module.ts
  components/affix/affix.spec.ts
  components/anchor/anchor.component.ts
  components/anchor/anchor.module.ts
  components/anchor/anchor.spec.ts
  components/back-top/back-top.component.ts
  components/back-top/back-top.module.ts
  components/back-top/back-top.spec.ts
  components/carousel/carousel.component.ts
  components/core/config/config.ts
  components/core/responsive/index.ts
  components/core/responsive/nz-breakpoint.ts
  components/core/responsive/package.json
  components/core/responsive/public-api.ts
  components/core/scroll/index.ts
  components/core/scroll/package.json
  components/core/scroll/public-api.ts
  components/core/services/breakpoint.ts
  components/core/services/drag.spec.ts
  components/core/services/drag.ts
  components/core/services/drag/index.ts
  components/core/services/drag/public-api.ts
  components/core/services/nz-copy-to-clipboard.service.module.ts
  components/core/services/nz-copy-to-clipboard.service.ts
  components/core/services/nz-dom-event.service.ts
  components/core/services/public-api.ts
  components/core/services/resize.ts
  components/core/services/scroll.spec.ts
  components/core/services/scroll.ts
  components/core/services/singleton.ts
  components/core/services/update-host-class.ts
  components/descriptions/descriptions.component.ts
  components/grid/row.directive.ts
  components/input/autosize.directive.ts
  components/layout/layout.spec.ts
  components/layout/sider-trigger.component.ts
  components/layout/sider.component.ts
  components/ng-zorro-antd.module.ts
  components/table/src/table/table-inner-scroll.component.ts
  components/tabs/tabs-nav.component.ts
  components/typography/text-copy.component.ts
  components/typography/typography.component.ts
  components/typography/typography.module.ts
Labels: PR: unreviewed

#4927 refactor(module:core): remove updateHostClass service
  components/avatar/avatar.component.ts
  components/core/services/public-api.ts
  components/core/services/update-host-class.ts
  components/icon/icon.directive.ts
  components/list/list.component.ts
  components/result/result.component.ts
  components/result/style/entry.less
  components/result/style/patch.less
  components/tabs/tabs.spec.ts
  components/tabs/tabset.component.ts
  components/tag/tag.component.ts
  components/time-picker/time-picker-panel.component.ts
  components/time-picker/time-picker.component.ts
  components/transfer/nz-transfer-list.component.ts
  components/transfer/nz-transfer.component.ts
  components/upload/upload-btn.component.ts
  components/upload/upload-list.component.ts
Labels: PR: unreviewed

#4931 chore: use NzSafeAny
  components/auto-complete/autocomplete-trigger.directive.ts
  components/carousel/carousel.component.ts
  components/cascader/cascader.component.ts
  components/cascader/cascader.service.ts
  components/cascader/typings.ts
  components/code-editor/code-editor.component.ts
  components/code-editor/code-editor.service.ts
  components/core/time/candy-date.spec.ts
  components/date-picker/date-picker.component.ts
  components/date-picker/lib/abstract-table.ts
  components/date-picker/picker.component.ts
  components/drawer/drawer-ref.ts
  components/drawer/drawer.component.ts
  components/drawer/drawer.service.ts
  components/empty/config.ts
  components/empty/embed-empty.component.ts
  components/i18n/nz-i18n.service.ts
  components/icon/icon.service.ts
  components/mention/mention-trigger.ts
  components/mention/mention.component.ts
  components/modal/modal-confirm-container.component.ts
  components/modal/modal-container.component.ts
  components/modal/modal-container.ts
  components/modal/modal-ref.ts
  components/modal/modal-types.ts
  components/modal/modal.component.ts
  components/modal/modal.service.ts
  components/modal/utils.ts
  components/resizable/resizable.service.ts
  components/tabs/tabs-nav.component.ts
  components/tooltip/base.ts
  components/transfer/interface.ts
  components/transfer/nz-transfer.component.ts
  components/tree/nz-tree.component.ts
  components/typography/text-copy.component.ts
  components/typography/text-edit.component.ts
  components/typography/typography.component.ts
  components/upload/interface.ts
  components/upload/upload-btn.component.ts
  components/upload/upload-list.component.ts
  components/upload/upload.component.ts
Labels: PR: reviewed-approved

#4863 feat(module:pagination): add auto resize
  components/pagination/doc/index.en-US.md
  components/pagination/doc/index.zh-CN.md
  components/pagination/pagination.component.ts
  components/pagination/pagination.spec.ts
Labels: PR: reviewed-approved

#4896 docs: add dynamic themes docs
  docs/customize-theme.en-US.md
  docs/customize-theme.zh-CN.md
  scripts/site/_site/doc/app/app.module.ts
  scripts/site/_site/doc/app/app.service.ts
  scripts/site/_site/doc/app/share/codebox/codebox.component.html
  scripts/site/_site/doc/app/share/codebox/codebox.component.less
  scripts/site/_site/doc/app/share/codebox/codebox.component.ts
  scripts/site/_site/doc/app/share/codebox/codebox.module.ts
  scripts/site/_site/doc/app/share/codebox/index.ts
  scripts/site/_site/doc/app/share/codebox/stack-blitz.ts
  scripts/site/_site/doc/app/share/contributors-list/contributors-list.component.ts
  scripts/site/_site/doc/app/share/contributors-list/contributors-list.module.ts
  scripts/site/_site/doc/app/share/github-btn/github-btn.component.html
  scripts/site/_site/doc/app/share/github-btn/github-btn.component.less
  scripts/site/_site/doc/app/share/github-btn/github-btn.component.ts
  scripts/site/_site/doc/app/share/github-btn/github-btn.module.ts
  scripts/site/_site/doc/app/share/github-btn/index.ts
  scripts/site/_site/doc/app/share/highlight/highlight.component.ts
  scripts/site/_site/doc/app/share/highlight/highlight.module.ts
  scripts/site/_site/doc/app/share/highlight/index.ts
  scripts/site/_site/doc/app/share/nav-bottom/nav-bottom.component.ts
  scripts/site/_site/doc/app/share/nav-bottom/nav-bottom.module.ts
  scripts/site/_site/doc/app/share/nz-codebox/index.ts
  scripts/site/_site/doc/app/share/nz-github-btn/index.ts
  scripts/site/_site/doc/app/share/nz-highlight/index.ts
  scripts/site/_site/doc/app/share/share.module.ts
  scripts/site/template/demo-component.template.ts
  scripts/site/utils/generate-demo.js
  scripts/site/utils/generate-docs.js
Labels: PR: reviewed-approved

#4938 release(9.0.0-beta.3): release 9.0.0-beta.3
  .prettierrc
  CHANGELOG.md
  README-zh_CN.md
  README.md
  components/package.json
  components/version/version.ts
  docs/changelog.en-US.md
  docs/changelog.zh-CN.md
  docs/contributing.en-US.md
  docs/contributing.zh-CN.md
  docs/customize-theme.en-US.md
  docs/customize-theme.zh-CN.md
  docs/getting-started.en-US.md
  docs/getting-started.zh-CN.md
  docs/introduce.en-US.md
  docs/introduce.zh-CN.md
  package.json
Labels: PR: unreviewed

#4942 docs: add ngx-quicklink
  docs/introduce.zh-CN.md
  package.json
  scripts/site/_site/doc/app/app.module.ts
  scripts/site/_site/doc/app/app.routing.module.ts
  scripts/site/_site/doc/app/footer/footer.module.ts
  scripts/site/_site/doc/app/share/contributors-list/contributors-list.component.ts
  scripts/site/_site/doc/app/share/share.module.ts
  scripts/site/_site/doc/assets/doc-search.min.css
  scripts/site/_site/doc/index.html
  scripts/site/_site/doc/polyfills.ts
  scripts/site/_site/doc/style/doc-search.less
  scripts/site/_site/doc/styles.less
Labels: PR: unreviewed

#4944 fix(module:time-picker): ngModelChange not work
  components/time-picker/time-picker-panel.component.ts
  components/time-picker/time-picker.component.spec.ts
  components/time-picker/time-picker.component.ts
  package.json
Labels: PR: reviewed-approved

#4947 fix(module:table): fix table no data
  .gitignore
  azure-pipelines.yml
  build-config.js
  components/table/src/table-data.service.ts
  components/table/src/table/table.component.ts
  integration/angular-cli/package.json
  integration/angular-cli/src/app/app.module.ts
  integration/rollup/src/app/app.module.ts
  integration/webpack/src/app/app.module.ts
  package.json
  scripts/build-config.ts
  scripts/gulp/tasks/library.ts
Labels: PR: unreviewed

#4952 fix(module:list): fix the avatar part old API
  components/list/list-item-meta-cell.ts
Labels: PR: reviewed-approved

#4766 fix(module:tree): fix search case sensitivity
  components/tree/nz-tree-node.component.ts
  components/tree/nz-tree.component.ts
  components/tree/nz-tree.spec.ts
Labels: PR: partially-approved

#4953 fix(module:table): fix 4.1.0 style error
  components/auto-complete/autocomplete-trigger.directive.ts
  components/drawer/drawer.component.ts
  components/dropdown/context-menu.service.ts
  components/ng-zorro-antd.module.ts
  components/pagination/pagination-default.component.ts
  components/pagination/pagination-simple.component.ts
  components/pagination/pagination.component.ts
  components/pagination/pagination.spec.ts
  components/pagination/style/entry.less
  components/pagination/style/patch.less
  components/table/src/addon/filter.component.ts
  components/table/src/cell/td-addon.component.ts
  components/table/src/cell/th-addon.component.ts
  components/table/src/table.module.ts
  components/table/src/table/table.component.ts
  components/table/src/testing/table.spec.ts
  docs/contributing.en-US.md
  docs/contributing.zh-CN.md
  docs/faq.en-US.md
  docs/faq.zh-CN.md
  docs/introduce.en-US.md
  docs/introduce.zh-CN.md
  scripts/site/_site/doc/polyfills.ts
  scripts/site/_site/doc/theme.less
  scripts/site/_site/doc/zone-flags.ts
  scripts/site/template/example-split.template.html
  scripts/site/utils/marked.js
Labels: PR: unreviewed
