Repository NG-ZORRO/ng-zorro-antd, pull requests merged in 2020-11, with the labels that each got.

#5994 fix(module:breadcrumb): patch last-child's style indule a is included
  components/breadcrumb/style/patch.less
Labels: PR: partially-approved

#5998 fix(module:tabs): `nzTabBarGutter` is not work in vertical position
  components/tabs/tabset.component.spec.ts
  components/tabs/tabset.component.ts
Labels: PR: unreviewed

#6008 fix(module:select): disabled allows to open panel
  components/select/select-top-control.component.ts
  components/select/select.component.ts
Labels: PR: partially-approved

#6016 fix(module:tabs): ink-bar does not render correctly in some cases
  components/tabs/tab-nav-bar.component.ts
Labels: PR: unreviewed

#6023 fix(module:cascader): menu closing behavoir
  components/cascader/cascader.component.ts
Labels: PR: reviewed-approved

#6030 fix(module:cascader): sync class name with ant-design
  components/cascader/cascader.component.ts
Labels: PR: partially-approved

#6032 chore(release): release 10.1.1
  CHANGELOG.md
  components/package.json
  components/version/version.ts
  docs/changelog.en-US.md
  docs/changelog.zh-CN.md
Labels: PR: unreviewed

#6049 fix(module:cascader): fix broken nzChangeOnSelect
  components/cascader/cascader.component.ts
Labels: PR: reviewed-approved

#6044 fix(module:code-editor): memorize cursor position and selections
  components/code-editor/code-editor.component.ts
Labels: PR: partially-approved

#6059 style: update tslint to support codelyzer 5.x
  tslint.json
Labels: PR: reviewed-approved

#6058 fix(module:typography): ellipsis does not work with copy action
  components/typography/demo/ellipsis.ts
  components/typography/typography.component.ts
Labels: PR: unreviewed

#6061 fix: include missing language exports
  components/i18n/public-api.ts
Labels: PR: reviewed-approved

#6062 chore(release): release 10.1.2
  CHANGELOG.md
  components/package.json
  components/version/version.ts
  docs/changelog.en-US.md
  docs/changelog.zh-CN.md
Labels: PR: unreviewed

#6073 fix(module:tree-select): selector cannot focus
  components/tree-select/tree-select.component.ts
  components/tree-select/tree-select.spec.ts
Labels: PR: unreviewed

#6078 docs: update readme & discord
  CONTRIBUTING.md
  README-zh_CN.md
  README.md
Labels: PR: unreviewed

#6053 feat(module: graph): support graph component
  components/graph/core/minimap.ts
  components/graph/custom-graph-node.directive.ts
  components/graph/data-source/base-graph-source.ts
  components/graph/data-source/graph-data-source.ts
  components/graph/demo/customized.md
  components/graph/demo/customized.ts
  components/graph/demo/module
  components/graph/doc/index.en-US.md
  components/graph/doc/index.zh-CN.md
  components/graph/graph-defs.component.ts
  components/graph/graph-edge.directive.ts
  components/graph/graph-minimap.component.ts
  components/graph/graph-node.directive.ts
  components/graph/graph-svg-container.component.ts
  components/graph/graph.component.ts
  components/graph/graph.module.ts
  components/graph/index.ts
  components/graph/interface.ts
  components/graph/package.json
  components/graph/public-api.ts
  components/graph/style/entry.less
  components/graph/style/index.less
  components/graph/utils.ts
  package.json
  scripts/site/_site/doc/styles.less
Labels: PR: reviewed-approved

#6082 fix(module:cascader): scroll active options into view
  components/cascader/cascader-li.component.ts
  components/cascader/cascader.component.ts
Labels: PR: partially-approved

#6013 feat(module:drawer): support nzVisible two-way binding
  components/drawer/doc/index.en-US.md
  components/drawer/doc/index.zh-CN.md
  components/drawer/drawer.component.ts
  components/drawer/drawer.spec.ts
Labels: PR: reviewed-approved, PR: target-minor

#6043 feat(module:pagination): support Global Config
  components/core/config/config.ts
  components/pagination/doc/index.en-US.md
  components/pagination/doc/index.zh-CN.md
  components/pagination/pagination.component.ts
Labels: PR: partially-approved

#6092 docs(module:time-picker): update nzAddOn property
  components/time-picker/doc/index.en-US.md
  components/time-picker/doc/index.zh-CN.md
Labels: PR: unreviewed

#6100 refactor(module: graph): remove detach to make sure contentChild can be rendered
  components/graph/graph-node.directive.ts
  components/graph/graph-svg-container.component.ts
  components/graph/graph.component.ts
Labels: PR: reviewed-approved

#6112 fix(module:descriptions): fix DOM structure
  components/descriptions/descriptions.component.ts
Labels: PR: unreviewed

#6079 fix(module:date-picker): clear wrong date input after closing panel
  components/date-picker/date-picker.component.spec.ts
  components/date-picker/date-picker.service.ts
Labels: PR: reviewed-approved

#6101 feat(module:steps): step supports enable and disable
  components/steps/step.component.ts
  components/steps/steps.spec.ts
Labels: PR: unreviewed

#6096 fix(module:upload): fix prevent trigger submit when click list button
  components/upload/upload-list.component.html
Labels: PR: reviewed-approved

#6088 fix(module:cascader): restore its value after cancel search
  components/cascader/cascader.component.ts
  components/cascader/cascader.spec.ts
Labels: PR: unreviewed

#6118 docs(module:tag): replace nzAfterClose with nzOnClose
  components/tag/demo/control.ts
Labels: PR: reviewed-approved

#6085 feat(module:drawer): add `nzDrawerContent` directive
  components/drawer/demo/basic-right.ts
  components/drawer/demo/from-drawer.ts
  components/drawer/demo/multi-level-drawer.ts
  components/drawer/demo/placement.ts
  components/drawer/demo/user-profile.ts
  components/drawer/drawer-content.directive.ts
  components/drawer/drawer.component.ts
  components/drawer/drawer.module.ts
  components/drawer/public-api.ts
Labels: PR: unreviewed

#6081 feat(module:modal): add `nzModalContent` directive
  components/modal/demo/async.ts
  components/modal/demo/basic.ts
  components/modal/demo/footer.md
  components/modal/demo/footer.ts
  components/modal/demo/footer2.md
  components/modal/demo/footer2.ts
  components/modal/demo/locale.ts
  components/modal/demo/position.ts
  components/modal/demo/service.ts
  components/modal/doc/index.en-US.md
  components/modal/doc/index.zh-CN.md
  components/modal/modal-content.directive.ts
  components/modal/modal-footer.directive.spec.ts
  components/modal/modal.component.ts
  components/modal/modal.module.ts
  components/modal/public-api.ts
Labels: PR: unreviewed
