Repository NG-ZORRO/ng-zorro-antd, pull requests merged in 2020-08, with the labels that each got.

#5639 fix(module:tabs): not emit click event from dropdown menu
  components/tabs/tab-nav-operation.component.ts
  components/tabs/tabset.component.ts
Labels: PR: partially-approved

#5640 fix(module:date-picker): window is not defined
  components/date-picker/picker.component.ts
Labels: PR: reviewed-approved

#5670 fix(module:breadcrumb): fix auto-generated with lazy modules
  components/breadcrumb/breadcrumb.component.ts
Labels: PR: reviewed-approved

#5663 fix(module:tabs): router link content projection error
  components/tabs/demo/link-router.ts
  components/tabs/doc/index.en-US.md
  components/tabs/doc/index.zh-CN.md
  components/tabs/style/patch.less
  components/tabs/tab-link.directive.ts
  components/tabs/tab.component.ts
  components/tabs/tabs.module.ts
  components/tabs/tabset.component.spec.ts
  components/tabs/tabset.component.ts
Labels: PR: unreviewed

#5677 fix(module:code-editor): init event never emit when using static loading
  components/code-editor/code-editor.service.ts
  components/code-editor/typings.ts
Labels: PR: unreviewed

#5659 fix(module:tabs): fix dropdown style
  components/tabs/style/patch.less
  components/tabs/tab-nav-operation.component.ts
Labels: PR: unreviewed

#5703 docs: type issue on upload component doc
  components/upload/doc/index.en-US.md
Labels: PR: reviewed-approved

#5715 docs: add missing code
  docs/customize-theme.zh-CN.md
Labels: PR: reviewed-approved

#5727 fix(module:style): fix 4.6.1 sync style
  components/package.json
  package.json
  scripts/site/_site/doc/theme.less
Labels: PR: unreviewed

#5629 refactor(module:*): refactor the WithConfig decorator
  components/affix/affix.component.ts
  components/alert/alert.component.ts
  components/anchor/anchor.component.ts
  components/avatar/avatar.component.ts
  components/back-top/back-top.component.ts
  components/badge/badge.component.ts
  components/button/button.component.ts
  components/card/card.component.ts
  components/carousel/carousel.component.ts
  components/cascader/cascader.component.ts
  components/code-editor/code-editor.service.ts
  components/collapse/collapse-panel.component.ts
  components/collapse/collapse.component.ts
  components/core/config/config.service.ts
  components/date-picker/date-picker.component.ts
  components/descriptions/descriptions.component.ts
  components/drawer/drawer.component.ts
  components/form/form.directive.ts
  components/modal/modal-config.ts
  components/modal/modal-container.ts
  components/modal/modal.service.ts
  components/notification/notification-container.component.ts
  components/page-header/page-header.component.ts
  components/progress/progress.component.ts
  components/rate/rate.component.ts
  components/select/select.component.ts
  components/space/space.component.ts
  components/spin/spin.component.ts
  components/switch/switch.component.ts
  components/table/src/table/table.component.ts
  components/tabs/tabset.component.ts
  components/time-picker/time-picker.component.ts
  components/tree-select/tree-select.component.ts
  components/tree/tree.component.ts
  components/typography/typography.component.ts
Labels: PR: partially-approved

#5728 chore: add action to sync Ant Design styles
  .github/workflows/sync-styles.yml
  docs/introduce.en-US.md
  docs/introduce.zh-CN.md
Labels: PR: reviewed-approved

#5707 chore: add surge preview action
  .github/workflows/preview.yml
Labels: PR: unreviewed
