Repository NG-ZORRO/ng-zorro-antd, pull requests merged in 2020-02, with the labels that each got.

#4754 feat(module:pagination): nzItemRender support prev_5 and next_5
  components/menu/menu.spec.ts
  components/menu/public-api.ts
  components/pagination/demo/item-render.ts
  components/pagination/doc/index.en-US.md
  components/pagination/doc/index.zh-CN.md
  components/pagination/nz-pagination.component.html
  components/pagination/nz-pagination.component.ts
  components/pagination/pagination-default.component.ts
  components/pagination/pagination-item.component.ts
  components/pagination/pagination-options.component.ts
  components/pagination/pagination-simple.component.ts
  components/pagination/pagination.component.ts
  components/pagination/pagination.module.ts
  components/pagination/pagination.spec.ts
  components/pagination/pagination.types.ts
  components/pagination/public-api.ts
  components/table/nz-th.component.ts
Labels: PR: unreviewed

#4756 chore: bump to Angular 9.0.0
  components/package.json
  package.json
Labels: PR: reviewed-approved

#4185 feat(module:input-number): support nzPrecisionMode mode
  components/input-number/demo/precision.md
  components/input-number/demo/precision.ts
  components/input-number/doc/index.en-US.md
  components/input-number/doc/index.zh-CN.md
  components/input-number/nz-input-number.component.ts
  components/input-number/nz-input-number.spec.ts
Labels: PR: reviewed-approved, PR: target-minor, PR: unreviewed

#4722 chore(module:statistic): refactor
  components/core/pipe/nz-pipe.module.ts
  components/core/pipe/public-api.ts
  components/core/pipe/time-range.pipe.ts
  components/core/pipe/time-range.spec.ts
  components/statistic/countdown.component.ts
  components/statistic/countdown.spec.ts
  components/statistic/nz-countdown.component.html
  components/statistic/nz-statistic-number.component.html
  components/statistic/nz-statistic.component.html
  components/statistic/public-api.ts
  components/statistic/statistic-number.component.ts
  components/statistic/statistic-number.spec.ts
  components/statistic/statistic.component.ts
  components/statistic/statistic.module.ts
  components/statistic/statistic.spec.ts
  components/statistic/typings.ts
Labels: PR: reviewed-approved

#4552 feat(module:tree-select): support `nzDropdownClassName` property
  components/tree-select/doc/index.en-US.md
  components/tree-select/doc/index.zh-CN.md
  components/tree-select/nz-tree-select.component.html
  components/tree-select/nz-tree-select.component.ts
  components/tree-select/nz-tree-select.spec.ts
Labels: PR: merge-ready, PR: reviewed-approved, PR: unreviewed

#4769 feat(module:input-number): trigger ngModelChange at once
  components/core/testing/event-objects.ts
  components/input-number/demo/precision.ts
  components/input-number/doc/index.en-US.md
  components/input-number/doc/index.zh-CN.md
  components/input-number/input-number.component.ts
  components/input-number/input-number.module.ts
  components/input-number/input-number.spec.ts
  components/input-number/nz-input-number.component.html
  components/input-number/public-api.ts
  components/input-number/style/index.tsx
Labels: PR: unreviewed

#4726 chore(module:empty): refactor
  components/core/testing/componet-bed.ts
  components/empty/config.ts
  components/empty/demo/config.md
  components/empty/demo/customize.md
  components/empty/demo/description.md
  components/empty/demo/description.ts
  components/empty/demo/simple.md
  components/empty/demo/simple.ts
  components/empty/doc/index.en-US.md
  components/empty/doc/index.zh-CN.md
  components/empty/embed-empty.component.ts
  components/empty/empty.component.ts
  components/empty/empty.module.ts
  components/empty/empty.spec.ts
  components/empty/nz-embed-empty.component.html
  components/empty/nz-empty-config.ts
  components/empty/nz-empty.component.html
  components/empty/nz-empty.component.ts
  components/empty/nz-empty.service.ts
  components/empty/partial/default.ts
  components/empty/partial/simple.ts
  components/empty/public-api.ts
Labels: PR: unreviewed

#4719 chore(module:code-editor): refactor
  components/code-editor/code-editor.component.ts
  components/code-editor/code-editor.module.ts
  components/code-editor/code-editor.service.ts
  components/code-editor/code-editor.spec.ts
  components/code-editor/nz-code-editor.component.html
  components/code-editor/public-api.ts
  components/code-editor/typings.ts
Labels: PR: unreviewed

#4714 feat(module:rate): refactor
  components/rate/nz-rate-item.component.html
  components/rate/nz-rate.component.html
  components/rate/public-api.ts
  components/rate/rate-item.component.ts
  components/rate/rate.component.ts
  components/rate/rate.module.ts
  components/rate/rate.spec.ts
Labels: PR: unreviewed

#4721 chore(module:tooltip,popover,popconfirm): refactor
  components/popconfirm/nz-popconfirm.component.html
  components/popconfirm/nz-popconfirm.component.ts
  components/popconfirm/nz-popconfirm.directive.ts
  components/popconfirm/popconfirm.module.ts
  components/popconfirm/popconfirm.spec.ts
  components/popconfirm/popconfirm.ts
  components/popconfirm/public-api.ts
  components/popover/nz-popover.component.html
  components/popover/nz-popover.component.ts
  components/popover/nz-popover.directive.ts
  components/popover/popover.module.ts
  components/popover/popover.spec.ts
  components/popover/popover.ts
  components/popover/public-api.ts
  components/tooltip/README.md
  components/tooltip/base.ts
  components/tooltip/nz-tooltip-base.component.ts
  components/tooltip/nz-tooltip.component.html
  components/tooltip/nz-tooltip.component.ts
  components/tooltip/nz-tooltip.definitions.ts
  components/tooltip/nz-tooltip.directive.ts
  components/tooltip/public-api.ts
  components/tooltip/tooltip.module.ts
  components/tooltip/tooltip.spec.ts
  components/tooltip/tooltip.ts
  components/upload/nz-upload.spec.ts
Labels: PR: unreviewed

#4715 chore(module:carousel): refactor
  components/carousel/carousel-content.directive.ts
  components/carousel/carousel.component.ts
  components/carousel/carousel.module.ts
  components/carousel/carousel.spec.ts
  components/carousel/demo/autoplay.ts
  components/carousel/demo/basic.ts
  components/carousel/demo/fade.ts
  components/carousel/demo/position.ts
  components/carousel/nz-carousel.component.html
  components/carousel/public-api.ts
  components/carousel/strategies/base-strategy.ts
  components/carousel/strategies/opacity-strategy.ts
  components/carousel/strategies/transform-strategy.ts
  components/carousel/typings.ts
Labels: PR: unreviewed

#4720 chore(module:descriptions): refactor
  components/descriptions/descriptions-item.component.ts
  components/descriptions/descriptions.component.ts
  components/descriptions/descriptions.module.ts
  components/descriptions/descriptions.spec.ts
  components/descriptions/nz-descriptions-item.component.html
  components/descriptions/nz-descriptions.component.html
  components/descriptions/public-api.ts
  components/descriptions/typings.ts
Labels: PR: unreviewed

#4718 chore(module:cascader): refactor
  components/cascader/cascader-li.component.ts
  components/cascader/cascader.component.ts
  components/cascader/cascader.module.ts
  components/cascader/cascader.service.ts
  components/cascader/cascader.spec.ts
  components/cascader/nz-cascader-li.component.html
  components/cascader/nz-cascader.component.html
  components/cascader/public-api.ts
  components/cascader/typings.ts
  components/cascader/utils.ts
Labels: PR: unreviewed

#4724 chore(module:result): refactor
  components/result/nz-result.component.html
  components/result/public-api.ts
  components/result/result-cells.ts
  components/result/result.component.ts
  components/result/result.module.ts
  components/result/result.spec.ts
Labels: PR: unreviewed

#4725 chore(module:progress): refactor
  components/progress/nz-progress.component.html
  components/progress/progress.component.ts
  components/progress/progress.module.ts
  components/progress/progress.spec.ts
  components/progress/public-api.ts
  components/progress/typings.ts
  components/progress/utils.spec.ts
  components/progress/utils.ts
  components/upload/nz-upload.spec.ts
Labels: PR: unreviewed

#4629 feat(module:typography): support `nzSuffix` property
  components/core/util/text-measure.ts
  components/typography/demo/module
  components/typography/demo/suffix.md
  components/typography/demo/suffix.ts
  components/typography/doc/index.en-US.md
  components/typography/doc/index.zh-CN.md
  components/typography/nz-typography.component.html
  components/typography/nz-typography.component.ts
  components/typography/nz-typography.spec.ts
Labels: PR: merge-ready, PR: reviewed-approved

#4690 fix(module:timeline): fix reverse bug
  components/core/util/dom.ts
  components/timeline/nz-timeline-item.component.html
  components/timeline/nz-timeline-item.component.ts
  components/timeline/nz-timeline.component.html
  components/timeline/nz-timeline.component.ts
  components/timeline/public-api.ts
  components/timeline/timeline-item.component.ts
  components/timeline/timeline.component.ts
  components/timeline/timeline.module.ts
  components/timeline/timeline.spec.ts
Labels: PR: unreviewed

#4713 feat(module:breadcrumb): support indenpendent separator
  components/breadcrumb/breadcrumb-item.component.ts
  components/breadcrumb/breadcrumb-separator.component.ts
  components/breadcrumb/breadcrumb.component.ts
  components/breadcrumb/breadcrumb.module.ts
  components/breadcrumb/breadcrumb.spec.ts
  components/breadcrumb/demo/separator-independent.md
  components/breadcrumb/demo/separator-independent.ts
  components/breadcrumb/doc/index.en-US.md
  components/breadcrumb/doc/index.zh-CN.md
  components/breadcrumb/nz-breadcrumb-item.component.html
  components/breadcrumb/nz-breadcrumb.component.html
  components/breadcrumb/public-api.ts
Labels: PR: unreviewed
