Repository NG-ZORRO/ng-zorro-antd, pull requests merged in 2020-04, with the labels that each got.

#4949 fix(module:time-picker): allow inputting string type
  components/i18n/date-helper.service.spec.ts
  components/i18n/date-helper.service.ts
  components/time-picker/time-picker-panel.component.ts
  components/time-picker/time-picker.component.spec.ts
  components/time-picker/time-picker.component.ts
  components/time-picker/time-value-accessor.directive.ts
Labels: PR: reviewed-approved

#4970 feat(module:table): support new nzQueryParams
  components/table/demo/ajax.md
  components/table/demo/ajax.ts
  components/table/demo/reset-filter.ts
  components/table/demo/sort-filter.ts
  components/table/doc/index.en-US.md
  components/table/doc/index.zh-CN.md
  components/table/src/addon/filter.component.ts
  components/table/src/addon/sorters.component.ts
  components/table/src/cell/th-addon.component.ts
  components/table/src/table-data.service.ts
  components/table/src/table.types.ts
  components/table/src/table/table-content.component.ts
  components/table/src/table/table-inner-default.component.ts
  components/table/src/table/table-inner-scroll.component.ts
  components/table/src/table/table.component.ts
  components/table/src/table/thead.component.ts
  components/table/src/testing/table.spec.ts
  components/table/src/testing/th.spec.ts
  components/tabs/demo/lazy.md
  docs/faq.en-US.md
  docs/faq.zh-CN.md
Labels: PR: unreviewed

#4958 docs(module:modal): add template context usage
  components/modal/demo/service.md
  components/modal/demo/service.ts
  components/modal/modal-types.ts
Labels: PR: unreviewed

#4954 fix(module:modal): `nzModalFooter` not work when the modal open on init
  components/modal/modal-footer.directive.spec.ts
  components/modal/modal.component.ts
Labels: PR: unreviewed

#4876 fix(module:date-picker): click date cell not work when changing month or year
  components/date-picker/calendar-footer.component.ts
  components/date-picker/date-picker.component.html
  components/date-picker/date-picker.component.spec.ts
  components/date-picker/date-picker.component.ts
  components/date-picker/date-picker.service.ts
  components/date-picker/date-range-popup.component.ts
  components/date-picker/demo/disabled-date.ts
  components/date-picker/lib/abstract-table.ts
  components/date-picker/picker.component.ts
  components/date-picker/public-api.ts
  components/date-picker/range-picker.component.spec.ts
  components/date-picker/util.ts
Labels: PR: reviewed-approved

#4973 fix(module:tree): fix tree animation
  components/core/animation/collapse.ts
  components/package.json
  components/tree/nz-tree-indent.component.ts
  components/tree/nz-tree-node.component.ts
  components/tree/nz-tree.component.ts
  components/tree/nz-tree.spec.ts
  components/tree/style/patch.less
  docs/introduce.zh-CN.md
  scripts/site/_site/doc/index.html
Labels: PR: unreviewed

#4961 fix(module:time-picker): scroll to wrong position in datepicker
  components/time-picker/time-picker-panel.component.spec.ts
  components/time-picker/time-picker-panel.component.ts
Labels: PR: reviewed-approved

#4849 feat(module:tooltip,etc): support custom origin
  components/core/element-patch/element-patch.directive.ts
  components/core/element-patch/element-patch.module.ts
  components/core/element-patch/element-patch.spec.ts
  components/core/element-patch/index.ts
  components/core/element-patch/package.json
  components/core/element-patch/public-api.ts
  components/popconfirm/doc/index.en-US.md
  components/popconfirm/doc/index.zh-CN.md
  components/popconfirm/popconfirm.ts
  components/popover/doc/index.en-US.md
  components/popover/doc/index.zh-CN.md
  components/popover/popover.ts
  components/tooltip/base.ts
  components/tooltip/demo/module
  components/tooltip/demo/origin.md
  components/tooltip/demo/origin.ts
  components/tooltip/demo/template.ts
  components/tooltip/doc/index.en-US.md
  components/tooltip/doc/index.zh-CN.md
  components/tooltip/tooltip.spec.ts
  components/tooltip/tooltip.ts
Labels: PR: partially-approved

#4984 feat(module:code-editor): upgrade monaco to 0.20.0 and update interfaces
  components/code-editor/typings.ts
  package.json
Labels: PR: unreviewed

#4965 fix(module:badge): allow `nzTitle` set to null
  components/badge/badge.component.ts
  components/badge/badge.spec.ts
  components/badge/demo/no-wrapper.ts
  components/badge/doc/index.en-US.md
  components/badge/doc/index.zh-CN.md
  components/badge/preset-colors.ts
  components/badge/types.ts
  scripts/site/_site/doc/style/patch.less
Labels: PR: reviewed-approved

#4946 chore: add optional chaining and nullish coalescing
  components/core/config/config.service.ts
  components/core/time/candy-date.ts
  components/form/demo/layout.ts
  components/slider/handle.component.ts
  components/time-picker/time-picker-panel.component.ts
  components/tree/demo/dynamic.ts
  components/typography/text-edit.component.ts
  schematics/ng-add/setup-project/register-locale.ts
  schematics/ng-add/setup-project/theming.ts
  schematics/utils/build-component.ts
  schematics/utils/ng-update/elements.ts
  schematics/utils/package-config.ts
Labels: PR: reviewed-approved

#4928 feat(module:space): add new component
  components/components.less
  components/core/config/config.ts
  components/space/demo/basic.md
  components/space/demo/basic.ts
  components/space/demo/customize.md
  components/space/demo/customize.ts
  components/space/demo/module
  components/space/demo/size.md
  components/space/demo/size.ts
  components/space/demo/vertical.md
  components/space/demo/vertical.ts
  components/space/doc/index.en-US.md
  components/space/doc/index.zh-CN.md
  components/space/index.ts
  components/space/package.json
  components/space/public-api.ts
  components/space/space-item.component.ts
  components/space/space.component.spec.ts
  components/space/space.component.ts
  components/space/space.module.ts
  components/space/style/entry.less
  components/space/style/index.less
  components/space/style/patch.less
  components/space/types.ts
Labels: :star: New Component, PR: reviewed-approved, PR: unreviewed

#4972 feat: support compact theme
  components/dark-theme.js
  docs/customize-theme.en-US.md
  docs/customize-theme.zh-CN.md
  package.json
  scripts/build/compact-vars.ts
  scripts/build/compile-styles.ts
  scripts/build/dark-vars.ts
  scripts/build/generate-less-vars.ts
  scripts/gulp/tasks/library.ts
  scripts/site/_site/doc/app/app.component.ts
  scripts/site/_site/doc/app/share/fixed-widgets/fixed-widgets.component.ts
  scripts/site/_site/doc/app/share/fixed-widgets/fixed-widgets.module.ts
  scripts/site/_site/doc/app/share/fixed-widgets/theme-icons.ts
  scripts/site/_site/doc/style/common.less
  scripts/site/generate-theme.js
Labels: PR: reviewed-approved

#4985 refactor(module:transfer): refactor
  components/transfer/demo/basic.ts
  components/transfer/doc/index.en-US.md
  components/transfer/doc/index.zh-CN.md
  components/transfer/nz-transfer-list.component.html
  components/transfer/nz-transfer-search.component.html
  components/transfer/nz-transfer.component.html
  components/transfer/public-api.ts
  components/transfer/transfer-list.component.ts
  components/transfer/transfer-search.component.ts
  components/transfer/transfer.component.ts
  components/transfer/transfer.module.ts
  components/transfer/transfer.spec.ts
Labels: Component: Transfer, PR: reviewed-approved, PR: unreviewed

#5013 fix(module:page-header): location inject error
  components/page-header/doc/index.en-US.md
  components/page-header/doc/index.zh-CN.md
  components/page-header/page-header.component.ts
Labels: PR: reviewed-approved

#5014 fix(module:modal): fix close button style
  components/drawer/drawer.component.ts
  components/drawer/drawer.spec.ts
Labels: PR: unreviewed

#5012 fix: add theme bundle files
  components/ng-zorro-antd.compact.less
  components/ng-zorro-antd.dark.less
  docs/customize-theme.en-US.md
  docs/customize-theme.zh-CN.md
  scripts/build/compile-styles.ts
Labels: PR: unreviewed

#4983 chore(module:date-picker,time-picker): improve interaction
  components/core/time/candy-date.ts
  components/date-picker/date-picker.component.html
  components/date-picker/date-picker.component.spec.ts
  components/date-picker/date-picker.component.ts
  components/date-picker/date-picker.service.ts
  components/date-picker/date-range-popup.component.ts
  components/date-picker/inner-popup.component.ts
  components/date-picker/lib/abstract-panel-header.html
  components/date-picker/lib/date-table.component.ts
  components/date-picker/lib/interface.ts
  components/date-picker/picker.component.ts
  components/date-picker/range-picker.component.spec.ts
  components/icon/icon.service.ts
  components/icon/icons.ts
  components/time-picker/time-holder.spec.ts
  components/time-picker/time-holder.ts
  components/time-picker/time-picker-panel.component.spec.ts
  components/time-picker/time-picker-panel.component.ts
  components/time-picker/time-picker.component.spec.ts
  components/time-picker/time-picker.component.ts
Labels: PR: reviewed-approved

#4989 feat(module:notification): add onClick observable
  components/message/base.ts
  components/message/doc/index.en-US.md
  components/message/doc/index.zh-CN.md
  components/message/message-container.component.ts
  components/message/message.component.ts
  components/message/message.service.ts
  components/message/message.spec.ts
  components/message/public-api.ts
  components/message/typings.ts
  components/notification/demo/basic.ts
  components/notification/doc/index.en-US.md
  components/notification/doc/index.zh-CN.md
  components/notification/notification-container.component.ts
  components/notification/notification.component.ts
  components/notification/notification.service.ts
  components/notification/notification.spec.ts
  components/notification/typings.ts
  scripts/site/_site/doc/app/app.module.ts
Labels: PR: reviewed-approved

#4939 fix: fix handle transform in vertical mode
  components/slider/handle.component.ts
Labels: PR: reviewed-approved

#4469 feat(schematics): add v9 migration rules for carousel and inject tokens
  schematics/ng-update/index.ts
  schematics/ng-update/test-cases/v9/deprecated-injection-tokens.spec.ts
  schematics/ng-update/test-cases/v9/deprecated-inputs-carousel.spec.ts
  schematics/ng-update/upgrade-rules/checks/carousel-like-template-rule.ts
  schematics/ng-update/upgrade-rules/checks/injection-token-rule.ts
  schematics/utils/ng-update/module-specifiers.ts
Labels: PR: merge-ready, PR: partially-approved, PR: unreviewed

#5020 chore(module:date-picker): improve interaction again
  components/date-picker/date-picker.component.html
  components/date-picker/date-picker.component.ts
  components/date-picker/date-range-popup.component.ts
  components/date-picker/inner-popup.component.ts
  components/time-picker/time-picker-panel.component.spec.ts
  components/time-picker/time-picker-panel.component.ts
  components/time-picker/time-picker.component.ts
Labels: PR: reviewed-approved

#5021 chore(release): release 9.0.0-beta.4
  CHANGELOG.md
  components/ng-zorro-antd.module.ts
  components/package.json
  components/version/version.ts
  docs/changelog.en-US.md
  docs/changelog.zh-CN.md
  scripts/release/release-site.ts
  scripts/release/release.ts
Labels: PR: reviewed-approved

#5025 fix(module:button): fix icon only style
  components/button/button.component.ts
  components/button/button.spec.ts
Labels: PR: unreviewed

#4888 feat(module:form): support auto error tips
  components/core/config/config.ts
  components/form/demo/auto-tips.md
  components/form/demo/auto-tips.ts
  components/form/doc/index.en-US.md
  components/form/doc/index.zh-CN.md
  components/form/form-control.component.ts
  components/form/form-control.spec.ts
  components/form/form.directive.ts
Labels: PR: reviewed-approved

#5027 chore: add the core entry port compatibility
  components/core/index.ts
  components/core/package.json
  components/core/public-api.ts
  components/tree-select/demo/async.ts
  components/tree/demo/basic-controlled.ts
  components/tree/demo/basic.ts
  components/tree/demo/directory.ts
  components/tree/demo/draggable-confirm.ts
  components/tree/demo/draggable.ts
  components/tree/demo/dynamic.ts
  components/tree/demo/line.ts
  components/tree/demo/search.ts
  components/tree/public-api.ts
  docs/animations.en-US.md
  docs/animations.zh-CN.md
  docs/global-config.en-US.md
  docs/global-config.zh-CN.md
Labels: PR: reviewed-approved

#5037 refactor(module:form): modify nzTipOptions to nzAutoTips
  components/core/config/config.ts
  components/form/demo/auto-tips.md
  components/form/demo/auto-tips.ts
  components/form/doc/index.en-US.md
  components/form/doc/index.zh-CN.md
  components/form/form-control.component.ts
  components/form/form-control.spec.ts
  components/form/form.directive.ts
Labels: PR: unreviewed

#5036 chore(release): release 9.0.0
  .travis.yml
  CHANGELOG.md
  README-zh_CN.md
  README.md
  commitlint.config.js
  components/button/button.component.ts
  components/package.json
  components/space/demo/basic.ts
  components/upload/demo/basic.ts
  components/upload/demo/default-file-list.ts
  components/upload/demo/file-list.ts
  components/upload/demo/picture-style.ts
  components/upload/demo/preview-file.ts
  components/upload/demo/upload-manually.ts
  components/version/version.ts
  docs/changelog.en-US.md
  docs/changelog.zh-CN.md
  docs/introduce.en-US.md
  docs/introduce.zh-CN.md
  scripts/site/_site/doc/app/header/header.component.ts
Labels: PR: unreviewed

#5055 fix: ngcc errors caused by overlapping entry-points
  components/core/index.ts
  components/core/package.json
  components/core/public-api.ts
  schematics/ng-update/index.ts
  schematics/ng-update/test-cases/v9/secondary-entry-points.spec.ts
  schematics/ng-update/upgrade-rules/checks/secondary-entry-points-rule.ts
Labels: PR: reviewed-approved

#5038 chore: update schematics config
  schematics/migration.json
  schematics/ng-add/index.spec.ts
  schematics/ng-add/schema.json
  schematics/ng-add/setup-project/register-locale.ts
Labels: PR: reviewed-approved

#5063 fix(module:select): wrong sort in group option
  components/select/select.component.ts
  components/select/select.spec.ts
Labels: PR: reviewed-approved

#5057 fix(module:select): options overflow content cannot be hidden
  components/select/option-container.component.ts
  components/select/style/patch.less
Labels: PR: reviewed-approved

#5066 fix(module:select): fix nzDropdownMatchSelectWidth not work
  components/core/transition-patch/transition-patch.directive.ts
  components/select/option-container.component.ts
  components/select/select.component.ts
  components/select/select.spec.ts
  components/select/style/patch.less
  components/spin/spin.component.ts
  docs/faq.zh-CN.md
Labels: PR: unreviewed

#5053 fix(module:popover): change visible correctly
  components/tooltip/base.ts
  components/tooltip/tooltip.spec.ts
Labels: PR: reviewed-approved

#5074 docs(module:space): fix typo
  components/space/doc/index.zh-CN.md
Labels: PR: reviewed-approved

#4524 fix(module:form): fix changes not calling detectChanges
  components/core/types/input-observable.ts
  components/core/types/public-api.ts
  components/form/form-control.component.ts
  components/form/form-control.spec.ts
  components/form/form-label.component.ts
  components/form/form.directive.ts
Labels: PR: reviewed-approved

#5082 fix(module:input): fix input group missing focus and disabled
  components/input/input-group.component.ts
  components/input/input-group.spec.ts
  components/input/input.directive.ts
Labels: PR: unreviewed

#5081 fix(module:all): fix enableIvy:false with ng-zorro-antd
  components/avatar/avatar.component.ts
  components/card/card-loading.component.ts
  components/date-picker/date-picker.component.html
  components/date-picker/date-picker.component.ts
  components/drawer/drawer.module.ts
  components/dropdown/dropdown-menu.component.ts
  components/dropdown/dropdown.module.ts
  components/form/form.directive.ts
  components/grid/col.directive.ts
  components/icon/icon.directive.ts
  components/menu/submenu-inline-child.component.ts
  components/menu/submenu-non-inline-child.component.ts
  components/message/message.module.ts
  components/modal/modal-confirm-container.component.ts
  components/modal/modal-container.component.ts
  components/modal/modal.module.ts
  components/notification/notification.module.ts
  components/popconfirm/popconfirm.module.ts
  components/popover/popover.module.ts
  components/resizable/resize-handle.component.ts
  components/table/src/table/table-inner-scroll.component.ts
  components/tabs/tabset.component.ts
  components/tag/tag.component.ts
  components/time-picker/time-picker-panel.component.ts
  components/time-picker/time-picker.component.ts
  components/tooltip/tooltip.module.ts
  components/transfer/transfer-list.component.ts
  components/transfer/transfer.component.ts
  components/tree-select/tree-select.component.ts
  components/tree/tree-indent.component.ts
  components/upload/upload-btn.component.ts
  components/upload/upload-list.component.ts
  components/upload/upload.component.html
  components/upload/upload.spec.ts
  scripts/site/template/demo-module.template.ts
  scripts/site/utils/generate-demo.js
Labels: PR: unreviewed

#5083 docs: support run codes on CodeSandbox
  package.json
  scripts/site/_site/doc/app/online-ide/files/angular.json.ts
  scripts/site/_site/doc/app/online-ide/files/app.module.ts
  scripts/site/_site/doc/app/online-ide/files/dot_angular-cli.json.ts
  scripts/site/_site/doc/app/online-ide/files/environment.ts
  scripts/site/_site/doc/app/online-ide/files/main.ts
  scripts/site/_site/doc/app/online-ide/files/ng-zorro-antd.module.ts
  scripts/site/_site/doc/app/online-ide/files/polyfill.ts
  scripts/site/_site/doc/app/online-ide/online-ide.service.ts
  scripts/site/_site/doc/app/share/codebox/codebox.component.html
  scripts/site/_site/doc/app/share/codebox/codebox.component.ts
  scripts/site/_site/doc/app/share/codebox/codebox.module.ts
  scripts/site/_site/doc/app/share/codebox/stack-blitz.ts
Labels: PR: unreviewed

#5084 docs: add migration guide
  components/code-editor/code-editor.component.ts
  components/code-editor/code-editor.service.ts
  components/resizable/resizable.service.ts
  components/space/space.component.ts
  components/time-picker/time-picker.component.ts
  components/transfer/transfer.component.ts
  components/tree/demo/virtual-scroll.ts
  docs/migration-v9.en-US.md
  docs/migration-v9.zh-CN.md
Labels: PR: unreviewed

#5085 fix(module:button): fix button type definition
  components/button/button.component.ts
Labels: PR: unreviewed

#5072 feat(module: date-picker, time-picker): support custom suffix icon
  components/core/config/config.ts
  components/date-picker/date-picker.component.html
  components/date-picker/date-picker.component.spec.ts
  components/date-picker/date-picker.component.ts
  components/date-picker/date-picker.module.ts
  components/date-picker/doc/index.en-US.md
  components/date-picker/doc/index.zh-CN.md
  components/date-picker/picker.component.ts
  components/time-picker/doc/index.en-US.md
  components/time-picker/doc/index.zh-CN.md
  components/time-picker/time-picker.component.spec.ts
  components/time-picker/time-picker.component.ts
  components/time-picker/time-picker.module.ts
Labels: PR: reviewed-approved, PR: target-minor

#5090 fix: backward-compatible with the previous rendering engine
  components/date-picker/date-range-popup.component.ts
  components/date-picker/month-picker.component.spec.ts
  components/date-picker/picker.component.ts
  components/modal/modal-confirm-container.component.ts
  components/modal/modal-container.component.ts
  components/modal/modal.module.ts
  components/select/select.component.ts
  components/skeleton/skeleton-element.component.ts
  components/skeleton/skeleton.spec.ts
Labels: PR: reviewed-approved

#5095 fix(module:menu): fix menu matchRouter not work
  components/menu/menu-item.directive.ts
Labels: PR: unreviewed

#5092 feat(module:select): support global config nzSuffixIcon
  components/core/config/config.ts
  components/select/doc/index.en-US.md
  components/select/doc/index.zh-CN.md
  components/select/select-arrow.component.ts
  components/select/select.component.ts
Labels: PR: unreviewed

#5097 fix(module:tooltip): fix title not updated to component
  components/tooltip/base.ts
Labels: PR: unreviewed

#5104 fix(module:time-picker): allow undefined or null input
  components/time-picker/time-picker.component.ts
Labels: PR: reviewed-approved

#5103 fix(module:modal): `NoopAnimations` do not work with modal mask
  components/modal/modal-config.ts
  components/modal/modal-container.ts
  components/modal/modal.service.ts
Labels: PR: reviewed-approved

#5105 fix(module:date-picker): support clicking host to open panel
  components/date-picker/date-picker.component.html
  components/date-picker/date-picker.component.ts
  components/date-picker/picker.component.ts
  components/time-picker/time-picker.component.ts
Labels: PR: unreviewed

#5039 chore(module:page-header): sync ant-design v4.1.4
  components/page-header/page-header.component.ts
  components/page-header/style/index.less
Labels: PR: reviewed-approved

#5123 fix(module:message): fix message remove error when no container
  components/message/base.ts
Labels: PR: unreviewed

#5126 fix(module:date-picker): set formControl disabled not work
  components/date-picker/date-picker.component.spec.ts
  components/date-picker/date-picker.component.ts
Labels: PR: reviewed-approved

#5117 fix(module:select): fix ie11 select search input
  README-zh_CN.md
  README.md
  components/core/transition-patch/transition-patch.directive.ts
  components/select/option-container.component.ts
  components/select/select-search.component.ts
  components/select/select.module.ts
Labels: PR: unreviewed

#5131 fix(module:select): fix virtual scroll hover bug
  components/select/option-container.component.ts
  components/select/select.component.ts
Labels: PR: unreviewed

#5133 feat(module:select): support option height and opiton overflow size
  components/select/doc/index.en-US.md
  components/select/doc/index.zh-CN.md
  components/select/option-container.component.ts
  components/select/select.component.ts
Labels: PR: unreviewed

#5132 fix(module:table): remove table nzQueryParams debounceTime
  components/table/src/table-data.service.ts
Labels: PR: unreviewed

#5147 fix(module:space): fix config name
  components/space/space.component.ts
Labels: PR: reviewed-approved

#5134 chore(module:tooltip): hide deprecation warning when specific propert…
  components/tooltip/base.ts
Labels: PR: reviewed-approved

#5140 fix(module:notification): fix global config nzPlacement not working
  components/notification/demo/placement.ts
  components/notification/notification-container.component.ts
  components/notification/typings.ts
Labels: PR: reviewed-approved

#5144 fix(module:form): the setStatus needs to call again on tips changes
  components/form/demo/auto-tips.ts
  components/form/form-control.component.ts
  components/form/form-control.spec.ts
Labels: PR: reviewed-approved

#5151 docs: add fossa scan result
  README-zh_CN.md
  README.md
  components/popconfirm/doc/index.en-US.md
  components/popconfirm/doc/index.zh-CN.md
  components/popover/doc/index.en-US.md
  components/popover/doc/index.zh-CN.md
  components/tooltip/doc/index.en-US.md
  components/tooltip/doc/index.zh-CN.md
Labels: PR: unreviewed

#5136 fix(module:progress): fix nzFormat not shown status is exception
  components/progress/progress.component.ts
Labels: PR: reviewed-approved

#5139 fix(module:description): fix description not accept TemplateRef
  components/descriptions/descriptions-item.component.ts
  components/descriptions/descriptions.component.ts
Labels: PR: reviewed-approved

#5148 fix(module:cascader): fix cascader position
  components/cascader/style/entry.less
  components/cascader/style/patch.less
  components/core/overlay/overlay-position.ts
Labels: PR: reviewed-approved

#5109 feat(module:select): support input nzOptions in select
  components/select/demo/big-data.ts
  components/select/demo/options.md
  components/select/demo/options.ts
  components/select/doc/index.en-US.md
  components/select/doc/index.zh-CN.md
  components/select/select.component.ts
  components/select/select.spec.ts
  components/select/select.types.ts
Labels: PR: unreviewed

#5155 fix(module:menu): fix submenu scrollable
  components/menu/submenu.component.ts
Labels: PR: unreviewed

#5153 docs(module:tree): add tips for the order of property settings
  components/tree/doc/index.en-US.md
  components/tree/doc/index.zh-CN.md
Labels: PR: unreviewed

#4996 feat(module:autocomplete): support values whit object type
  components/auto-complete/autocomplete-trigger.directive.ts
  components/auto-complete/autocomplete.component.ts
  components/auto-complete/autocomplete.spec.ts
  components/auto-complete/demo/object-value.md
  components/auto-complete/demo/object-value.ts
  components/auto-complete/doc/index.en-US.md
  components/auto-complete/doc/index.zh-CN.md
Labels: PR: unreviewed

#5157 fix(module:auto-complete): dropdown position error with group-input
  components/auto-complete/autocomplete-trigger.directive.ts
  components/auto-complete/autocomplete.module.ts
  components/auto-complete/autocomplete.spec.ts
  components/input/input-group.component.ts
  components/input/input.module.ts
Labels: PR: reviewed-approved

#5158 chore(release): release 9.1.0
  CHANGELOG.md
  components/package.json
  components/version/version.ts
  docs/changelog.en-US.md
  docs/changelog.zh-CN.md
Labels: PR: unreviewed

#5145 docs(module:tooltip): add direction of cdkScrollable
  components/tooltip/doc/index.en-US.md
  components/tooltip/doc/index.zh-CN.md
Labels: PR: reviewed-approved

#5159 chore: fix test:watch on Windows
  package.json
  scripts/gulp/util/task-helpers.ts
Labels: PR: reviewed-approved

#5177 fix(module:modal): rollback to component types can be the content of confirm-mode
  components/modal/modal-confirm-container.component.ts
  components/modal/modal.spec.ts
Labels: PR: partially-approved
