Repository NG-ZORRO/ng-zorro-antd, pull requests merged in 2020-10, with the labels that each got.

#5856 docs: correct Angular version
  docs/migration-v10.en-US.md
Labels: PR: unreviewed

#5851 fix(module:upload): fix upload list style of picture card type
  components/upload/demo/picture-card.ts
  components/upload/upload-list.component.html
Labels: PR: reviewed-approved

#5874 chore: bump @angular/cdk to 10.2.4
  components/package.json
  docs/migration-v10.en-US.md
  docs/migration-v10.zh-CN.md
  package.json
  schematics/ng-update/data/input-names.ts
  schematics/ng-update/data/output-names.ts
  schematics/ng-update/data/property-names.ts
Labels: PR: unreviewed

#5872 fix(module:code-editor): run value changes in Angular zone
  components/code-editor/code-editor.component.ts
Labels: PR: unreviewed

#5863 fix(module:breadcrumb): fix breadcrumbs not returned
  components/breadcrumb/breadcrumb.component.ts
Labels: PR: unreviewed

#5841 fix(module:date-picker,time-picker): open the panel wrongly in IE11
  components/date-picker/date-picker.component.spec.ts
  components/date-picker/date-picker.service.ts
  components/date-picker/date-range-popup.component.ts
  components/date-picker/month-picker.component.spec.ts
  components/date-picker/picker.component.ts
  components/date-picker/range-picker.component.spec.ts
  components/date-picker/year-picker.component.spec.ts
  components/time-picker/time-picker.component.ts
Labels: PR: reviewed-approved

#5865 docs: show how to append theme style
  docs/customize-theme.en-US.md
Labels: PR: unreviewed

#5842 build: update ngsw-config.json
  ngsw-config.json
  package.json
  scripts/gulp/tasks/universal.ts
  scripts/prerender/ngsw-config.ts
Labels: PR: unreviewed

#5866 docs(module:table): improves documentation
  components/table/doc/index.en-US.md
Labels: PR: unreviewed

#5561 fix(module:modal): modal's nzOnOk/nzOnCancel swallow Promise Rejection
  components/modal/modal-ref.ts
  components/modal/modal.spec.ts
Labels: PR: reviewed-approved

#5804 fix(module:date-picker): years contain disabled date cannot select
  components/date-picker/date-picker.component.spec.ts
  components/date-picker/inner-popup.component.ts
  components/date-picker/lib/month-table.component.ts
  components/date-picker/lib/year-table.component.ts
  components/date-picker/month-picker.component.spec.ts
Labels: PR: reviewed-approved

#5879 docs: optimization site
  docs/introduce.en-US.md
  docs/introduce.zh-CN.md
  docs/schematics.en-US.md
  docs/schematics.zh-CN.md
  scripts/site/_site/doc/app/app.component.ts
  scripts/site/_site/doc/app/app.module.ts
  scripts/site/_site/doc/app/app.routing.module.ts
  scripts/site/_site/doc/app/header/github-button.component.ts
  scripts/site/_site/doc/app/header/header.component.ts
  scripts/site/_site/doc/app/header/navigation.component.ts
  scripts/site/_site/doc/app/share/codebox/codebox.component.html
  scripts/site/_site/doc/app/share/share.module.ts
  scripts/site/template/title.template.html
Labels: PR: unreviewed

#5880 chore(release): release 10.0.1
  CHANGELOG.md
  components/package.json
  components/version/version.ts
  docs/changelog.en-US.md
  docs/changelog.zh-CN.md
Labels: PR: reviewed-approved

#5895 fix(module:pagination): fix shoule be only allowed number
  components/pagination/pagination-options.component.ts
Labels: PR: unreviewed

#5893 docs: ignore server-side redirected URLs in the SW
  docs/introduce.en-US.md
  docs/introduce.zh-CN.md
  ngsw-config.json
  package.json
  scripts/prerender/minify.ts
  scripts/prerender/ngsw-config.ts
  scripts/site/_site/doc/app/app.component.ts
  scripts/site/_site/doc/app/header/header.less
  scripts/site/_site/doc/app/header/logo.component.ts
  scripts/site/utils/generate-docs.js
  scripts/site/utils/generate-routes.js
  scripts/site/utils/get-meta.js
  scripts/site/utils/parse-doc-md.js
Labels: PR: unreviewed

#5862 fix(module:slider): fix slider precision when step is decimal
  components/slider/slider.component.ts
  components/slider/slider.spec.ts
Labels: PR: target-patch, PR: unreviewed

#5868 fix(module:tooltip): fix mouse leave overlay not obey delaying
  components/popconfirm/popconfirm.ts
  components/popover/popover.ts
  components/tooltip/base.ts
  components/tooltip/demo/basic.ts
  components/tooltip/tooltip.spec.ts
  components/tooltip/tooltip.ts
Labels: PR: reviewed-approved, PR: target-patch, PR: unreviewed

#5904 fix(module:select): accept 0 value on enter
  components/select/select.component.ts
Labels: PR: reviewed-approved

#5903 docs: add pipes in prerender routers
  README-zh_CN.md
  README.md
  docs/changelog.en-US.md
  docs/changelog.zh-CN.md
  docs/customize-theme.en-US.md
  docs/customize-theme.zh-CN.md
  docs/getting-started.en-US.md
  docs/introduce.en-US.md
  docs/introduce.zh-CN.md
  docs/recommendation.en-US.md
  docs/recommendation.zh-CN.md
  scripts/prerender/ngsw-config.ts
  scripts/prerender/route-paths.txt
  scripts/site/_site/doc/app/footer/footer.component.ts
  scripts/site/_site/doc/app/share/contributors-list/contributors-list.component.ts
  scripts/site/_site/doc/style/highlight.less
Labels: PR: unreviewed

#5918 docs: better LCP with prerender
  docs/introduce.zh-CN.md
  scripts/site/_site/doc/app/app.module.ts
Labels: PR: unreviewed

#5922 fix(module:tooltip): fix tooltip trigger delay not get
  components/tooltip/base.ts
  components/tooltip/demo/basic.ts
Labels: PR: reviewed-approved

#5921 docs: improve docs in EN
  docs/animations.en-US.md
  docs/contributing.en-US.md
  docs/getting-started.en-US.md
  docs/getting-started.zh-CN.md
  docs/global-config.en-US.md
  docs/recommendation.en-US.md
  docs/schematics.en-US.md
  docs/universal.en-US.md
Labels: PR: reviewed-approved

#5930 fix(module:spin): make delay behave more accurately
  components/spin/demo/delay-and-debounce.md
  components/spin/spin.component.ts
  components/spin/spin.spec.ts
Labels: PR: reviewed-approved

#5934 docs: update readme
  README-zh_CN.md
  README.md
  docs/introduce.en-US.md
  docs/introduce.zh-CN.md
Labels: PR: unreviewed

#5933 fix(module:code-editor): only emit update if value changed
  components/code-editor/code-editor.component.ts
Labels: PR: reviewed-approved

#5924 docs: update sitemap
  README.md
  components/space/doc/index.zh-CN.md
  docs/faq.en-US.md
  docs/faq.zh-CN.md
  docs/introduce.en-US.md
  docs/introduce.zh-CN.md
  docs/recommendation.en-US.md
  docs/recommendation.zh-CN.md
  docs/universal.en-US.md
  docs/universal.zh-CN.md
  scripts/prerender/minify.ts
  scripts/prerender/route-paths.txt
  scripts/prerender/sitemap.ts
  scripts/site/_site/doc/app/app.component.ts
  scripts/site/_site/doc/app/footer/footer-item.component.ts
  scripts/site/_site/doc/app/header/github-button.component.ts
  scripts/site/_site/doc/app/header/logo.component.ts
  scripts/site/_site/doc/app/header/searchbar.component.ts
  scripts/site/_site/doc/app/utils/load-script.ts
  scripts/site/_site/doc/index.html
  scripts/site/_site/doc/style/patch.less
  scripts/site/utils/get-meta.js
  scripts/site/utils/marked.js
Labels: PR: partially-approved

#5935 chore(release): release 10.0.2
  CHANGELOG.md
  components/package.json
  components/version/version.ts
  docs/changelog.en-US.md
  docs/changelog.zh-CN.md
  scripts/site/_site/doc/app/header/github-button.component.ts
  scripts/site/_site/doc/assets/icons/icon-128.png
  scripts/site/_site/doc/assets/icons/icon-144.png
  scripts/site/_site/doc/assets/icons/icon-152.png
  scripts/site/_site/doc/assets/icons/icon-72.png
  scripts/site/_site/doc/assets/icons/icon-96.png
Labels: PR: reviewed-approved

#5939 fix(doc layout): duplicated binding description
  components/layout/doc/index.en-US.md
  components/layout/doc/index.zh-CN.md
Labels: PR: reviewed-approved

#5945 docs: use cdn img and pwa optimazition
  docs/introduce.en-US.md
  docs/introduce.zh-CN.md
  scripts/site/_site/doc/app/app.component.ts
  scripts/site/_site/doc/app/header/logo.component.ts
  scripts/site/_site/doc/manifest.json
Labels: PR: reviewed-approved

#5948 docs: fix site title
  .github/workflows/preview.yml
  docs/introduce.en-US.md
  docs/introduce.zh-CN.md
  scripts/site/_site/doc/app/app.component.ts
Labels: PR: unreviewed

#5954 fix(module:tabs): link is not active on the whole tab
  components/tabs/style/patch.less
Labels: PR: unreviewed

#5953 fix(module:select): input search not work in IE11
  components/select/select-search.component.ts
  components/select/select-top-control.component.ts
Labels: PR: unreviewed

#5925 refactor(module:all): remove the backdrop of most components
  components/auto-complete/autocomplete-trigger.directive.ts
  components/auto-complete/autocomplete.spec.ts
  components/cascader/cascader.component.ts
  components/cascader/style/patch.less
  components/date-picker/date-picker.component.spec.ts
  components/date-picker/month-picker.component.spec.ts
  components/date-picker/picker.component.ts
  components/date-picker/range-picker.component.spec.ts
  components/date-picker/year-picker.component.spec.ts
  components/dropdown/doc/index.en-US.md
  components/dropdown/doc/index.zh-CN.md
  components/dropdown/dropdown.directive.ts
  components/mention/mention.component.ts
  components/mention/nz-mention.spec.ts
  components/popconfirm/popconfirm.ts
  components/popover/popover.ts
  components/select/select-top-control.component.ts
  components/select/select.component.ts
  components/select/select.spec.ts
  components/time-picker/time-picker.component.ts
  components/tooltip/base.ts
  components/tooltip/tooltip.spec.ts
  components/tooltip/tooltip.ts
  components/tree-select/tree-select.component.ts
  components/tree-select/tree-select.spec.ts
Labels: PR: target-minor, PR: unreviewed

#5964 docs: update Akita documentation website URL
  docs/recommendation.en-US.md
  docs/recommendation.zh-CN.md
Labels: PR: reviewed-approved

#5962 fix(module:form): remove @host so child components recieve autotips
  components/form/form-control.component.ts
Labels: PR: reviewed-approved

#5932 feat(module:menu): add danger style
  components/dropdown/demo/basic.ts
  components/menu/doc/index.en-US.md
  components/menu/doc/index.zh-CN.md
  components/menu/menu-item.directive.ts
  components/menu/menu.spec.ts
Labels: PR: partially-approved, PR: target-minor, PR: unreviewed

#5920 feat(module:avatar): support for set gap
  components/avatar/avatar.component.ts
  components/avatar/avatar.spec.ts
  components/avatar/demo/dynamic.ts
  components/avatar/demo/module
  components/avatar/doc/index.en-US.md
  components/avatar/doc/index.zh-CN.md
  components/core/config/config.ts
Labels: PR: target-minor, PR: unreviewed

#5915 feat(module:typography): support success type
  components/typography/demo/ellipsis.ts
  components/typography/demo/text.ts
  components/typography/demo/title.ts
  components/typography/doc/index.en-US.md
  components/typography/doc/index.zh-CN.md
  components/typography/typography.component.ts
  components/typography/typography.spec.ts
Labels: PR: target-minor, PR: unreviewed

#5899 feat(module:cascader): support suffix icon & expand icon
  components/cascader/cascader-li.component.ts
  components/cascader/cascader.component.ts
  components/cascader/cascader.spec.ts
  components/cascader/demo/basic.ts
  components/cascader/doc/index.en-US.md
  components/cascader/doc/index.zh-CN.md
Labels: PR: reviewed-approved, PR: target-minor, PR: unreviewed

#5892 feat(module:back-top): add `nzDuration` property
  components/anchor/anchor.component.ts
  components/anchor/anchor.spec.ts
  components/back-top/back-top.component.ts
  components/back-top/doc/index.en-US.md
  components/back-top/doc/index.zh-CN.md
  components/core/services/scroll.spec.ts
  components/core/services/scroll.ts
Labels: PR: target-minor, PR: unreviewed

#5859 feat(module:descriptions): add extra property
  components/descriptions/demo/custom-size.ts
  components/descriptions/demo/module
  components/descriptions/descriptions.component.ts
  components/descriptions/doc/index.en-US.md
  components/descriptions/doc/index.zh-CN.md
Labels: PR: reviewed-approved, PR: target-minor, PR: unreviewed

#5916 feat(module:avatar): add avatar group component
  components/avatar/avatar-group.component.ts
  components/avatar/avatar.module.ts
  components/avatar/avatar.spec.ts
  components/avatar/demo/group.md
  components/avatar/demo/group.ts
  components/avatar/demo/module
  components/avatar/doc/index.en-US.md
  components/avatar/doc/index.zh-CN.md
Labels: PR: target-minor, PR: unreviewed

#5911 feat(module:typography): support custom icons and tooltips
  components/core/config/config.ts
  components/typography/demo/interactive.ts
  components/typography/doc/index.en-US.md
  components/typography/doc/index.zh-CN.md
  components/typography/text-copy.component.ts
  components/typography/text-edit.component.ts
  components/typography/typography.component.ts
  components/typography/typography.module.ts
  components/typography/typography.spec.ts
Labels: PR: target-minor, PR: unreviewed

#5896 feat(module:tooltip): add nzTooltipColor
  components/core/color/color.ts
  components/core/color/index.ts
  components/core/color/package.json
  components/core/color/public-api.ts
  components/tag/tag.component.ts
  components/tooltip/base.ts
  components/tooltip/demo/color.md
  components/tooltip/demo/color.ts
  components/tooltip/demo/module
  components/tooltip/doc/index.en-US.md
  components/tooltip/doc/index.zh-CN.md
  components/tooltip/tooltip.spec.ts
  components/tooltip/tooltip.ts
Labels: PR: reviewed-approved, PR: target-minor, PR: unreviewed

#5966 fix(module:form): explain status style not work with sync antd 4.7.2
  components/form/form-control.component.ts
Labels: PR: unreviewed

#5967 feat(module:form): support a fallback locale for validation tips
  components/form/demo/auto-tips.md
  components/form/demo/auto-tips.ts
  components/form/form-control.component.ts
  components/form/form-control.spec.ts
Labels: PR: unreviewed

#5957 feat(module:form): `nz-form-label` support `nzFormTooltip`
  components/core/config/config.ts
  components/form/demo/register.ts
  components/form/doc/index.en-US.md
  components/form/doc/index.zh-CN.md
  components/form/form-label.component.ts
  components/form/form-label.spec.ts
  components/form/form.directive.ts
  components/form/form.module.ts
Labels: PR: partially-approved

#5972 docs(module:icon): fix API docs
  components/icon/doc/index.zh-CN.md
Labels: PR: partially-approved

#5973 fix(module:select): the ESC keydown event not handled correctly
  components/select/select.component.ts
  components/select/select.spec.ts
Labels: PR: unreviewed

#5975 feat(module:date-picker): add `nzBorderless`
  components/date-picker/date-picker.component.spec.ts
  components/date-picker/date-picker.component.ts
  components/date-picker/date-range-popup.component.ts
  components/date-picker/demo/bordered.md
  components/date-picker/demo/bordered.ts
  components/date-picker/doc/index.en-US.md
  components/date-picker/doc/index.zh-CN.md
  components/date-picker/inner-popup.component.ts
  components/date-picker/lib/abstract-table.ts
  components/date-picker/picker.component.ts
Labels: PR: unreviewed

#5971 fix(module:upload): ensure i18n$ is defined on unsubscribe
  components/upload/upload.component.ts
Labels: PR: partially-approved

#5982 fix(module:table): fix typo nzOuterBordered
  components/table/doc/index.en-US.md
  components/table/doc/index.zh-CN.md
Labels: PR: reviewed-approved

#5990 fix(module:time-picker): hidden clear icon when disabled
  components/time-picker/time-picker.component.spec.ts
  components/time-picker/time-picker.component.ts
Labels: PR: reviewed-approved

#5978 fix(module:select): title not display
  components/select/option-item.component.ts
  components/select/select-top-control.component.ts
Labels: PR: unreviewed

#5959 docs(module:list): update the infinite load demo
  components/list/demo/infinite-load.ts
  components/list/demo/module
Labels: PR: unreviewed

#5861 feat(module:tooltip): enable custom placements
  components/popconfirm/doc/index.en-US.md
  components/popconfirm/doc/index.zh-CN.md
  components/popconfirm/popconfirm.ts
  components/popover/doc/index.en-US.md
  components/popover/doc/index.zh-CN.md
  components/popover/popover.ts
  components/tooltip/base.ts
  components/tooltip/demo/placement.ts
  components/tooltip/doc/index.en-US.md
  components/tooltip/doc/index.zh-CN.md
  components/tooltip/tooltip.ts
Labels: PR: target-minor, PR: unreviewed

#5993 chore(release): release 10.1.0
  CHANGELOG.md
  components/cascader/demo/basic.ts
  components/package.json
  components/version/version.ts
  docs/changelog.en-US.md
  docs/changelog.zh-CN.md
Labels: PR: partially-approved
