Repository NG-ZORRO/ng-zorro-antd, pull requests merged in 2020-05, with the labels that each got.

#5190 chore: bump @angular/cdk from 9.0.0 to 9.2.2
  package.json
  schematics/ng-update/index.ts
  schematics/ng-update/upgrade-data.ts
  schematics/ng-update/upgrade-rules/checks/calendar-input-rule.ts
  schematics/ng-update/upgrade-rules/checks/carousel-like-template-rule.ts
  schematics/ng-update/upgrade-rules/checks/dropdown-class-rule.ts
  schematics/ng-update/upgrade-rules/checks/dropdown-template-rule.ts
  schematics/ng-update/upgrade-rules/checks/form-template-rule.ts
  schematics/ng-update/upgrade-rules/checks/icon-template-rule.ts
  schematics/ng-update/upgrade-rules/checks/injection-token-rule.ts
  schematics/ng-update/upgrade-rules/checks/secondary-entry-points-rule.ts
  schematics/ng-update/upgrade-rules/checks/tooltip-like-template-rule.ts
Labels: PR: reviewed-approved

#5191 docs(module:select): add `nzBorderless`
  components/select/doc/index.en-US.md
  components/select/doc/index.zh-CN.md
Labels: PR: unreviewed

#5192 fix(module:*): fix dependeny components' file import
  components/anchor/style/entry.less
  components/auto-complete/style/entry.less
  components/calendar/style/entry.less
  components/card/style/entry.less
  components/cascader/style/entry.less
  components/code-editor/style/entry.less
  components/date-picker/style/entry.less
  components/dropdown/style/entry.less
  components/form/style/entry.less
  components/list/style/entry.less
  components/menu/style/entry.less
  components/modal/style/entry.less
  components/page-header/style/entry.less
  components/pagination/style/entry.less
  components/popconfirm/style/entry.less
  components/rate/style/entry.less
  components/select/style/entry.less
  components/slider/style/entry.less
  components/table/style/entry.less
  components/transfer/style/entry.less
  components/tree-select/style/entry.less
  components/upload/style/entry.less
Labels: PR: reviewed-approved

#5210 fix(module:schematics): invalid version will be added when the package already exists
  build-config.js
Labels: PR: reviewed-approved

#5175 fix(module:typography): ellipsis line measurement error
  components/core/util/text-measure.ts
  components/typography/typography.component.ts
Labels: PR: reviewed-approved

#4966 fix(module:breadcrumb): fix breadcrumb when Routes path=''
  components/breadcrumb/breadcrumb.component.ts
  components/breadcrumb/breadcrumb.spec.ts
Labels: PR: reviewed-approved

#5205 fix(module:upload): fix invalid preview image in picture card
  components/upload/upload-list.component.ts
Labels: PR: reviewed-approved

#5211 fix(module:alert): `nzNoAnimation` not work with the alert component
  components/alert/alert.component.ts
Labels: PR: reviewed-approved

#5212 build: fix `watch:site` task cannot work on Windows
  scripts/gulp/tasks/site.ts
Labels: PR: reviewed-approved

#5214 chore: add CODEOWNERS file
  .github/CODEOWNERS
  .github/nz-boot.yml
Labels: PR: reviewed-approved

#5218 docs: fix customize-theme typo
  docs/customize-theme.en-US.md
  docs/customize-theme.zh-CN.md
Labels: PR: reviewed-approved

#5243 docs: fix stackblitz error with @angular/cdk
  scripts/site/_site/doc/app/online-ide/online-ide.service.ts
Labels: PR: unreviewed

#5244 fix(module:dropdown): fix dropdown break SSR
  components/dropdown/dropdown.directive.ts
  components/dropdown/dropdown.module.ts
Labels: PR: unreviewed

#5246 fix(module:table): fix table expand in multiple thead tr
  components/table/src/table-style.service.ts
Labels: PR: unreviewed

#5233 fix(module:button): disabled not work with anchor
  components/button/button.component.ts
  components/button/button.spec.ts
  components/core/wave/nz-wave.directive.ts
Labels: PR: reviewed-approved

#5165 fix(module:auto-complete,drawer): cannot reopen when reuse route snapshots
  components/auto-complete/autocomplete-trigger.directive.ts
  components/core/config/config.ts
  components/drawer/doc/index.en-US.md
  components/drawer/doc/index.zh-CN.md
  components/drawer/drawer-options.ts
  components/drawer/drawer.component.ts
Labels: PR: reviewed-approved

#5161 fix(module:modal): modal cannot close after the host view destroyed
  components/core/config/config.ts
  components/modal/doc/index.en-US.md
  components/modal/doc/index.zh-CN.md
  components/modal/modal-container.ts
  components/modal/modal-ref.ts
  components/modal/modal.component.ts
  components/modal/modal.spec.ts
  components/modal/utils.ts
Labels: PR: partially-approved

#5239 docs: typo
  components/tag/doc/index.en-US.md
Labels: PR: unreviewed

#5228 fix(module:modal): global config cannot work with service mode
  components/badge/badge.component.ts
  components/modal/modal-config.ts
  components/modal/modal-confirm-container.component.ts
  components/modal/modal-container.component.ts
  components/modal/modal-container.ts
  components/modal/modal-ref.ts
  components/modal/modal-types.ts
  components/modal/modal.component.ts
  components/modal/modal.service.ts
  components/modal/modal.spec.ts
  components/modal/utils.ts
Labels: PR: reviewed-approved

#5254 chore(release): release 9.1.1
  CHANGELOG.md
  components/package.json
  components/version/version.ts
  docs/changelog.en-US.md
  docs/changelog.zh-CN.md
Labels: PR: reviewed-approved

#5266 fix(module:list): empty content is always rendered
  components/list/list.component.ts
Labels: PR: partially-approved

#5264 fix(module:select): option item not selected with falsy value
  components/select/option-item.component.ts
Labels: PR: reviewed-approved

#4940 feat(module:slider): add nzReverse property
  components/slider/demo/reverse.md
  components/slider/demo/reverse.ts
  components/slider/doc/index.en-US.md
  components/slider/doc/index.zh-CN.md
  components/slider/handle.component.ts
  components/slider/slider.component.ts
  components/slider/slider.spec.ts
  components/slider/track.component.ts
Labels: PR: reviewed-approved

#5267 revert: "feat(module:slider): add nzReverse property"
  components/slider/demo/reverse.md
  components/slider/demo/reverse.ts
  components/slider/doc/index.en-US.md
  components/slider/doc/index.zh-CN.md
  components/slider/handle.component.ts
  components/slider/slider.component.ts
  components/slider/slider.spec.ts
  components/slider/track.component.ts
Labels: PR: partially-approved

#5269 chore(release): release 9.1.2
  CHANGELOG.md
  components/package.json
  components/version/version.ts
  docs/changelog.en-US.md
  docs/changelog.zh-CN.md
Labels: PR: reviewed-approved

#5274 chore: clean the site files
  scripts/release/release-site.ts
Labels: PR: reviewed-approved

#5279 docs: fix typo
  docs/schematics.zh-CN.md
Labels: PR: reviewed-approved

#5277 fix(affix,anchor): wrong value is set when the initial value is non-number
  components/affix/affix.component.ts
  components/affix/affix.spec.ts
  components/anchor/anchor.component.ts
  components/core/util/convert.ts
Labels: PR: partially-approved

#5283 chore: update issue template config
  .github/ISSUE_TEMPLATE/----please-use-issue-helper---.md
  .github/ISSUE_TEMPLATE/----please-use-issue-helper-zh_CN---.md
  .github/ISSUE_TEMPLATE/config.yml
Labels: PR: reviewed-approved

#5289 docs: fix codesandbox tempalte
  scripts/site/_site/doc/app/online-ide/online-ide.service.ts
Labels: PR: reviewed-approved

#5306 docs: fix typo
  components/drawer/doc/index.en-US.md
Labels: PR: reviewed-approved

#5313 fix(module:modal): `nzAutofocus` doesn't work correctly
  components/modal/modal-confirm-container.component.ts
  components/modal/modal-footer.component.ts
  components/modal/modal.component.ts
  components/modal/utils.ts
Labels: PR: reviewed-approved

#5317 chore(module:upload): rename public interfaces
  components/upload/demo/avatar.ts
  components/upload/demo/basic.ts
  components/upload/demo/default-file-list.ts
  components/upload/demo/drag.ts
  components/upload/demo/file-list.ts
  components/upload/demo/picture-card.ts
  components/upload/demo/picture-style.ts
  components/upload/demo/preview-file.ts
  components/upload/demo/transform-file.ts
  components/upload/demo/upload-manually.ts
  components/upload/demo/upload-with-aliyun-oss.ts
  components/upload/doc/index.en-US.md
  components/upload/doc/index.zh-CN.md
  components/upload/interface.ts
  components/upload/upload-btn.component.ts
  components/upload/upload-list.component.ts
  components/upload/upload.component.ts
  components/upload/upload.spec.ts
Labels: PR: partially-approved
