Repository NG-ZORRO/ng-zorro-antd, pull requests merged in 2020-01, with the labels that each got.

#4608 fix(module:table): fix table data type
  bundlesize.config.json
  components/table/nz-table.component.ts
Labels: PR: unreviewed

#4532 fix(module: code-editor): fix wrong initialization with diff mode
  components/code-editor/nz-code-editor.component.ts
Labels: PR: unreviewed

#4625 docs(module:table): document sort properties
  components/table/doc/index.en-US.md
Labels: PR: reviewed-approved

#4611 feat(module:i18n): support for Armenian
  components/i18n/languages/calendar/hy_AM.ts
  components/i18n/languages/date-picker/hy_AM.ts
  components/i18n/languages/en_US.ts
  components/i18n/languages/hy_AM.ts
  components/i18n/languages/nl_NL.ts
  components/i18n/languages/pagination/hy_AM.ts
  components/i18n/languages/pt_BR.ts
  components/i18n/languages/sk_SK.ts
  components/i18n/languages/th_TH.ts
  components/i18n/languages/time-picker/hy_AM.ts
  components/i18n/languages/zh_CN.ts
  docs/i18n.en-US.md
  docs/i18n.zh-CN.md
Labels: PR: unreviewed

#4598 feat(module:progress): support TemplateRef for nzFormat
  components/progress/doc/index.en-US.md
  components/progress/doc/index.zh-CN.md
  components/progress/nz-progress.component.html
  components/progress/nz-progress.definitions.ts
  components/progress/nz-progress.module.ts
  components/progress/nz-progress.spec.ts
Labels: PR: unreviewed

#4584 refactor(module: resizable): change cursor styles
  components/resizable/nz-resizable.directive.ts
  components/resizable/style/index.less
Labels: PR: reviewed-approved

#4640 chore: update theme.less and package.json
  azure-pipelines.yml
  components/package.json
  components/progress/nz-progress.component.html
  components/select/nz-option-container.spec.ts
  components/style/v2-compatible-reset.less
  components/table/nz-th.spec.ts
  components/time-picker/nz-time-picker-panel.component.spec.ts
  package.json
  scripts/site/_site/doc/style/demo.less
  scripts/site/_site/doc/style/highlight.less
  scripts/site/_site/doc/style/markdown.less
  scripts/site/_site/doc/theme.less
  scripts/site/utils/capitalize-first-letter.js
Labels: PR: unreviewed

#4376 chore(module:carousel): remove vertical api
  components/carousel/nz-carousel.component.html
  components/carousel/nz-carousel.component.ts
  components/carousel/nz-carousel.spec.ts
Labels: PR: reviewed-approved, PR: target-major, PR: unreviewed, pre-release, 💔 Breaking Change

#4465 chore(module:empty): remove injection token
  components/empty/nz-embed-empty.component.ts
  components/empty/nz-empty.service.ts
  components/empty/nz-empty.spec.ts
Labels: PR: reviewed-approved, pre-release, 💔 Breaking Change

#4476 feat(module:tabs): add nzCanDeactivate hook
  components/core/util/observable.ts
  components/core/util/public-api.ts
  components/notification/nz-notification.component.html
  components/tabs/demo/guard.md
  components/tabs/demo/guard.ts
  components/tabs/demo/module
  components/tabs/doc/index.en-US.md
  components/tabs/doc/index.zh-CN.md
  components/tabs/nz-tabs.spec.ts
  components/tabs/nz-tabset.component.ts
  docs/recommendation.zh-CN.md
  scripts/site/_site/doc/app/app.component.html
Labels: PR: reviewed-approved, pre-release

#4609 fix(module:drawer): disable transition animation when placement change
  components/drawer/nz-drawer.component.html
  components/drawer/nz-drawer.component.ts
  components/drawer/nz-drawer.spec.ts
Labels: PR: reviewed-approved, pre-release

#4595 fix(module:table): `nzFilters` can is not null
  components/table/nz-th.component.ts
Labels: PR: reviewed-approved

#4404 chore(module:message,notification): remove old injection tokens
  components/message/nz-message-base.service.ts
  components/message/nz-message-config.ts
  components/message/nz-message-container.component.ts
  components/message/nz-message.module.ts
  components/message/nz-message.service.ts
  components/message/nz-message.spec.ts
  components/message/public-api.ts
  components/notification/demo/placement.ts
  components/notification/nz-notification-container.component.ts
  components/notification/nz-notification.module.ts
  components/notification/nz-notification.service.ts
  components/notification/nz-notification.spec.ts
  components/notification/public-api.ts
  docs/global-config.en-US.md
  docs/global-config.zh-CN.md
Labels: PR: reviewed-approved, PR: target-major, PR: unreviewed, pre-release, 💔 Breaking Change

#4467 feat(schematics): add v9 migration rules for icon and calendar
  schematics/ng-update/data/input-names.ts
  schematics/ng-update/index.ts
  schematics/ng-update/test-cases/v9/input-names-calendar.spec.ts
  schematics/ng-update/test-cases/v9/input-names-icon.spec.ts
  schematics/ng-update/upgrade-rules/checks/calendar-input-rule.ts
  schematics/ng-update/upgrade-rules/checks/icon-template-rule.ts
  schematics/utils/ng-update/elements.ts
Labels: PR: reviewed-approved, pre-release

#4601 chore(module:tree, tree-select): remove deprecated API
  components/tree-select/nz-tree-select.component.ts
  components/tree-select/nz-tree-select.spec.ts
  components/tree/nz-tree-node.component.ts
  components/tree/nz-tree.component.ts
  components/tree/nz-tree.spec.ts
Labels: PR: reviewed-approved, pre-release, 💔 Breaking Change

#4657 docs(module:resizable): add Stackblitz config
  components/code-editor/doc/index.en-US.md
  components/code-editor/doc/index.zh-CN.md
  components/resizable/doc/index.en-US.md
  components/resizable/doc/index.zh-CN.md
  package.json
  scripts/site/_site/doc/app/share/nz-codebox/stack-blitz.ts
Labels: PR: reviewed-approved

#4565 fix(module:cascader): fix not showing empty when there's no options
  components/cascader/nz-cascader.component.html
  components/cascader/nz-cascader.component.ts
  components/cascader/nz-cascader.service.ts
  components/core/overlay/overlay-position.ts
Labels: PR: reviewed-approved, pre-release

#4671 chore: add the pull request preview config
  .github/nz-boot.yml
Labels: PR: reviewed-approved

#4672 chore: fix bot config
  .github/nz-boot.yml
Labels: PR: reviewed-approved

#4674 feat(module:grid): support nzFlex and nzGutter array, deprecated nzType
  components/button/button-group.component.ts
  components/button/button.component.ts
  components/button/button.module.ts
  components/core/config/config.ts
  components/core/responsive/nz-breakpoint.ts
  components/core/transition-patch/transition-patch.spec.ts
  components/core/types/direction.ts
  components/core/wave/nz-wave.directive.ts
  components/descriptions/nz-descriptions.component.ts
  components/form/nz-form-control.component.ts
  components/form/nz-form-item.component.ts
  components/form/nz-form-label.component.ts
  components/form/nz-form.directive.ts
  components/form/nz-form.module.ts
  components/grid/col.directive.ts
  components/grid/demo/flex-align.md
  components/grid/demo/flex-align.ts
  components/grid/demo/flex-order.md
  components/grid/demo/flex-order.ts
  components/grid/demo/flex-stretch.md
  components/grid/demo/flex-stretch.ts
  components/grid/demo/flex.md
  components/grid/demo/flex.ts
  components/grid/demo/playground.ts
  components/grid/doc/index.en-US.md
  components/grid/doc/index.zh-CN.md
  components/grid/grid.module.ts
  components/grid/grid.spec.ts
  components/grid/nz-col.directive.ts
  components/grid/nz-grid.spec.ts
  components/grid/nz-row.directive.ts
  components/grid/public-api.ts
  components/grid/row.directive.ts
  components/layout/nz-sider.component.ts
  components/tsconfig.spec.json
Labels: PR: unreviewed

#4628 feat(module:tag): support status colors
  components/tag/demo/status.md
  components/tag/demo/status.ts
  components/tag/nz-tag.component.ts
  components/tag/nz-tag.spec.ts
Labels: PR: merge-ready, PR: reviewed-approved, PR: unreviewed

#4551 fix(module:auto-complete): close the panel when tapping scrollbar on Windows
  components/auto-complete/nz-autocomplete-trigger.directive.ts
  components/auto-complete/nz-autocomplete.spec.ts
Labels: PR: merge-ready, PR: reviewed-approved, PR: unreviewed

#4700 chore: bump Angular to 9.0.0-rc.9
  components/time-picker/nz-time-picker-panel.component.ts
  package.json
Labels: PR: reviewed-approved

#4739 fix(module:layout): fix responsive sider not work
  components/layout/sider.component.ts
  components/menu/demo/inline-collapsed.ts
  components/menu/menu.directive.ts
  components/menu/submenu.service.ts
Labels: PR: unreviewed
