Repository NG-ZORRO/ng-zorro-antd, pull requests merged in 2020-06, with the labels that each got.

#5358 build: optimize less compilation performance
  scripts/build/compile-styles.ts
Labels: PR: reviewed-approved

#5275 fix(module:badge): fix parent component use onpush nzCount not show
  components/badge/badge.component.ts
Labels: PR: reviewed-approved

#5323 fix(module:message): fix style not changed when property changes
  components/message/message-container.component.ts
Labels: PR: reviewed-approved

#5357 fix(module:date-picker): get input width before panel open
  components/date-picker/picker.component.ts
  components/date-picker/range-picker.component.spec.ts
Labels: PR: reviewed-approved

#5295 feat(module:calendar): support nzDisabledDate of calendar
  components/calendar/calendar.component.ts
  components/calendar/doc/index.en-US.md
  components/calendar/doc/index.zh-CN.md
Labels: PR: reviewed-approved

#5300 docs: fix Github API handling errors
  scripts/site/_site/doc/app/share/contributors-list/contributors-list.component.ts
Labels: PR: reviewed-approved

#5311 docs: update docs and fix demo
  components/list/demo/grid.md
  components/list/demo/grid.ts
  components/list/demo/resposive.md
  components/list/demo/resposive.ts
  components/list/list.component.ts
  components/modal/doc/index.en-US.md
  components/modal/doc/index.zh-CN.md
  docs/introduce.en-US.md
  docs/introduce.zh-CN.md
Labels: PR: partially-approved

#5380 build: fix theme generate error
  package.json
Labels: PR: reviewed-approved

#5241 fix(module:page-header): add compact style
  components/page-header/page-header.component.ts
Labels: PR: reviewed-approved

#5280 docs(module:tags): fix nz-tabset nzSelectChange event object field name
  components/tabs/doc/index.en-US.md
  components/tabs/doc/index.zh-CN.md
Labels: PR: partially-approved

#5240 fix(module:table): fix ExpressionChangedAfterError of nzRight and nzLeft
  components/table/src/cell/cell-fixed.directive.ts
Labels: PR: reviewed-approved

#5268 feat(module:slider): add nzReverse property
  components/slider/demo/reverse.md
  components/slider/demo/reverse.ts
  components/slider/doc/index.en-US.md
  components/slider/doc/index.zh-CN.md
  components/slider/handle.component.ts
  components/slider/slider.component.ts
  components/slider/slider.spec.ts
  components/slider/track.component.ts
Labels: PR: reviewed-approved

#5273 test(module:select): add test for selected class
  components/select/select.spec.ts
  components/table/src/table/thead.component.ts
Labels: PR: reviewed-approved

#5297 feat(module:typography): support `nzOnEllipsis` output
  components/typography/demo/ellipsis.ts
  components/typography/demo/interactive.md
  components/typography/demo/suffix.ts
  components/typography/doc/index.en-US.md
  components/typography/doc/index.zh-CN.md
  components/typography/typography.component.ts
  components/typography/typography.spec.ts
Labels: PR: reviewed-approved

#5394 docs(module:dropdown): fix component doc footer language & dropdown typo
  components/dropdown/doc/index.en-US.md
  components/dropdown/doc/index.zh-CN.md
  scripts/site/_site/doc/app/app.component.html
Labels: PR: reviewed-approved

#5382 fix(module:notification): fix issue 4787
  components/notification/notification-container.component.ts
  components/notification/notification.spec.ts
Labels: PR: partially-approved

#5315 fix(module:input): fix input missing attr disabled
  components/input/input.directive.ts
Labels: PR: reviewed-changes-requested

#5404 fix(module:button): fix button init loading status
  components/button/button.component.ts
  components/button/button.spec.ts
  package.json
Labels: PR: unreviewed

#5407 fix(module:select): fix group label search
  components/select/demo/optgroup.ts
  components/select/select.component.ts
Labels: PR: unreviewed

#5409 fix(module:menu): fix menu group ng-template error
  components/menu/menu-group.component.ts
Labels: PR: unreviewed

#5416 docs(module:typhography): add the import in documentation
  components/card/doc/index.en-US.md
  components/typography/doc/index.en-US.md
  components/typography/doc/index.zh-CN.md
Labels: PR: partially-approved

#5417 fix(module:table): fix table colspan & empty data style
  components/table/doc/index.en-US.md
  components/table/doc/index.zh-CN.md
  components/table/src/cell/th-measure.directive.ts
Labels: PR: unreviewed

#5419 fix(module:table): fix th nzChecked supersedes nzShowCheckbox
  components/table/src/cell/th-selection.component.ts
Labels: PR: unreviewed

#5420 fix(module:select): fix select autofocus behavior
  components/select/select.component.ts
Labels: PR: unreviewed

#5422 chore(module:code-editor): update the instance types
  components/code-editor/code-editor.component.ts
  components/code-editor/doc/index.en-US.md
  components/code-editor/doc/index.zh-CN.md
Labels: PR: unreviewed

#5423 feat(module:input-number): support inputmode
  components/input-number/doc/index.en-US.md
  components/input-number/doc/index.zh-CN.md
  components/input-number/input-number.component.ts
Labels: PR: unreviewed

#5424 fix(module:radio): fix radio focus
  components/radio/demo/radiogroup-more.ts
  components/radio/radio.component.ts
Labels: PR: unreviewed

#5425 fix(module:select): fix select nzCustomContent render
  components/select/option-container.component.ts
  components/select/option-item.component.ts
Labels: PR: unreviewed

#5316 fix(module:input): support reactive form disabled
  components/input/input.directive.ts
Labels: PR: reviewed-changes-requested

#5428 fix(module:input): fix reactive form disabled input-group style
  components/form/demo/register.ts
  components/input/input.directive.ts
Labels: PR: unreviewed

#5427 test: update the `createComponentBed` options type
  components/core/testing/componet-bed.ts
Labels: PR: unreviewed

#5430 docs(module:table): change table demo key
  components/table/demo/expand-children.ts
Labels: PR: unreviewed

#5429 fix(module:dropdown): fix dropdown disabled button
  components/dropdown/dropdown.directive.ts
Labels: PR: unreviewed

#5432 fix(module:select): fix tag mode wrong value with keydown
  components/select/select.component.ts
Labels: PR: unreviewed

#5433 fix(module:table): fix table sort default value change
  components/table/src/table-data.service.ts
Labels: PR: unreviewed

#5434 feat(module:select): support nzBorderless in global config
  components/core/config/config.ts
  components/select/doc/index.en-US.md
  components/select/doc/index.zh-CN.md
  components/select/select.component.ts
  components/table/doc/index.en-US.md
  components/table/doc/index.zh-CN.md
  components/table/src/table/table.component.ts
Labels: PR: unreviewed

#5377 fix(module:modal): modal will close when clicking the scrollbar
  components/modal/modal-confirm-container.component.ts
  components/modal/modal-container.component.ts
  components/modal/modal-container.ts
  components/modal/modal.spec.ts
Labels: PR: unreviewed

#5369 feat(module:table): support the generic type of data
  components/table/demo/basic.ts
  components/table/demo/virtual.ts
  components/table/src/table/table.component.ts
Labels: PR: reviewed-approved

#5332 fix(module:modal): some cases there is no changes detected
  components/modal/demo/service.ts
  components/modal/doc/index.en-US.md
  components/modal/doc/index.zh-CN.md
  components/modal/modal-confirm-container.component.ts
  components/modal/modal-container.component.ts
  components/modal/modal-container.ts
  components/modal/modal-ref.ts
  components/modal/modal.component.ts
  components/modal/modal.spec.ts
Labels: PR: unreviewed

#5436 fix(module:grid): fix gutter zero
  components/grid/col.directive.ts
  components/grid/row.directive.ts
Labels: PR: unreviewed

#5204 feat(module:upload): add `nzFileListRender` property
  components/upload/doc/index.en-US.md
  components/upload/doc/index.zh-CN.md
  components/upload/upload.component.html
  components/upload/upload.component.ts
  components/upload/upload.spec.ts
Labels: PR: unreviewed

#5314 build: deploy and publish in azure
  azure-pipelines.yml
  components/date-picker/doc/index.en-US.md
  components/date-picker/doc/index.zh-CN.md
  scripts/gulp/tasks/site.ts
Labels: PR: unreviewed

#5431 fix(module: tree): fix nzCheckStrictly and selected keys bug
  components/core/tree/nz-tree-base.service.ts
  components/tree-select/tree-select.component.ts
  components/tree/tree.component.ts
Labels: PR: partially-approved

#4959 refactor(module:core): refactor dropdown animation
  components/auto-complete/autocomplete-trigger.directive.ts
  components/auto-complete/autocomplete.component.ts
  components/auto-complete/autocomplete.spec.ts
  components/cascader/cascader.component.ts
  components/cascader/cascader.spec.ts
  components/core/animation/slide.ts
  components/core/types/drop-down-position.ts
  components/core/types/public-api.ts
  components/date-picker/date-picker.component.ts
  components/date-picker/picker.component.ts
  components/dropdown/context-menu.service.ts
  components/dropdown/dropdown-menu.component.ts
  components/dropdown/dropdown.directive.ts
  components/menu/submenu.component.ts
  components/select/select.component.ts
  components/time-picker/time-picker.component.ts
  components/tree-select/tree-select.component.ts
Labels: PR: partially-approved

#5437 fix(module:table): fix table nzWidth not work with scroll
  components/table/src/table-style.service.ts
  components/table/src/table/table.component.ts
Labels: PR: unreviewed

#5438 fix(module:drawer): don't prevent events when nzMask is false
  components/drawer/drawer.component.ts
  components/drawer/drawer.spec.ts
Labels: PR: reviewed-approved

#5439 chore(release): release 9.2.0
  CHANGELOG.md
  components/package.json
  components/version/version.ts
  docs/changelog.en-US.md
  docs/changelog.zh-CN.md
Labels: PR: unreviewed

#5445 fix(module:i18n): some locales compile error
  components/date-picker/date-picker.component.ts
  components/i18n/nz-i18n.interface.ts
  components/i18n/nz-i18n.service.spec.ts
Labels: PR: reviewed-approved

#5447 chore(release): release 9.2.1
  CHANGELOG.md
  components/package.json
  components/version/version.ts
  docs/changelog.en-US.md
  docs/changelog.zh-CN.md
Labels: PR: reviewed-approved

#5466 fix(module:datepicker): not open panel when input change
  components/date-picker/picker.component.ts
Labels: PR: reviewed-approved

#5462 fix(module:modal): throw an error when autofocus on the confirm-mode
  components/modal/modal-container.ts
  components/modal/modal.service.ts
  components/modal/modal.spec.ts
Labels: PR: reviewed-approved

#5467 chore(release): release 9.2.2
  CHANGELOG.md
  components/package.json
  components/version/version.ts
  docs/changelog.en-US.md
  docs/changelog.zh-CN.md
Labels: PR: unreviewed
