Repository NG-ZORRO/ng-zorro-antd, pull requests merged in 2020-09, with the labels that each got.

#5708 fix(module:tabs): fix clickable area of tab-link
  components/tabs/style/patch.less
  components/tabs/tabset.component.ts
Labels: PR: unreviewed

#5648 docs: add autofocus for overview page search-input
  scripts/site/_site/doc/app/components-overview/components-overview.component.ts
Labels: PR: unreviewed

#5750 chore: fix preview action
  .github/workflows/preview.yml
  angular.json
  azure-pipelines.yml
  components/affix/affix.component.ts
  components/code-editor/code-editor.component.ts
  components/i18n/date-helper.service.spec.ts
  components/rate/rate.component.ts
  components/skeleton/skeleton.component.ts
  components/table/demo/multiple-sorter.ts
  components/table/demo/reset-filter.ts
  components/table/demo/sort-filter.ts
  components/tabs/tab-nav-bar.component.ts
  components/tabs/tab-nav-operation.component.ts
  components/tooltip/base.ts
  components/tooltip/tooltip.ts
  components/transfer/transfer-list.component.ts
  components/transfer/transfer-search.component.ts
  components/tree/tree.component.ts
  package.json
  scripts/gulp/tasks/universal.ts
  scripts/prerender/prerender.ts
  scripts/prerender/route-paths.txt
  scripts/prerender/sitemap.ts
  scripts/prerender/static.paths.ts
  scripts/prerender/tsconfig.json
  scripts/site/_site/doc/app/app.server.module.ts
  scripts/site/_site/doc/app/header/github-button.component.ts
  scripts/site/_site/doc/app/share/contributors-list/contributors-list.component.ts
  scripts/site/_site/doc/app/share/github-btn/github-btn.component.ts
  scripts/site/_site/doc/main.server.ts
Labels: PR: unreviewed

#5749 feat(module:tabs): support (nzContextmenu) event
  components/tabs/demo/slide.ts
  components/tabs/doc/index.en-US.md
  components/tabs/doc/index.zh-CN.md
  components/tabs/interfaces.ts
  components/tabs/tab-link.directive.ts
  components/tabs/tab-nav-operation.component.ts
  components/tabs/tab.component.ts
  components/tabs/tabset.component.spec.ts
  components/tabs/tabset.component.ts
Labels: PR: unreviewed

#5729 fix(module:mention): not emit `(nzOnSearchChange)` when value is empty
  components/mention/mention.component.ts
  components/mention/nz-mention.spec.ts
Labels: PR: unreviewed

#5643 fix(module:date-picker): open the panel wrongly in IE11
  components/date-picker/date-picker.component.spec.ts
  components/date-picker/month-picker.component.spec.ts
  components/date-picker/picker.component.ts
  components/date-picker/range-picker.component.spec.ts
  components/date-picker/testing/util.ts
  components/date-picker/year-picker.component.spec.ts
Labels: PR: reviewed-approved

#5753 fix(module:date-picker): modify date-fns week-year format
  components/date-picker/date-picker.component.spec.ts
  components/date-picker/date-picker.component.ts
  components/date-picker/date-picker.service.ts
  components/date-picker/date-range-popup.component.ts
  components/date-picker/picker.component.ts
  components/date-picker/week-picker.component.spec.ts
  components/i18n/date-helper.service.spec.ts
Labels: PR: reviewed-approved

#5716 fix(module:select): cursor abnormal in nz-select with nzDisabled
  components/select/doc/index.zh-CN.md
  components/select/select.component.ts
Labels: PR: partially-approved

#5710 feat(module:skeleton): add nzRound prop and skeleton-element image
  components/skeleton/demo/children.md
  components/skeleton/demo/element.md
  components/skeleton/demo/element.ts
  components/skeleton/demo/list.md
  components/skeleton/demo/module
  components/skeleton/doc/index.en-US.md
  components/skeleton/doc/index.zh-CN.md
  components/skeleton/skeleton-element.component.ts
  components/skeleton/skeleton.component.ts
  components/skeleton/skeleton.module.ts
  components/skeleton/skeleton.spec.ts
  components/skeleton/style/index.less
Labels: PR: unreviewed

#5759 fix(module:tabs): tab-link cannot be disabled
  components/button/button.spec.ts
  components/tabs/style/patch.less
Labels: PR: unreviewed

#5761 fix(module:tree-select): not clear search value when dropdown close
  components/tree-select/tree-select.component.ts
  components/tree-select/tree-select.spec.ts
Labels: PR: unreviewed

#5760 feat(module:tree-select): support virtual scroll
  components/tree-select/demo/virtual-scroll.md
  components/tree-select/demo/virtual-scroll.ts
  components/tree-select/doc/index.en-US.md
  components/tree-select/doc/index.zh-CN.md
  components/tree-select/tree-select.component.ts
  components/tree/doc/index.en-US.md
  components/tree/doc/index.zh-CN.md
Labels: PR: unreviewed

#5355 feat(module:typography): support keyboard and link types
  components/typography/demo/basic.ts
  components/typography/demo/text.ts
Labels: PR: unreviewed

#5546 feat(module:drawer): support `[nzCloseIcon]`
  components/drawer/doc/index.en-US.md
  components/drawer/doc/index.zh-CN.md
  components/drawer/drawer.component.ts
  components/drawer/drawer.spec.ts
Labels: PR: unreviewed

#5299 feat(module:space): support `nzAlign`
  components/space/demo/align.md
  components/space/demo/align.ts
  components/space/doc/index.en-US.md
  components/space/doc/index.zh-CN.md
  components/space/public-api.ts
  components/space/space.component.spec.ts
  components/space/space.component.ts
  components/space/types.ts
Labels: PR: unreviewed

#5671 fix(module:carousel): support SSR
  components/carousel/carousel.component.ts
  components/carousel/strategies/base-strategy.ts
  components/carousel/strategies/transform-strategy.ts
Labels: PR: unreviewed

#5567 chore(module:core): enhance nzElementRef
  components/core/element-patch/element-patch.directive.ts
  components/core/element-patch/element-patch.spec.ts
Labels: PR: unreviewed

#5769 fix(module:tree-select): should be not clearable when disabled or unselected
  components/tree-select/tree-select.component.ts
  components/tree-select/tree-select.spec.ts
Labels: PR: unreviewed

#5768 build: update to typescript 4.0
  components/auto-complete/autocomplete.spec.ts
  components/breadcrumb/breadcrumb.spec.ts
  components/button/button.component.ts
  components/button/button.spec.ts
  components/calendar/calendar-header.spec.ts
  components/calendar/calendar.spec.ts
  components/cascader/cascader.spec.ts
  components/code-editor/code-editor.service.ts
  components/code-editor/code-editor.spec.ts
  components/comment/comment.spec.ts
  components/core/config/config.spec.ts
  components/core/tree/nz-tree-base.service.ts
  components/date-picker/date-picker.component.spec.ts
  components/date-picker/month-picker.component.spec.ts
  components/date-picker/range-picker.component.spec.ts
  components/date-picker/year-picker.component.spec.ts
  components/drawer/drawer.component.ts
  components/drawer/drawer.spec.ts
  components/empty/embed-empty.component.ts
  components/empty/empty.spec.ts
  components/icon/icon.spec.ts
  components/input/autosize.spec.ts
  components/input/input-group.spec.ts
  components/input/input.spec.ts
  components/layout/layout.spec.ts
  components/mention/nz-mention.spec.ts
  components/menu/menu.spec.ts
  components/menu/submenu.service.ts
  components/modal/modal-footer.directive.spec.ts
  components/modal/modal.service.ts
  components/page-header/page-header.spec.ts
  components/pagination/pagination.spec.ts
  components/skeleton/skeleton-element.component.ts
  components/space/space.component.spec.ts
  components/spin/spin.component.ts
  components/steps/steps.spec.ts
  components/table/src/table/thead.component.ts
  components/table/src/testing/table.spec.ts
  components/tabs/tab-nav-bar.component.ts
  components/time-picker/time-picker-panel.component.spec.ts
  components/time-picker/time-picker.component.spec.ts
  components/time-picker/time-value-accessor.directive.spec.ts
  components/tree-select/tree-select.spec.ts
  components/tsconfig.lib.json
  components/tsconfig.lib.prod.json
  components/upload/upload.component.ts
  components/upload/upload.spec.ts
  package.json
  schematics/utils/build-component.ts
  scripts/tslint-rules/coercionTypesRule.ts
  tsconfig.json
Labels: PR: unreviewed

#5772 docs: fix typo for global config page (en)
  docs/global-config.en-US.md
Labels: PR: reviewed-approved

#5774 refactor(module:upload): remove deprecated APIs for v10
  components/skeleton/skeleton.component.ts
  components/upload/interface.ts
  schematics/migration.json
  schematics/ng-update/data/class-names.ts
  schematics/ng-update/data/migrations/class-names.ts
  schematics/ng-update/index.ts
  schematics/ng-update/test-cases/v10/upload-deprecated.spec.ts
  schematics/utils/ng-update/module-specifiers.ts
Labels: PR: unreviewed

#5778 refactor(module:cascader): remove deprecated APIs for v10
  components/cascader/typings.ts
  schematics/ng-update/data/class-names.ts
Labels: PR: unreviewed

#5776 refactor(module:anchor): remove deprecated APIs for v10
  components/anchor/anchor.component.ts
  components/anchor/anchor.spec.ts
  schematics/ng-update/data/input-names.ts
Labels: PR: unreviewed

#5779 refactor(module:notification): remove deprecated APIs for v10
  components/notification/notification-container.component.ts
  components/notification/typings.ts
  schematics/ng-update/data/class-names.ts
  schematics/ng-update/data/property-names.ts
  schematics/ng-update/test-cases/v10/notification-deprecated.spec.ts
Labels: PR: unreviewed

#5781 feat(module:input): support borderless
  components/core/transition-patch/transition-patch.directive.ts
  components/divider/doc/index.en-US.md
  components/divider/doc/index.zh-CN.md
  components/input/demo/borderless.md
  components/input/demo/borderless.ts
  components/input/doc/index.en-US.md
  components/input/doc/index.zh-CN.md
  components/input/input.directive.ts
  package.json
  scripts/site/_site/doc/app/header/header.less
Labels: PR: unreviewed

#5784 fix(module:select): fix click arrow open
  components/select/select.component.ts
Labels: PR: unreviewed

#5785 fix(module:select): arrow icon can be used when not using single-select
  components/select/doc/index.en-US.md
  components/select/doc/index.zh-CN.md
  components/select/select.component.ts
Labels: PR: unreviewed

#5786 docs(module:date-picker): remove unneeded variable
  components/date-picker/demo/presetted-ranges.ts
Labels: PR: unreviewed

#5789 refactor(module:tree): remove deprecated APIs for v10
  components/core/tree/nz-tree-base-node.ts
  schematics/ng-update/data/property-names.ts
  schematics/ng-update/test-cases/v10/tree-deprecated.spec.ts
Labels: PR: unreviewed

#5794 feat(module:table): fix scroll bar displays always even unnecessary
  components/table/src/table/table-inner-scroll.component.ts
Labels: PR: unreviewed

#5795 feat(module:table): support nzOuterBordered
  components/table/demo/bordered.ts
  components/table/doc/index.en-US.md
  components/table/doc/index.zh-CN.md
  components/table/src/table/table.component.ts
  components/table/style/patch.less
Labels: PR: unreviewed

#5796 feat(module:card): support nzBorderless
  components/card/card.component.ts
  components/card/doc/index.en-US.md
  components/card/doc/index.zh-CN.md
  components/core/config/config.ts
Labels: PR: unreviewed

#5793 refactor(module:date-picker): remove deprecated APIs for v10
  components/date-picker/date-picker.component.spec.ts
  components/date-picker/date-picker.component.ts
  components/date-picker/month-picker.component.spec.ts
  components/date-picker/range-picker.component.spec.ts
  components/date-picker/year-picker.component.spec.ts
  components/i18n/convert-tokens.ts
  components/i18n/date-config.ts
  components/i18n/date-helper.service.spec.ts
  components/i18n/date-helper.service.ts
  components/i18n/public-api.ts
  schematics/ng-update/data/input-names.ts
  schematics/ng-update/index.ts
  schematics/ng-update/upgrade-rules/checks/date-fns-compatible-rule.ts
  schematics/ng-update/upgrade-rules/checks/global-config-rule.ts
  schematics/ng-update/upgrade-rules/checks/injection-token-rule.ts
Labels: PR: unreviewed

#5798 refactor(module:code-editor): remove deprecated APIs for v10
  components/code-editor/code-editor.service.ts
  components/code-editor/demo/config.ts
  components/code-editor/doc/index.en-US.md
  components/code-editor/doc/index.zh-CN.md
  components/code-editor/typings.ts
  schematics/ng-update/data/property-names.ts
  schematics/ng-update/test-cases/v9/deprecated-injection-tokens.spec.ts
  schematics/ng-update/upgrade-rules/checks/global-config-rule.ts
Labels: PR: unreviewed

#5797 docs(module:divider): fix typo
  components/divider/doc/index.en-US.md
Labels: PR: partially-approved

#5777 feat(module:date-picker): add open() and close()
  components/date-picker/date-picker.component.spec.ts
  components/date-picker/date-picker.component.ts
  components/date-picker/demo/start-end.md
  components/date-picker/demo/start-end.ts
  components/date-picker/doc/index.en-US.md
  components/date-picker/doc/index.zh-CN.md
  components/date-picker/picker.component.ts
Labels: PR: reviewed-approved

#5799 refactor(module:modal): change deprecated APIs for v10
  components/message/typings.ts
  components/modal/demo/service.ts
  components/modal/doc/index.zh-CN.md
  components/modal/modal-container.ts
  components/modal/modal-footer.component.ts
  components/modal/modal-ref.ts
  components/modal/modal-types.ts
  components/modal/modal.component.ts
  components/modal/utils.ts
Labels: PR: unreviewed

#5800 refactor(module:badge): add standalone mode
  components/badge/badge-sup.component.ts
  components/badge/badge.component.ts
  components/badge/badge.module.ts
  components/badge/badge.spec.ts
  components/badge/demo/change.ts
  components/badge/demo/colorful.ts
  components/badge/demo/module
  components/badge/demo/no-wrapper.md
  components/badge/demo/no-wrapper.ts
  components/badge/demo/ribbon.md
  components/badge/demo/ribbon.ts
  components/badge/doc/index.en-US.md
  components/badge/doc/index.zh-CN.md
  components/badge/ribbon.component.ts
  components/badge/style/entry.less
  components/badge/style/patch.less
  components/core/util/check.ts
Labels: PR: unreviewed

#5801 feat(module:tag): support icon in tag
  components/icon/icon.directive.ts
  components/tag/demo/icon.md
  components/tag/demo/icon.ts
  components/tag/demo/module
  components/tag/demo/status.ts
  components/tag/tag.component.ts
  components/tag/tag.spec.ts
Labels: PR: unreviewed

#5790 fix(module:date-picker): nzCalendarChange not work when clicking ok
  components/date-picker/date-picker.component.ts
  components/date-picker/date-range-popup.component.ts
  components/date-picker/demo/time.ts
  components/date-picker/range-picker.component.spec.ts
Labels: PR: reviewed-approved

#5791 refactor(module:date-picker): add new type for date-picker size
  components/date-picker/date-picker.component.ts
  components/date-picker/public-api.ts
Labels: PR: partially-approved

#5676 fix(module:progress): fix value not updated when is steps
  components/progress/progress.component.ts
  components/progress/progress.spec.ts
Labels: PR: unreviewed

#5541 chore(module:carousel): rename syncStrategy method and make-public
  components/carousel/carousel.component.ts
Labels: PR: unreviewed

#5502 chore(module:tooltip,*): remove deprecated API
  components/menu/demo/inline-collapsed.ts
  components/popconfirm/popconfirm.spec.ts
  components/popconfirm/popconfirm.ts
  components/popover/popover.spec.ts
  components/popover/popover.ts
  components/steps/demo/customized-progress-dot.ts
  components/tooltip/base.ts
  components/tooltip/tooltip.spec.ts
  components/tooltip/tooltip.ts
Labels: PR: unreviewed

#5814 fix(module:slider): fix reverse slider value with min and max
  components/slider/slider.component.ts
  components/slider/slider.spec.ts
Labels: PR: reviewed-approved

#5770 fix(module:time-picker): input value change not work
  components/core/time/public-api.ts
  components/core/time/time-parser.spec.ts
  components/core/time/time-parser.ts
  components/date-picker/picker.component.ts
  components/i18n/date-helper.service.spec.ts
  components/i18n/date-helper.service.ts
  components/time-picker/demo/use12-hours.ts
  components/time-picker/public-api.ts
  components/time-picker/time-picker-panel.component.ts
  components/time-picker/time-picker.component.spec.ts
  components/time-picker/time-picker.component.ts
  components/time-picker/time-picker.module.ts
  components/time-picker/time-value-accessor.directive.spec.ts
  components/time-picker/time-value-accessor.directive.ts
Labels: PR: unreviewed

#5817 refactor(module:tooltip, popover, popconfirm): change deprecated APIs for v10
  components/popconfirm/doc/index.zh-CN.md
  components/tooltip/base.ts
  schematics/ng-update/data/input-names.ts
  schematics/ng-update/data/output-names.ts
Labels: PR: unreviewed

#5818 docs: add component library users
  README-zh_CN.md
  README.md
  docs/introduce.en-US.md
  docs/introduce.zh-CN.md
  scripts/site/utils/marked.js
Labels: PR: unreviewed

#5824 chore: fix build pipeline
  azure-pipelines.yml
Labels: PR: unreviewed

#5812 refactor(module:date-picker): will not sort range date
  components/core/time/candy-date.spec.ts
  components/core/time/candy-date.ts
  components/date-picker/date-picker.service.ts
  components/date-picker/date-range-popup.component.ts
  components/date-picker/picker.component.ts
  components/date-picker/range-picker.component.spec.ts
Labels: PR: unreviewed

#5657 fix(module:select): display IME input completely
  components/select/select-search.component.ts
Labels: PR: unreviewed

#5827 docs: update version and pipes
  components/pipes/doc/index.en-US.md
  components/pipes/doc/index.zh-CN.md
  schematics/migration.json
  scripts/site/_site/doc/app/header/header.component.ts
  scripts/site/_site/doc/app/header/navigation.component.ts
  scripts/site/_site/doc/app/online-ide/files/ng-zorro-antd.module.ts
  scripts/site/_site/doc/app/online-ide/online-ide.service.ts
Labels: PR: partially-approved

#5830 chore(schematics): fix table rules
  CHANGELOG.md
  components/package.json
  schematics/ng-update/data/input-names.ts
  schematics/ng-update/test-cases/v9/secondary-entry-points.spec.ts
  schematics/ng-update/upgrade-rules/checks/secondary-entry-points-rule.ts
  schematics/ng-update/upgrade-rules/checks/table-template-rule.ts
Labels: PR: unreviewed

#5832 feat(module:date-picker): add range pickers of week, month, year
  components/core/time/candy-date.spec.ts
  components/core/time/candy-date.ts
  components/date-picker/date-picker.component.spec.ts
  components/date-picker/date-picker.component.ts
  components/date-picker/date-picker.service.ts
  components/date-picker/date-range-popup.component.ts
  components/date-picker/demo/basic.ts
  components/date-picker/demo/date-render.ts
  components/date-picker/demo/disabled-date.ts
  components/date-picker/demo/disabled.md
  components/date-picker/demo/disabled.ts
  components/date-picker/demo/extra-footer.ts
  components/date-picker/demo/format.md
  components/date-picker/demo/format.ts
  components/date-picker/demo/mode.md
  components/date-picker/demo/mode.ts
  components/date-picker/demo/presetted-ranges.ts
  components/date-picker/demo/range-picker.md
  components/date-picker/demo/range-picker.ts
  components/date-picker/demo/size.md
  components/date-picker/demo/size.ts
  components/date-picker/demo/time.md
  components/date-picker/demo/time.ts
  components/date-picker/doc/index.en-US.md
  components/date-picker/doc/index.zh-CN.md
  components/date-picker/inner-popup.component.ts
  components/date-picker/lib/abstract-table.ts
  components/date-picker/lib/date-table.component.ts
  components/date-picker/lib/decade-table.component.ts
  components/date-picker/lib/interface.ts
  components/date-picker/lib/month-table.component.ts
  components/date-picker/lib/year-table.component.ts
  components/date-picker/month-picker.component.spec.ts
  components/date-picker/month-picker.component.ts
  components/date-picker/picker.component.ts
  components/date-picker/range-picker.component.spec.ts
  components/date-picker/range-picker.component.ts
  components/date-picker/standard-types.ts
  components/date-picker/week-picker.component.spec.ts
  components/date-picker/week-picker.component.ts
  components/date-picker/year-picker.component.spec.ts
  components/date-picker/year-picker.component.ts
  components/form/demo/time-related-controls.ts
Labels: PR: unreviewed

#5837 fix(module:date-picker): today showing incorrectly
  components/date-picker/calendar-footer.component.ts
  components/date-picker/date-picker.component.ts
Labels: PR: unreviewed

#5835 chore(release): release 10.0.0
  CHANGELOG.md
  README-zh_CN.md
  README.md
  components/date-picker/demo/range-picker.ts
  components/date-picker/doc/index.en-US.md
  components/date-picker/doc/index.zh-CN.md
  components/package.json
  components/typography/demo/text.ts
  components/version/version.ts
  docs/changelog.en-US.md
  docs/changelog.zh-CN.md
  docs/introduce.en-US.md
  docs/introduce.zh-CN.md
  docs/migration-v10.en-US.md
  docs/migration-v10.zh-CN.md
  docs/migration-v9.en-US.md
  docs/migration-v9.zh-CN.md
  package.json
  scripts/site/_site/doc/app/components-overview/components-overview.component.ts
  scripts/site/_site/doc/style/dark.less
Labels: PR: unreviewed

#5840 build: fix site build
  angular.json
  package.json
  scripts/gulp/tasks/site.ts
  scripts/gulp/tasks/universal.ts
  scripts/prerender/sitemap.ts
Labels: PR: unreviewed

#5847 docs(changelog): Fixes missing closing backtick
  CHANGELOG.md
Labels: PR: unreviewed
