Repository NG-ZORRO/ng-zorro-antd, pull requests merged in 2020-12, with the labels that each got.

#6121 test(module:date-picker): fix test in month comparison
  components/core/time/candy-date.spec.ts
Labels: PR: unreviewed

#6123 fix(module:tree): fix indent line styles
  components/tree/tree-indent.component.ts
  components/tree/tree-node.component.ts
Labels: PR: unreviewed

#6125 fix(module:date-picker): display error in dynamic switching nzMode
  components/date-picker/date-picker.component.spec.ts
  components/date-picker/date-picker.component.ts
  components/date-picker/demo/bordered.md
  components/date-picker/demo/date-render.md
  components/date-picker/demo/disabled-date.md
  components/date-picker/demo/disabled.md
  components/date-picker/demo/format.md
  components/date-picker/demo/module
  components/date-picker/demo/presetted-ranges.md
  components/date-picker/demo/size.md
  components/date-picker/demo/start-end.md
  components/date-picker/demo/switch.md
  components/date-picker/demo/switch.ts
  components/date-picker/demo/time.md
  components/date-picker/picker.component.ts
Labels: PR: unreviewed

#6104 feat(module:input): textarea supports character count
  components/input/demo/module
  components/input/demo/textarea-with-character-count.md
  components/input/demo/textarea-with-character-count.ts
  components/input/doc/index.en-US.md
  components/input/doc/index.zh-CN.md
  components/input/input.module.ts
  components/input/public-api.ts
  components/input/textarea-count.component.ts
  components/input/textarea-count.spec.ts
Labels: PR: unreviewed

#6126 fix(module:date-picker): panel not update when changing to week
  components/date-picker/lib/abstract-table.ts
Labels: PR: unreviewed

#6129 docs(module:button): Add missing description for text button
  components/button/demo/basic.md
Labels: PR: reviewed-approved

#6128 chore(release): release 10.2.0
  CHANGELOG.md
  components/graph/doc/index.en-US.md
  components/graph/doc/index.zh-CN.md
  components/package.json
  components/version/version.ts
  docs/changelog.en-US.md
  docs/changelog.zh-CN.md
  scripts/site/utils/generate-routes.js
Labels: PR: reviewed-approved

#6145 build: fix type error
  scripts/gulp/util/task-helpers.ts
Labels: PR: unreviewed

#6133 fix(module:table): showPagination in ngIf when nzHideOnSinglePage
  components/table/src/table/table.component.ts
  components/table/src/testing/table.spec.ts
Labels: PR: partially-approved

#6137 fix(module:mention): scroll to focus when arrow up or down
  components/mention/mention.component.ts
Labels: PR: reviewed-approved

#6148 fix(module:select): activate first item or first selected item
  components/select/select.component.ts
Labels: PR: unreviewed

#6155 fix(module:description): fix label colon not working
  components/descriptions/descriptions.component.ts
Labels: PR: partially-approved

#6159 docs(module:auto-complete): add details for docs desc
  components/auto-complete/doc/index.zh-CN.md
Labels: PR: reviewed-approved

#6157 fix(module:modal): add nzOkDanger to avoid old button style
  components/button/button.component.ts
  components/modal/doc/index.en-US.md
  components/modal/doc/index.zh-CN.md
  components/modal/modal-footer.component.ts
  components/modal/modal-types.ts
  components/modal/modal.component.ts
  components/modal/utils.ts
Labels: PR: partially-approved

#6138 chore: sync upload component styles
  components/upload/demo/picture-card.ts
  components/upload/style/index.less
  components/upload/upload-list.component.html
  components/upload/upload-list.component.ts
  components/upload/upload.spec.ts
Labels: PR: unreviewed

#6168 chore: sync ant design style
  components/alert/alert.component.ts
  components/alert/style/index.less
  components/alert/style/rtl.less
  scripts/site/_site/doc/theme.less
Labels: PR: partially-approved

#6173 fix(module:tabs): keyboard events in extra areas trigger navigation
  components/tabs/tab-nav-bar.component.ts
  components/tabs/tabset.component.spec.ts
Labels: PR: unreviewed

#6171 chore(module:date-picker,time-picker): prevent losing input focus
  components/date-picker/date-range-popup.component.ts
  components/time-picker/time-picker-panel.component.ts
Labels: PR: unreviewed

#6169 fix(module:transfer): fix only filtered data in `nzRenderList`
  components/transfer/demo/tree-transfer.ts
  components/transfer/transfer-list.component.ts
Labels: PR: unreviewed

#6164 refactor(module: graph): refactor some apis and support to disable animations
  components/graph/core/minimap.ts
  components/graph/core/utils.ts
  components/graph/custom-graph-node.directive.ts
  components/graph/demo/customized.ts
  components/graph/demo/module
  components/graph/doc/index.en-US.md
  components/graph/doc/index.zh-CN.md
  components/graph/graph-defs.component.ts
  components/graph/graph-edge.component.ts
  components/graph/graph-edge.directive.ts
  components/graph/graph-minimap.component.ts
  components/graph/graph-node.component.ts
  components/graph/graph-node.directive.ts
  components/graph/graph-svg-container.component.ts
  components/graph/graph-zoom.directive.ts
  components/graph/graph.component.ts
  components/graph/graph.module.ts
  components/graph/interface.ts
  components/graph/public-api.ts
  components/graph/style/index.less
  components/graph/utils.ts
Labels: PR: unreviewed

#6165 feat: add aliyun theme
  components/ng-zorro-antd.aliyun.less
  components/style/aliyun.less
  components/style/themes/aliyun.less
  docs/customize-theme.en-US.md
  docs/customize-theme.zh-CN.md
  scripts/build/aliyun-vars.ts
  scripts/build/compile-styles.ts
  scripts/site/_site/doc/app/share/fixed-widgets/fixed-widgets.component.ts
  scripts/site/_site/doc/style/patch.less
  scripts/site/generate-theme.js
Labels: PR: unreviewed

#6185 chore(release): release 10.2.1
  CHANGELOG.md
  components/package.json
  components/version/version.ts
  docs/changelog.en-US.md
  docs/changelog.zh-CN.md
Labels: PR: reviewed-approved

#6186 docs: fix changelog
  CHANGELOG.md
  docs/changelog.en-US.md
  docs/changelog.zh-CN.md
Labels: PR: reviewed-approved

#6192 feat(module:graph): export nz-graph-zoom as nzGraphZoom
  components/graph/graph-zoom.directive.ts
Labels: PR: reviewed-approved

#6193 fix(module:button): only warn about deprecated value when used
  components/button/button.component.ts
Labels: PR: unreviewed

#6195 docs: add override i18n configuration
  docs/i18n.en-US.md
  docs/i18n.zh-CN.md
Labels: PR: reviewed-approved

#6160 feat(module:date-picker): add `nzShowNow`
  components/date-picker/calendar-footer.component.ts
  components/date-picker/date-picker.component.spec.ts
  components/date-picker/date-picker.component.ts
  components/date-picker/date-range-popup.component.ts
  components/date-picker/doc/index.en-US.md
  components/date-picker/doc/index.zh-CN.md
  components/date-picker/range-picker.component.spec.ts
Labels: PR: reviewed-approved

#6198 fix(module: tree): fix tree styles
  components/tree/tree-drop-indicator.component.ts
  components/tree/tree-node-title.component.ts
  components/tree/tree-node.component.ts
  components/tree/tree.module.ts
Labels: PR: unreviewed

#6154 feat(module:image): add image component
  components/components.less
  components/core/config/config.ts
  components/icon/icons.ts
  components/image/demo/basic.md
  components/image/demo/basic.ts
  components/image/demo/fallback.md
  components/image/demo/fallback.ts
  components/image/demo/module
  components/image/demo/placeholder.md
  components/image/demo/placeholder.ts
  components/image/demo/preview-group.md
  components/image/demo/preview-group.ts
  components/image/demo/service.md
  components/image/demo/service.ts
  components/image/doc/index.en-US.md
  components/image/doc/index.zh-CN.md
  components/image/image-config.ts
  components/image/image-group.component.ts
  components/image/image-preview-options.ts
  components/image/image-preview-ref.ts
  components/image/image-preview.component.ts
  components/image/image.directive.ts
  components/image/image.module.ts
  components/image/image.service.ts
  components/image/image.spec.ts
  components/image/index.ts
  components/image/package.json
  components/image/public-api.ts
  components/image/style/entry.less
  components/image/style/index.less
  components/image/style/patch.less
Labels: PR: merge-ready, PR: target-major, PR: unreviewed

#6069 fix(module:time-picker): placeholder not update with i18n changes
  components/back-top/back-top.component.ts
  components/card/card.component.ts
  components/checkbox/checkbox-group.component.ts
  components/checkbox/checkbox.component.ts
  components/collapse/collapse.component.ts
  components/drawer/drawer.spec.ts
  components/input-number/input-number.component.ts
  components/layout/layout.component.ts
  components/message/message-container.component.ts
  components/page-header/page-header.component.ts
  components/result/result.component.ts
  components/result/result.spec.ts
  components/select/select.component.ts
  components/time-picker/time-picker-panel.component.ts
  components/time-picker/time-picker.component.spec.ts
  components/time-picker/time-picker.component.ts
  components/tooltip/base.ts
  components/tooltip/demo/template.ts
  components/transfer/transfer.component.ts
  components/tree-select/tree-select.component.ts
  components/upload/upload-list.component.ts
  components/upload/upload.component.ts
Labels: PR: partially-approved

#6202 chore(module:date-picker): active bar not work
  components/date-picker/date-picker.component.ts
  components/date-picker/date-picker.service.ts
  components/date-picker/picker.component.ts
Labels: PR: unreviewed

#6205 fix(module:button): only warn about deprecated value when used (#6193)
  components/button/button.component.ts
Labels: PR: unreviewed

#6206 chore: fix ant-design v4.9.3 styles
  components/dropdown/style/index.less
  components/image/style/index.less
  components/menu/submenu-title.component.ts
  components/modal/style/modal.less
  components/style/mixins/modal-mask.less
Labels: PR: unreviewed

#6207 chore(release): release 10.2.2
  components/package.json
  components/version/version.ts
Labels: PR: unreviewed

#6161 feat(module:tree-view): add tree-view component
  components/components.less
  components/core/animation/collapse.ts
  components/style/patch.less
  components/tree-select/style/patch.less
  components/tree-select/tree-select.spec.ts
  components/tree-view/checkbox.ts
  components/tree-view/data-source.ts
  components/tree-view/demo/basic.md
  components/tree-view/demo/basic.ts
  components/tree-view/demo/checkbox.md
  components/tree-view/demo/checkbox.ts
  components/tree-view/demo/directory.md
  components/tree-view/demo/directory.ts
  components/tree-view/demo/dynamic.md
  components/tree-view/demo/dynamic.ts
  components/tree-view/demo/editable.md
  components/tree-view/demo/editable.ts
  components/tree-view/demo/line.md
  components/tree-view/demo/line.ts
  components/tree-view/demo/module
  components/tree-view/demo/search.md
  components/tree-view/demo/search.ts
  components/tree-view/demo/virtual-scroll.md
  components/tree-view/demo/virtual-scroll.ts
  components/tree-view/doc/index.en-US.md
  components/tree-view/doc/index.zh-CN.md
  components/tree-view/indent.ts
  components/tree-view/index.ts
  components/tree-view/node.ts
  components/tree-view/option.ts
  components/tree-view/outlet.ts
  components/tree-view/package.json
  components/tree-view/padding.ts
  components/tree-view/public-api.ts
  components/tree-view/style/entry.less
  components/tree-view/style/index.less
  components/tree-view/toggle.ts
  components/tree-view/tree-view.module.ts
  components/tree-view/tree-view.ts
  components/tree-view/tree-virtual-scroll-view.ts
  components/tree-view/tree.ts
  components/tree-view/utils.ts
  components/tree/demo/basic.ts
  components/tree/tree-node-checkbox.component.ts
  components/tree/tree-node.component.ts
  components/tree/tree.component.ts
  components/tree/tree.module.ts
  components/tree/tree.spec.ts
Labels: PR: merge-ready, PR: partially-approved, PR: unreviewed

#6190 chore: bump @angular/* from 10 to 11
  components/package.json
  components/version/version.ts
  package.json
  schematics/ng-add/index.spec.ts
  schematics/ng-add/index.ts
  schematics/ng-add/setup-project/add-animations-module.ts
  schematics/ng-add/setup-project/add-icon-assets.ts
  schematics/ng-add/setup-project/add-required-modules.ts
  schematics/ng-add/setup-project/hammerjs-import.ts
  schematics/ng-add/setup-project/index.ts
  schematics/ng-add/setup-project/register-locale.ts
  schematics/ng-add/setup-project/theming.ts
  schematics/ng-generate/blank/index.ts
  schematics/ng-generate/side-menu/index.ts
  schematics/ng-generate/topnav/index.ts
  schematics/ng-update/test-cases/config.ts
  schematics/ng-update/test-cases/v10/grid-deprecated.spec.ts
  schematics/utils/build-component.ts
  schematics/utils/project-style.ts
  schematics/utils/root-module.ts
Labels: PR: merge-ready, PR: target-major, PR: unreviewed

#6176 refactor(module:dropdown): move nzBackDrop deprecation to v12
  components/dropdown/dropdown.directive.spec.ts
  components/dropdown/dropdown.directive.ts
Labels: PR: merge-ready, PR: partially-approved, PR: target-major, PR: unreviewed

#6178 refactor(module:date-picker): remove deprecated APIs for v11
  components/date-picker/date-picker.component.spec.ts
  components/date-picker/date-picker.component.ts
  components/date-picker/standard-types.ts
Labels: PR: merge-ready, PR: partially-approved, PR: target-major, PR: unreviewed

#6179 refactor(module:tabs): remove deprecated APIs for v11
  components/tabs/tab-link.directive.ts
  components/tabs/tab.component.ts
  components/tabs/tabset.component.ts
  schematics/ng-update/index.ts
  schematics/ng-update/test-cases/v11/tabs-deprecated.spec.ts
  schematics/ng-update/upgrade-rules/checks/tabs-input-rule.ts
  schematics/ng-update/upgrade-rules/checks/tabs-output-rule.ts
  schematics/ng-update/upgrade-rules/checks/tabs-template-rule.ts
  schematics/utils/ng-update/elements.ts
Labels: PR: merge-ready, PR: partially-approved, PR: target-major, PR: unreviewed

#6214 fix(module:button): fix nzOkDanger confirm btn and demo
  components/modal/demo/confirm.ts
  components/modal/demo/service.ts
  components/modal/modal-confirm-container.component.ts
Labels: PR: reviewed-approved

#6203 feat(schematics): make ng-add schematics chainable
  schematics/ng-add/index.spec.ts
  schematics/ng-add/index.ts
  schematics/ng-add/schema.json
  schematics/ng-add/schema.ts
  schematics/ng-generate/side-menu/index.spec.ts
Labels: PR: reviewed-approved

#6218 chore: append issue url to v11 migration
  schematics/migration.json
Labels: PR: reviewed-approved

#6223 chore(module:icon): upgrade dependency version
  components/package.json
  package.json
Labels: PR: unreviewed

#6222 fix(module:select): fix XSS vulnerabilities
  components/select/select-search.component.ts
Labels: PR: unreviewed

#6225 build: support strict: true
  .gitignore
  components/cascader/cascader.component.ts
  components/core/config/config.service.ts
  components/core/wave/nz-wave-renderer.ts
  components/tsconfig.lib.json
  docs/direction.en-US.md
  docs/direction.zh-CN.md
  docs/i18n.en-US.md
  docs/i18n.zh-CN.md
  integration/angular-cli/angular.json
  integration/angular-cli/package.json
  integration/angular-cli/src/app/app.component.ts
  integration/angular-cli/src/app/app.module.ts
  integration/angular-cli/src/assets/.gitkeep
  integration/angular-cli/src/environments/environment.prod.ts
  integration/angular-cli/src/environments/environment.ts
  integration/angular-cli/src/index.html
  integration/angular-cli/src/main.ts
  integration/angular-cli/src/polyfills.ts
  integration/angular-cli/src/styles.css
  integration/angular-cli/src/tsconfig.app.json
  integration/angular-cli/src/typings.d.ts
  integration/angular-cli/tsconfig.json
  integration/rollup/package.json
  integration/rollup/rollup.config.js
  integration/rollup/src/app/app.component.ts
  integration/rollup/src/app/app.module.ts
  integration/rollup/src/assets/.gitkeep
  integration/rollup/src/environments/environment.prod.ts
  integration/rollup/src/environments/environment.ts
  integration/rollup/src/index.html
  integration/rollup/src/main.ts
  integration/rollup/src/polyfills.ts
  integration/rollup/src/styles.css
  integration/rollup/src/tsconfig.app.json
  integration/rollup/src/typings.d.ts
  integration/rollup/tsconfig.json
  integration/webpack/package.json
  integration/webpack/src/app/app.component.ts
  integration/webpack/src/app/app.module.ts
  integration/webpack/src/assets/.gitkeep
  integration/webpack/src/environments/environment.prod.ts
  integration/webpack/src/environments/environment.ts
  integration/webpack/src/index.html
  integration/webpack/src/main.ts
  integration/webpack/src/polyfills.ts
  integration/webpack/src/styles.css
  integration/webpack/src/tsconfig.app.json
  integration/webpack/src/typings.d.ts
  integration/webpack/tsconfig.json
  integration/webpack/webpack.config.js
  package.json
  scripts/site/_site/doc/app/app.module.ts
  setup-shared-libs.sh
  tsconfig-build.json
  tsconfig.json
Labels: PR: partially-approved

#6226 chore(schematics): change custom theme file content
  .gitignore
  schematics/ng-add/index.spec.ts
  schematics/utils/create-custom-theme.ts
  scripts/gulp/tasks/schematic.ts
  scripts/schematics/set-theme.ts
Labels: PR: unreviewed

#6227 fix(module:image): support rtl direction and fix props
  components/core/config/config.ts
  components/image/doc/index.en-US.md
  components/image/doc/index.zh-CN.md
  components/image/image-preview-options.ts
  components/image/image.directive.ts
  components/image/image.service.ts
  scripts/site/_site/doc/app/header/header.component.ts
Labels: PR: unreviewed

#6221 docs(module:list): Add property description for nz-list-item-meta-ava…
  components/list/doc/index.en-US.md
  components/list/doc/index.zh-CN.md
Labels: PR: reviewed-approved

#6232 fix(module:list): fix template rendering order
  components/list/list.component.ts
Labels: PR: reviewed-approved

#6228 feat(module: graph): support graph component under experimental
  components/graph/demo/customized.ts
  components/graph/doc/index.en-US.md
  components/graph/doc/index.zh-CN.md
  components/graph/graph-edge.component.ts
  components/graph/graph-minimap.component.ts
  components/graph/graph-node.component.ts
  components/graph/graph.component.ts
  components/graph/interface.ts
  components/graph/package.json
  components/graph/style/index.less
  package.json
Labels: PR: reviewed-approved

#6236 fix(module:i18n): fix Ukrainian i18n file
  components/i18n/languages/uk_UA.ts
Labels: PR: unreviewed

#6235 build: remove unused dep
  angular.json
  package.json
Labels: PR: unreviewed

#6234 docs: fix typo & missing part
  components/cascader/doc/index.zh-CN.md
  components/graph/doc/index.en-US.md
  components/image/doc/index.en-US.md
  components/image/doc/index.zh-CN.md
  components/modal/doc/index.en-US.md
  components/progress/doc/index.zh-CN.md
  components/table/doc/index.zh-CN.md
Labels: PR: partially-approved

#6237 refactor(module:graph): add specified directive to definition group node
  components/graph/demo/customized.ts
  components/graph/doc/index.en-US.md
  components/graph/doc/index.zh-CN.md
  components/graph/graph-group-node.directive.ts
  components/graph/graph.component.ts
  components/graph/graph.module.ts
  components/graph/package.json
  components/graph/public-api.ts
  package.json
Labels: PR: unreviewed

#6239 chore(release): release 11.0.0
  CHANGELOG.md
  README-zh_CN.md
  README.md
  components/package.json
  components/version/version.ts
  docs/changelog.en-US.md
  docs/changelog.zh-CN.md
  docs/introduce.en-US.md
  docs/introduce.zh-CN.md
  docs/migration-v10.en-US.md
  docs/migration-v10.zh-CN.md
  docs/migration-v11.en-US.md
  docs/migration-v11.zh-CN.md
  scripts/release/release.ts
  scripts/site/_site/doc/app/header/header.component.ts
Labels: PR: partially-approved

#6240 chore: add image component code owner
  .github/CODEOWNERS
Labels: PR: reviewed-approved

#6243 docs: fix doc ssr
  scripts/site/_site/doc/app/app.module.ts
Labels: PR: unreviewed

#6244 docs: update changelog and prerender router
  CHANGELOG.md
  angular.json
  docs/changelog.en-US.md
  docs/changelog.zh-CN.md
  docs/i18n.en-US.md
  docs/i18n.zh-CN.md
  package.json
  scripts/gulp/tasks/universal.ts
  scripts/prerender/route-paths.txt
Labels: PR: unreviewed

#6253 docs: fix PageHeader component document table format
  components/page-header/doc/index.en-US.md
  components/page-header/doc/index.zh-CN.md
Labels: PR: partially-approved

#6247 docs(module:images): fix table of NzImageService
  components/image/doc/index.en-US.md
Labels: PR: reviewed-approved

#6266 docs(module:form): fix template-syntax outer link
  components/form/demo/validate-reactive.md
  components/form/demo/validate-template.md
Labels: PR: reviewed-approved

#6273 fix(module:image): add missing imported modules
  components/image/image.module.ts
Labels: PR: reviewed-approved

#6278 fix(module:tabs): fix clickable area of the anchor element
  components/tabs/style/patch.less
Labels: PR: unreviewed

#6284 docs(module:modal): fix uncorrect 'NzModalService' markdown style
  components/modal/doc/index.en-US.md
  components/modal/doc/index.zh-CN.md
Labels: PR: reviewed-approved

#6280 fix(module:collapse): animation cannot be disabled
  components/collapse/collapse-panel.component.ts
  components/collapse/collapse.module.ts
  components/style/patch.less
Labels: PR: unreviewed

#6275 docs(module:page-header): remove remove extra parentheses
  components/page-header/doc/index.zh-CN.md
Labels: PR: reviewed-approved

#6281 docs: add new modules in DEMO module
  .github/CODEOWNERS
  .github/nz-boot.yml
  scripts/site/_site/doc/app/online-ide/files/ng-zorro-antd.module.ts
Labels: PR: unreviewed

#6262 fix(module:image): image fit content when drag released
  components/image/image-preview.component.ts
  components/image/image.spec.ts
  components/image/public-api.ts
  components/image/utils.ts
Labels: PR: reviewed-approved

#6257 chore(module:table): add nzHasBackdrop on nz-filter-trigger
  components/table/doc/index.en-US.md
  components/table/doc/index.zh-CN.md
  components/table/src/addon/filter-trigger.component.ts
Labels: PR: unreviewed

#6291 docs(module:image): add NzImageModule import guide
  components/image/doc/index.en-US.md
  components/image/doc/index.zh-CN.md
Labels: PR: unreviewed

#6294 fix(module:modal): mask is not set with the `nzZindex` property
  components/modal/modal-container.ts
  components/modal/modal.spec.ts
Labels: PR: unreviewed

#6269 fix(module:carousel): remove unused patch style
  components/carousel/style/patch.less
Labels: PR: unreviewed

#6006 fix(module:slider): fix slider style + reverse marks if reversed slider
  components/slider/demo/reverse.ts
  components/slider/marks.component.ts
  components/slider/slider.component.ts
  components/slider/slider.spec.ts
  components/slider/step.component.ts
Labels: PR: need-test, PR: partially-approved, PR: unreviewed

#6293 fix(module:tabs): index only changed by router event when nzLinkRouter
  components/tabs/tab-link.directive.ts
  components/tabs/tabset.component.spec.ts
  components/tabs/tabset.component.ts
Labels: PR: unreviewed

#6245 fix(module:select): change order for clear and arrow
  components/select/select.component.ts
Labels: PR: partially-approved

#6136 docs: fix demo table don't display the checkbox
  components/transfer/demo/table-transfer.ts
Labels: PR: partially-approved

#6298 fix(module:table): data is not updated when pagination exists
  components/table/src/table/table.component.ts
  components/table/src/testing/table.spec.ts
Labels: PR: unreviewed

#6297 chore(release): release 11.0.1
  CHANGELOG.md
  components/package.json
  components/version/version.ts
  docs/changelog.en-US.md
  docs/changelog.zh-CN.md
Labels: PR: unreviewed
