Repository NG-ZORRO/ng-zorro-antd, pull requests merged in 2021-01, with the labels that each got.

#6318 fix(module:carousel): throw error when changing rtl
  components/carousel/carousel.component.ts
  components/carousel/carousel.spec.ts
Labels: PR: partially-approved

#6309 chore: export `NZ_ICONS_USED_BY_ZORRO`
  components/icon/public-api.ts
Labels: PR: reviewed-approved

#6300 fix(module:image): add missing entry components
  components/image/image.module.ts
Labels: PR: reviewed-approved

#6330 chore(module:*): replace deprecated APIs without side effects
  components/anchor/anchor.spec.ts
  components/input/input-group.component.ts
  components/table/src/table/tr.directive.ts
Labels: PR: unreviewed

#6338 docs: fix typo
  components/pipes/doc/index.en-US.md
Labels: PR: unreviewed

#6325 fix(module:table): memory leak
  components/table/src/table/tr.directive.ts
Labels: PR: reviewed-approved

#6238 docs: refine docs of customize and switch themes
  docs/customize-theme.en-US.md
  docs/customize-theme.zh-CN.md
Labels: PR: unreviewed

#6336 fix(module:carousel): fix carousel under rtl
  components/carousel/carousel.component.ts
  components/carousel/strategies/base-strategy.ts
  components/carousel/strategies/transform-strategy.ts
Labels: PR: reviewed-approved

#6335 fix(module:date-picker): remove wrong warning message
  components/core/time/candy-date.ts
Labels: PR: reviewed-approved

#6348 fix(module:core): fix nzBordered typo (#6331)
  components/core/config/config.ts
Labels: PR: partially-approved

#6339 fix(module:date-picker): start and end month displays unreasonable
  components/core/time/candy-date.spec.ts
  components/core/time/candy-date.ts
  components/date-picker/calendar-footer.component.ts
  components/date-picker/date-picker.service.ts
  components/date-picker/date-range-popup.component.ts
  components/date-picker/doc/index.zh-CN.md
  components/date-picker/lib/date-table.component.ts
  components/date-picker/lib/decade-table.component.ts
  components/date-picker/lib/month-table.component.ts
  components/date-picker/lib/year-table.component.ts
  components/date-picker/picker.component.ts
  components/date-picker/range-picker.component.spec.ts
  components/time-picker/time-picker-panel.component.ts
Labels: PR: reviewed-approved

#6350 chore(release): release 11.0.2
  CHANGELOG.md
  components/package.json
  components/version/version.ts
  docs/changelog.en-US.md
  docs/changelog.zh-CN.md
Labels: PR: unreviewed

#6333 feat(module:modal): add nzCentered for modal
  components/modal/demo/position.md
  components/modal/demo/position.ts
  components/modal/doc/index.en-US.md
  components/modal/doc/index.zh-CN.md
  components/modal/modal-confirm-container.component.ts
  components/modal/modal-container.component.ts
  components/modal/modal-types.ts
  components/modal/modal.component.ts
  components/modal/modal.spec.ts
  components/modal/utils.ts
Labels: PR: reviewed-approved

#6283 feat(module:upload): support `NzUploadFile` parameter of `nzIconRender`
  components/upload/doc/index.en-US.md
  components/upload/doc/index.zh-CN.md
  components/upload/interface.ts
  components/upload/upload-list.component.html
  components/upload/upload-list.component.ts
  components/upload/upload.component.ts
Labels: PR: reviewed-approved

#6246 feat(module:date-picker): support nzId (#6242)
  components/date-picker/date-picker.component.ts
  components/date-picker/doc/index.en-US.md
  components/date-picker/doc/index.zh-CN.md
  components/date-picker/picker.component.ts
Labels: PR: partially-approved

#5986 feat(module:table): support nzPaginationType property
  components/table/demo/dynamic-settings.ts
  components/table/doc/index.en-US.md
  components/table/doc/index.zh-CN.md
  components/table/src/table.types.ts
  components/table/src/table/table.component.ts
Labels: PR: reviewed-approved

#6365 build: update to 11.1
  components/cascader/cascader.spec.ts
  components/modal/modal.spec.ts
  package.json
  schematics/utils/build-component.ts
  scripts/site/_site/doc/theme.less
Labels: PR: unreviewed

#6156 feat(module:table): add support for ReadonlyArray
  components/table/demo/dynamic-settings.ts
  components/table/demo/row-selection-and-operation.ts
  components/table/demo/row-selection-custom.ts
  components/table/src/table-data.service.ts
  components/table/src/table-style.service.ts
  components/table/src/table/table.component.ts
  components/table/src/table/tbody.component.ts
Labels: PR: unreviewed

#6369 fix(module:typography): edit area cannot get the content
  components/table/src/table/table-content.component.ts
  components/table/src/table/table-inner-default.component.ts
  components/table/src/table/table-inner-scroll.component.ts
  components/table/src/table/tr-measure.component.ts
  components/typography/text-edit.component.ts
  components/typography/typography.component.ts
  components/typography/typography.spec.ts
Labels: PR: partially-approved

#6367 fix(module:table): fix table nzBordered
  components/table/src/table/table-inner-scroll.component.ts
  package.json
  scripts/site/_site/doc/app/app.module.ts
  scripts/site/_site/doc/app/share/share.module.ts
Labels: PR: reviewed-approved

#6371 chore(release): release 11.1.0
  CHANGELOG.md
  components/package.json
  components/version/version.ts
  docs/changelog.en-US.md
  docs/changelog.zh-CN.md
Labels: PR: unreviewed

#6386 fix(module:tree-view): correct API typo
  components/tree-view/doc/index.en-US.md
  components/tree-view/doc/index.zh-CN.md
  components/tree-view/tree-virtual-scroll-view.ts
Labels: PR: reviewed-approved
