Repository NG-ZORRO/ng-zorro-antd, pull requests merged in 2021-06, with the labels that each got.

#6733 docs(module:cascader): use `nzModalContent` instead
  components/cascader/demo/modal.ts
Labels: PR: reviewed-approved

#6729 fix(module:slider): processing value zero correctly
  components/slider/slider.component.ts
  components/slider/slider.spec.ts
Labels: PR: reviewed-approved

#6717 fix(module:badge): enable nzNoAnimation support
  components/badge/badge-sup.component.ts
  components/badge/badge.component.ts
  components/badge/badge.module.ts
  components/badge/badge.spec.ts
  components/style/patch.less
Labels: PR: reviewed-approved

#6706 fix(module:tabs): fix `nzCentered` not working
  components/tabs/demo/card-top.md
  components/tabs/demo/card.md
  components/tabs/demo/centered.md
  components/tabs/demo/centered.ts
  components/tabs/demo/custom-add-trigger.md
  components/tabs/demo/editable-card.md
  components/tabs/demo/extra.md
  components/tabs/demo/guard.md
  components/tabs/demo/icon.md
  components/tabs/demo/lazy.md
  components/tabs/demo/link-router.md
  components/tabs/demo/position.md
  components/tabs/demo/size.md
  components/tabs/demo/slide.md
  components/tabs/style/index.less
  components/tabs/style/position.less
Labels: PR: partially-approved

#6686 build: deprecate `whitelistedNonPeerDependencies`
  components/core/resize-observers/package.json
  components/date-picker/package.json
  components/icon/package.json
  components/ng-package.json
Labels: PR: partially-approved

#6685 fix(module:autocomplete): no reset status when no matching inputs
  components/auto-complete/autocomplete-trigger.directive.ts
  components/auto-complete/autocomplete.component.ts
  components/auto-complete/autocomplete.spec.ts
Labels: PR: unreviewed

#6736 fix(module:tree-view): node indent line without mark change check
  components/tree-view/demo/editable.ts
  components/tree-view/indent.ts
Labels: PR: unreviewed

#6738 fix(module:tag): missing styles on view engine
  components/core/color/color.ts
  components/tag/tag.component.ts
Labels: PR: unreviewed

#6662 docs: Typo
  components/select/doc/index.en-US.md
Labels: PR: unreviewed

#6741 docs(module:cascader): make filter make more sense
  components/cascader/doc/index.en-US.md
  components/cascader/doc/index.zh-CN.md
Labels: PR: reviewed-approved

#6742 chore: update route-paths and CODEOWNERS files
  .github/CODEOWNERS
  scripts/prerender/route-paths.txt
Labels: PR: unreviewed

#6739 chore(release): release 11.4.2
  CHANGELOG.md
  components/package.json
  components/version/version.ts
  docs/changelog.en-US.md
  docs/changelog.zh-CN.md
Labels: PR: unreviewed

#6690 build: upgrade husky from 4.3.6 to 6.0.0
  .husky/.gitignore
  .husky/commit-msg
  .husky/pre-commit
  package.json
Labels: PR: reviewed-approved

#6743 chore: bump @angular/* to v12
  angular.json
  components/core/resize-observers/resize-observers.service.ts
  components/karma.conf.js
  components/package.json
  components/polyfills.ts
  components/space/space.component.ts
  components/test.ts
  docs/introduce.en-US.md
  docs/introduce.zh-CN.md
  docs/migration-v12.en-US.md
  docs/migration-v12.zh-CN.md
  package.json
  schematics/ng-add/schema.json
  schematics/ng-component/schema.json
  schematics/ng-generate/blank/schema.json
  schematics/ng-generate/side-menu/schema.json
  schematics/ng-generate/topnav/schema.json
  schematics/utils/build-component.ts
  scripts/prerender/tsconfig.json
  scripts/site/_site/doc/app/online-ide/files/polyfill.ts
  scripts/site/_site/doc/environments/environment.ts
  scripts/site/_site/doc/polyfills.ts
  scripts/site/_site/iframe/environments/environment.ts
  scripts/site/_site/iframe/polyfills.ts
  tsconfig.json
Labels: PR: unreviewed

#6745 chore: update config files
  angular.json
  schematics/collection.json
  schematics/migration.json
  schematics/ng-update/index.ts
  scripts/gulp/tasks/library.ts
Labels: PR: unreviewed

#6759 refactor(module:table): fix `TrackByFunction` type infer
  components/graph/graph.component.ts
  components/table/demo/reset-filter.ts
  components/table/demo/sort-filter.ts
  components/table/doc/index.en-US.md
  components/table/doc/index.zh-CN.md
  components/table/src/cell/th-addon.component.ts
  components/table/src/table-data.service.ts
  components/table/src/table.types.ts
  components/table/src/table/table-inner-scroll.component.ts
  components/table/src/table/table-virtual-scroll.directive.ts
  components/table/src/table/table.component.ts
  components/table/src/table/thead.component.ts
  components/table/src/testing/table.spec.ts
  components/table/src/testing/th.spec.ts
  components/transfer/demo/table-transfer.ts
Labels: PR: unreviewed

#6757 chore: add tsc type check for pre-commit
  .husky/pre-commit
  components/grid/grid.spec.ts
  components/icon/page/index.ts
  components/tsconfig.json
  package.json
Labels: PR: partially-approved

#6761 fix(module:cascader): add nzClear functionality to cascader
  components/cascader/cascader.component.ts
  components/cascader/cascader.service.ts
  components/cascader/cascader.spec.ts
Labels: PR: reviewed-approved

#6746 refactor(module:button): remove deprecated APIs for v12
  components/button/button.component.ts
  components/button/button.spec.ts
  schematics/utils/ng-update/elements.ts
Labels: PR: target-major, PR: unreviewed

#6747 refactor(module:modal, drawer): remove deprecated APIs for v12
  components/drawer/drawer.component.ts
  components/modal/modal.component.ts
  components/modal/utils.ts
Labels: PR: target-major, PR: unreviewed

#6752 test(module:tabs): remove deprecated APIs test cases
  components/tabs/tabset.component.spec.ts
Labels: PR: unreviewed

#6754 refactor(module:tree-view): remove deprecated APIs for v12
  components/tree-view/tree-virtual-scroll-view.ts
  schematics/ng-update/data/input-names.ts
Labels: PR: target-major, PR: unreviewed

#6762 refactor(module:dropdown, table): deprecate `nzHasBackdrop` input
  components/dropdown/dropdown.directive.spec.ts
  components/dropdown/dropdown.directive.ts
  components/table/src/addon/filter-trigger.component.ts
Labels: PR: unreviewed

#6602 fix(module:time-picker): close time-picker after tabbing out
  components/time-picker/time-picker.component.spec.ts
  components/time-picker/time-picker.component.ts
Labels: PR: reviewed-approved

#6744 fix(module: pagination): pagination in form will trigger submit
  components/pagination/pagination-item.component.ts
Labels: PR: partially-approved

#6753 refactor(module:space): remove deprecated APIs for v12
  components/space/public-api.ts
  components/space/space-item.component.ts
  components/space/space.component.spec.ts
  components/space/space.component.ts
  components/space/space.module.ts
Labels: PR: target-major, PR: unreviewed

#6765 test(module:time-picker): remove duplicated import identifiers
  components/time-picker/time-picker.component.spec.ts
Labels: PR: unreviewed

#6755 build: upgrade to node 14
  .nvmrc
  azure-pipelines.yml
  package.json
Labels: PR: unreviewed

#6256 feat(module:popconfirm): support nzAutoFocus
  components/core/config/config.ts
  components/popconfirm/doc/index.en-US.md
  components/popconfirm/doc/index.zh-CN.md
  components/popconfirm/popconfirm.module.ts
  components/popconfirm/popconfirm.spec.ts
  components/popconfirm/popconfirm.ts
  components/tooltip/base.ts
Labels: PR: reviewed-approved

#6132 feat(module:steps): steps support circular progress bar
  components/progress/typings.ts
  components/steps/demo/progress.md
  components/steps/demo/progress.ts
  components/steps/doc/index.en-US.md
  components/steps/doc/index.zh-CN.md
  components/steps/step.component.ts
  components/steps/steps.component.ts
  components/steps/steps.module.ts
Labels: PR: partially-approved

#6771 fix(module:tree): stop drop event change url in firefox
  components/tree/tree-node.component.ts
Labels: PR: partially-approved

#6772 docs(module:menu): correct the `Layout` demo link
  components/menu/demo/inline-collapsed.md
Labels: PR: partially-approved

#6750 docs(module:carousel): add demo to use custom transition strategy
  .husky/pre-commit
  components/carousel/carousel.component.ts
  components/carousel/carousel.spec.ts
  components/carousel/demo/autoplay.ts
  components/carousel/demo/basic.ts
  components/carousel/demo/custom.md
  components/carousel/demo/custom.ts
  components/carousel/demo/fade.ts
  components/carousel/demo/position.ts
  components/carousel/public-api.ts
  components/carousel/strategies/experimental/flip-strategy.ts
  components/carousel/strategies/experimental/transform-no-loop-strategy.ts
  components/carousel/strategies/opacity-strategy.ts
  components/carousel/strategies/transform-strategy.ts
  package.json
Labels: PR: partially-approved

#6776 fix(module:typography): single line ellipsis style
  components/typography/style/index.less
  components/typography/typography.component.ts
Labels: PR: unreviewed

#6779 chore(module:table): sync filter style
  components/style/core/base.less
  components/style/core/global.less
  components/style/mixins/modal-mask.less
  components/style/themes/dark.less
  components/style/themes/default.less
  components/table/src/addon/filter-trigger.component.ts
  components/table/src/addon/filter.component.ts
  components/table/src/addon/sorters.component.ts
  components/table/style/bordered.less
  components/table/style/index.less
  components/table/style/patch.less
  components/table/style/size.less
Labels: PR: unreviewed

#6780 fix(pagination): add cdr check while page index change
  components/pagination/pagination.component.ts
Labels: PR: partially-approved

#6787 feat(module:rate): support customize character
  components/rate/demo/customize.md
  components/rate/demo/customize.ts
  components/rate/rate-item.component.ts
  components/rate/rate.component.ts
  components/rate/rate.spec.ts
Labels: PR: reviewed-approved, PR: target-minor

#6804 chore: bump angular from 12.0 to 12.1
  .husky/pre-commit
  angular.json
  azure-pipelines.yml
  components/list/demo/infinite-load.ts
  components/list/demo/loadmore.ts
  components/page-header/demo/responsive.ts
  components/select/demo/scroll-load.ts
  components/select/demo/select-users.ts
  components/steps/demo/progress.ts
  components/table/demo/ajax.ts
  package.json
  scripts/gulp/tasks/site.ts
  scripts/prerender/ngsw-config.ts
  scripts/prerender/route-paths.txt
  scripts/prerender/sitemap.ts
  scripts/release-helper.sh
  scripts/site/_site/doc/app/header/join-tip.components.ts
Labels: PR: unreviewed
