Repository NG-ZORRO/ng-zorro-antd, pull requests merged in 2021-04, with the labels that each got.

#6538 feat(module:select): support number as label (#6535)
  components/select/doc/index.en-US.md
  components/select/doc/index.zh-CN.md
  components/select/option-group.component.ts
  components/select/option-item-group.component.ts
  components/select/option-item.component.ts
  components/select/option.component.ts
  components/select/select-item.component.ts
  components/select/select.component.ts
  components/select/select.spec.ts
  components/select/select.types.ts
Labels: PR: reviewed-approved

#6547 fix(module: table): fix sort and filter when nzFrontPagination is false
  components/table/src/table-data.service.ts
Labels: PR: reviewed-approved

#6561 fix(module:space): fix deprecated warning for nz-space-item (#6549)
  components/space/space.component.ts
Labels: PR: unreviewed

#6571 fix(module:date-picker): close date-picker after tabbing out
  components/date-picker/date-picker.component.spec.ts
  components/date-picker/date-picker.component.ts
  components/date-picker/picker.component.ts
  components/date-picker/range-picker.component.spec.ts
Labels: PR: reviewed-approved

#6563 fix(module:tabs): make remove icon of nz-tab-link clickable
  components/tabs/style/patch.less
Labels: PR: partially-approved

#6580 fix(module:tabs): not scrolling to the selected tab after init
  components/tabs/demo/slide.ts
  components/tabs/tab-nav-bar.component.ts
Labels: PR: unreviewed

#6581 fix(module:drawer): content is attached before the drawer is opened
  components/drawer/drawer.component.ts
  components/drawer/drawer.spec.ts
Labels: PR: unreviewed

#6583 chore(release): release 11.4.0
  CHANGELOG.md
  components/package.json
  components/version/version.ts
  docs/changelog.en-US.md
  docs/changelog.zh-CN.md
Labels: PR: unreviewed

#6574 fix(module:tree-select): rely on destroy$ to clear subscriptions
  components/tree-select/tree-select.component.ts
Labels: PR: reviewed-approved

#6585 chore: fix changelog typo
  docs/changelog.zh-CN.md
Labels: PR: unreviewed

#6589 fix(module:i18n): added property missing in ka_GE
  components/i18n/languages/ka_GE.ts
Labels: PR: unreviewed

#6598 docs(module: table): change to nzPopconfirmTitle
  components/table/demo/edit-row.ts
Labels: PR: unreviewed

#6597 docs(module:image,date-picker,skeleton): remove 'nz-space-item'
  components/date-picker/demo/switch.ts
  components/image/demo/placeholder.ts
  components/skeleton/demo/element.ts
Labels: PR: unreviewed

#6569 fix: create image using document method to avoid ReferenceError in SSR
  components/graph/core/minimap.ts
  components/image/image.directive.ts
  components/upload/upload-list.component.ts
  components/upload/upload.spec.ts
Labels: PR: partially-approved

#6596 fix(module:date-picker): click outside not change value
  components/date-picker/date-picker.component.spec.ts
  components/date-picker/date-picker.component.ts
  components/date-picker/month-picker.component.spec.ts
  components/date-picker/picker.component.ts
  components/date-picker/range-picker.component.spec.ts
  components/date-picker/year-picker.component.spec.ts
Labels: PR: unreviewed

#6606 fix(module:typography): add type="button" attribute to button element…
  components/typography/text-copy.component.ts
Labels: PR: reviewed-approved

#6603 docs: delete repeated theme import
  scripts/site/_site/doc/styles.less
  scripts/site/_site/doc/theme.less
Labels: PR: reviewed-approved

#6604 fix(module:date-picker): time picker panel not scroll at first time
  components/date-picker/date-picker.component.spec.ts
  components/date-picker/date-picker.component.ts
  components/date-picker/date-picker.service.ts
  components/date-picker/date-range-popup.component.ts
  components/date-picker/month-picker.component.spec.ts
  components/date-picker/picker.component.ts
  components/date-picker/range-picker.component.spec.ts
  components/date-picker/year-picker.component.spec.ts
Labels: PR: unreviewed

#6619 docs(module:message,notification): add a link to `global-config`
  components/message/doc/index.en-US.md
  components/message/doc/index.zh-CN.md
  components/notification/doc/index.en-US.md
  components/notification/doc/index.zh-CN.md
Labels: PR: partially-approved

#6616 fix(module:date-picker): not switch month panel when range is same month
  components/core/time/candy-date.spec.ts
  components/core/time/candy-date.ts
Labels: PR: unreviewed

#6621 docs(changelog): fix typo
  docs/changelog.zh-CN.md
Labels: PR: reviewed-approved

#6623 chore: update animation classname
  components/image/image-config.ts
  components/image/image.spec.ts
  components/modal/modal-config.ts
  components/modal/modal.spec.ts
Labels: PR: unreviewed

#6627 docs: add FAQ of date picker format
  components/date-picker/doc/index.en-US.md
  components/date-picker/doc/index.zh-CN.md
Labels: PR: unreviewed

#6612 fix(module:slider): fix range slider not working for arrow keys
  components/slider/slider.component.ts
  components/slider/slider.spec.ts
Labels: PR: reviewed-approved

#6615 fix(module:graph): fix edge default style and wrong toggling group nodes
  components/graph/data-source/graph-data-source.ts
  components/graph/graph-edge.component.ts
  components/graph/graph.component.ts
  components/graph/interface.ts
  package.json
Labels: PR: reviewed-approved

#6636 fix(module:graph): fix wrong default edge style
  components/graph/doc/index.en-US.md
  components/graph/doc/index.zh-CN.md
  components/graph/graph-edge.component.ts
  components/graph/graph.component.ts
Labels: PR: unreviewed

#6640 docs: update customize theme
  docs/customize-theme.en-US.md
  docs/customize-theme.zh-CN.md
Labels: PR: reviewed-approved

#6630 chore(release): release 11.4.1
  CHANGELOG.md
  components/package.json
  components/version/version.ts
  docs/changelog.en-US.md
  docs/changelog.zh-CN.md
Labels: PR: reviewed-approved

#6562 fix: focus monitor cleanup
  components/checkbox/checkbox-group.component.ts
  components/checkbox/checkbox.component.ts
  components/input-number/input-number.component.ts
  components/input/input-group.component.ts
  components/radio/radio.component.ts
  components/select/select.component.ts
  components/switch/switch.component.ts
Labels: PR: partially-approved

#6649 fix(module:modal): `nzVisible` not updated when implicitly closed
  components/modal/modal-ref.ts
  components/modal/modal.component.ts
  components/modal/modal.spec.ts
Labels: PR: reviewed-approved
