Repository NG-ZORRO/ng-zorro-antd, pull requests merged in 2021-07, with the labels that each got.

#6814 fix(module:date-picker): nz-range-picker support nzId
  components/date-picker/date-picker.component.ts
  components/date-picker/doc/index.en-US.md
  components/date-picker/doc/index.zh-CN.md
Labels: PR: partially-approved

#6813 feat(module:checkbox): add nzId input
  components/checkbox/checkbox.component.ts
  components/checkbox/doc/index.en-US.md
  components/checkbox/doc/index.zh-CN.md
Labels: PR: partially-approved

#6786 fix(module:select): focus input when selector is clicked
  components/select/select-top-control.component.ts
Labels: PR: partially-approved

#6687 feat(timeline): support `nzLabel`
  components/timeline/demo/label.md
  components/timeline/demo/label.ts
  components/timeline/demo/module
  components/timeline/doc/index.en-US.md
  components/timeline/doc/index.zh-CN.md
  components/timeline/timeline-item.component.ts
  components/timeline/timeline.component.ts
  components/timeline/timeline.spec.ts
Labels: PR: partially-approved

#6832 docs: update introduce
  components/package.json
  docs/introduce.zh-CN.md
  docs/join.zh-CN.md
  package.json
Labels: PR: reviewed-approved

#6833 chore: add space component migration scripts
  .gitignore
  schematics/ng-update/index.ts
  schematics/ng-update/test-cases/v12/space-deprecated.spec.ts
  schematics/ng-update/upgrade-rules/checks/space-template-rule.ts
Labels: PR: unreviewed

#6835 chore(release): release 12.0.0
  CHANGELOG.md
  README-zh_CN.md
  README.md
  components/package.json
  components/version/version.ts
  docs/changelog.en-US.md
  docs/changelog.zh-CN.md
  schematics/migration.json
  scripts/site/_site/doc/app/header/header.less
Labels: PR: reviewed-approved

#6839 fix(module:icon): resolve memory leak
  components/icon/icon.service.ts
Labels: PR: reviewed-approved

#6841 fix(module:drawer): trigger change detection only if there are `nzOnViewInit` listeners
  components/drawer/drawer.component.ts
Labels: PR: reviewed-approved

#6843 fix: remove the default resize observer polyfill
  components/cdk/resize-observer/package.json
  components/cdk/resize-observer/public-api.ts
  components/cdk/resize-observer/resize-observer.service.ts
  components/ng-package.json
  components/package.json
  scripts/site/_site/doc/app/app.module.ts
  scripts/site/_site/doc/app/header/join-tip.components.ts
Labels: PR: unreviewed

#6845 fix(module:code-editor): re-enter the Angular zone only if the value has been changed
  components/code-editor/code-editor.component.ts
Labels: PR: partially-approved

#6846 fix(module:code-editor): resolve memory leak
  components/code-editor/code-editor.service.ts
Labels: PR: partially-approved

#6847 fix(module:code-editor): dispose the event listener when the component is destroyed
  components/code-editor/code-editor.component.ts
Labels: PR: partially-approved

#6848 chore(release): release 12.0.1
  CHANGELOG.md
  components/package.json
  components/version/version.ts
  docs/changelog.en-US.md
  docs/changelog.zh-CN.md
  scripts/site/_site/doc/app/header/header.component.ts
Labels: PR: reviewed-approved

#6854 build: fix ngsw-worker cannot match index.html
  scripts/prerender/ngsw-config.ts
  scripts/prerender/route-paths.txt
  scripts/site/_site/doc/app/header/header.component.ts
  scripts/site/_site/doc/app/header/header.module.ts
  scripts/site/_site/doc/app/header/join-tip.components.ts
Labels: PR: unreviewed

#6861 docs(online-ide): update deps to angular v12
  scripts/site/_site/doc/app/online-ide/online-ide.service.ts
Labels: PR: reviewed-approved
