Repository NG-ZORRO/ng-zorro-antd, pull requests merged in 2021-02, with the labels that each got.

#6404 fix(schematics): fix `add-icon-assets` schema path
  schematics/collection.json
Labels: PR: reviewed-approved

#6409 fix(module:input): fix [nzAutosize]="true" (#6403)
  components/input/autosize.directive.ts
  components/input/autosize.spec.ts
Labels: PR: reviewed-approved

#6408 fix(module:grid,menu,radio,table): fix memory leak problem
  components/grid/col.directive.ts
  components/menu/submenu.service.ts
  components/radio/radio-group.component.ts
  components/table/src/table/table-fixed-row.component.ts
  components/table/src/table/tbody.component.ts
  components/table/src/table/thead.component.ts
Labels: PR: reviewed-approved

#6399 test(module:modal): fix typo in modal-footer-directive.spec.ts
  components/modal/modal-footer.directive.spec.ts
Labels: PR: reviewed-approved

#6421 fix(module:18n): adding new translations es_ES
  components/i18n/languages/es_ES.ts
Labels: PR: unreviewed

#6354 fix(module:dropdown): close menu when click again (#6353)
  components/dropdown/dropdown.directive.ts
Labels: PR: unreviewed

#6370 fix(module:message): avoid flicker when window close (#6296)
  components/message/base.ts
  components/message/message.component.ts
  components/message/message.spec.ts
  components/notification/notification.component.ts
Labels: PR: unreviewed

#6410 feat(module:time-picker): support updating OK and Now button text
  components/core/config/config.ts
  components/time-picker/doc/index.en-US.md
  components/time-picker/doc/index.zh-CN.md
  components/time-picker/time-picker-panel.component.ts
  components/time-picker/time-picker.component.ts
Labels: PR: unreviewed

#6385 fix(module:table): fix table filter (#6384)
  components/table/src/addon/filter.component.ts
Labels: PR: unreviewed

#6428 fix(module:docs): fix dependabot alert
  package.json
Labels: PR: unreviewed

#6434 fix(module:18n): adding new translations de_DE
  components/i18n/languages/de_DE.ts
Labels: PR: partially-approved

#6433 chore(module:transfer): change private to publish of `lists` variable
  components/transfer/transfer.component.ts
Labels: PR: partially-approved

#6445 docs(module:graph): fix markdown table format
  components/graph/doc/index.en-US.md
  components/graph/doc/index.zh-CN.md
Labels: PR: reviewed-approved

#6436 feat(module:date-picker): add `nzInline` property
  components/date-picker/date-picker.component.spec.ts
  components/date-picker/date-picker.component.ts
  components/date-picker/date-range-popup.component.ts
  components/date-picker/demo/inline.md
  components/date-picker/demo/inline.ts
  components/date-picker/demo/module
  components/date-picker/picker.component.ts
  components/date-picker/range-picker.component.spec.ts
  components/date-picker/style/entry.less
  components/date-picker/style/patch.less
Labels: PR: reviewed-approved

#6379 feat(module:time-picker,select,tree-select): support `nzId`
  components/date-picker/date-picker.component.ts
  components/date-picker/picker.component.ts
  components/select/doc/index.en-US.md
  components/select/doc/index.zh-CN.md
  components/select/select-search.component.ts
  components/select/select-top-control.component.ts
  components/select/select.component.ts
  components/time-picker/doc/index.en-US.md
  components/time-picker/doc/index.zh-CN.md
  components/time-picker/time-picker.component.ts
  components/tree-select/doc/index.en-US.md
  components/tree-select/doc/index.zh-CN.md
  components/tree-select/tree-select.component.ts
Labels: PR: partially-approved

#6452 perf(module:select): avoid reflow when select init
  components/core/animation/zoom.ts
  components/select/select-top-control.component.ts
  components/select/select.component.ts
  components/tree-select/tree-select.component.ts
Labels: PR: unreviewed

#6450 fix(module:grid): `nzGutter` support string type
  components/grid/doc/index.en-US.md
  components/grid/doc/index.zh-CN.md
  components/grid/grid.spec.ts
  components/grid/row.directive.ts
Labels: PR: partially-approved

#6454 chore(release): release 11.2.0
  CHANGELOG.md
  components/drawer/doc/index.en-US.md
  components/drawer/doc/index.zh-CN.md
  components/package.json
  components/version/version.ts
  docs/changelog.en-US.md
  docs/changelog.zh-CN.md
Labels: PR: unreviewed
