Repository NG-ZORRO/ng-zorro-antd, pull requests merged in 2021-03, with the labels that each got.

#6463 chore: bump @angular/* from 11.1 to 11.2
  angular.json
  package.json
Labels: PR: reviewed-approved

#6465 docs: add join page
  docs/join.en-US.md
  docs/join.zh-CN.md
  scripts/site/_site/doc/app/header/header.component.ts
  scripts/site/_site/doc/app/header/header.module.ts
  scripts/site/_site/doc/app/header/join-tip.components.ts
  scripts/site/_site/doc/app/side/side.component.ts
  scripts/site/template/router.template.ts
  scripts/site/utils/generate-routes.js
Labels: PR: unreviewed

#6468 fix(module:modal): fix incorrect assignment of 'nzFooter'
  components/modal/modal-footer.component.ts
Labels: PR: reviewed-approved

#6485 fix(module: pagination): fix syntax error in NzPaginationItemComponent
  components/pagination/pagination-item.component.ts
Labels: PR: reviewed-approved

#6489 fix(module:tooltip): keep tooltip visibility when trigger is null
  components/tooltip/base.ts
  components/tooltip/tooltip.spec.ts
Labels: PR: reviewed-approved

#6457 fix(module:rate): fix invalid type of `nzCount` in `strictTemplates`
  components/rate/rate.component.ts
Labels: PR: reviewed-approved

#6487 feat(module:space): add `nzSplit` support
  components/space/demo/align.ts
  components/space/demo/basic.ts
  components/space/demo/customize.ts
  components/space/demo/module
  components/space/demo/size.ts
  components/space/demo/split.md
  components/space/demo/split.ts
  components/space/demo/vertical.ts
  components/space/doc/index.en-US.md
  components/space/doc/index.zh-CN.md
  components/space/space-item.component.ts
  components/space/space-item.directive.ts
  components/space/space.component.spec.ts
  components/space/space.component.ts
  components/space/space.module.ts
  components/space/types.ts
Labels: PR: unreviewed

#6493 fix(module:table): virtual scroll bordered style
  components/table/demo/virtual.ts
  components/table/style/patch.less
Labels: PR: unreviewed

#6515 docs: Fix broken table in radio component's docs
  components/radio/doc/index.en-US.md
Labels: PR: unreviewed

#6513 fix(module:descriptions): fix dom structure under vertical layout
  components/descriptions/descriptions.component.ts
Labels: PR: reviewed-approved

#6521 fix(module:space): add missing exports
  components/space/public-api.ts
Labels: PR: unreviewed

#6524 fix(module:date-picker,core,i18n): import date-fns by esm
  components/core/time/candy-date.ts
  components/date-picker/demo/basic.ts
  components/date-picker/demo/disabled-date.ts
  components/date-picker/demo/inline.ts
  components/date-picker/demo/presetted-ranges.ts
  components/date-picker/demo/range-picker.ts
  components/i18n/date-helper.service.ts
Labels: PR: reviewed-approved

#6531 docs: fix typos
  docs/contributing.zh-CN.md
Labels: PR: unreviewed

#6517 docs(module:descriptions): sync 'vertical' document
  components/descriptions/demo/vertical.md
  components/descriptions/demo/vertical.ts
Labels: PR: partially-approved

#6143 fix: dropdown and autocomplete animations
  components/auto-complete/autocomplete-trigger.directive.ts
  components/auto-complete/autocomplete.component.ts
  components/auto-complete/autocomplete.spec.ts
  components/dropdown/dropdown-menu.component.ts
  components/dropdown/dropdown.directive.ts
Labels: PR: partially-approved

#6503 docs: improve the description of the `nzCloseOnNavigation` API
  components/drawer/doc/index.en-US.md
  components/drawer/doc/index.zh-CN.md
  components/image/doc/index.en-US.md
  components/image/doc/index.zh-CN.md
  components/modal/doc/index.en-US.md
  components/modal/doc/index.zh-CN.md
Labels: PR: unreviewed

#6470 fix(module:tooltip): detect trigger change
  components/tooltip/base.ts
Labels: PR: unreviewed

#6459 docs(module:notification): use more reasonable content for duration demo
  components/notification/demo/duration.ts
Labels: PR: partially-approved

#6505 fix(module:mention): preserve white spaces when insert suggestions
  components/mention/config.ts
  components/mention/mention-trigger.ts
  components/mention/mention.component.ts
Labels: PR: unreviewed

#6396 feat(module:modal): add nzModalTitle directive (#6337)
  components/modal/doc/index.en-US.md
  components/modal/doc/index.zh-CN.md
  components/modal/modal-title.directive.spec.ts
  components/modal/modal-title.directive.ts
  components/modal/modal.component.ts
  components/modal/modal.module.ts
  components/modal/public-api.ts
Labels: PR: reviewed-approved

#6380 feat(module: all): global config for backdrop
  components/cascader/cascader.component.ts
  components/cascader/cascader.spec.ts
  components/cascader/doc/index.en-US.md
  components/cascader/doc/index.zh-CN.md
  components/core/config/config.ts
  components/date-picker/date-picker.component.spec.ts
  components/date-picker/date-picker.component.ts
  components/date-picker/doc/index.en-US.md
  components/date-picker/doc/index.zh-CN.md
  components/date-picker/picker.component.ts
  components/popconfirm/doc/index.en-US.md
  components/popconfirm/doc/index.zh-CN.md
  components/popconfirm/popconfirm.spec.ts
  components/popconfirm/popconfirm.ts
  components/popover/doc/index.en-US.md
  components/popover/doc/index.zh-CN.md
  components/popover/popover.spec.ts
  components/popover/popover.ts
  components/select/doc/index.en-US.md
  components/select/doc/index.zh-CN.md
  components/select/select.component.ts
  components/select/select.spec.ts
  components/time-picker/doc/index.en-US.md
  components/time-picker/doc/index.zh-CN.md
  components/time-picker/time-picker.component.spec.ts
  components/time-picker/time-picker.component.ts
  components/tooltip/base.ts
  components/tree-select/doc/index.en-US.md
  components/tree-select/doc/index.zh-CN.md
  components/tree-select/tree-select.component.ts
  components/tree-select/tree-select.spec.ts
Labels: PR: unreviewed

#6546 chore: release 11.3.0
  CHANGELOG.md
  components/package.json
  components/version/version.ts
  docs/changelog.en-US.md
  docs/changelog.zh-CN.md
Labels: PR: unreviewed
