Repository NG-ZORRO/ng-zorro-antd, pull requests merged in 2021-11, with the labels that each got.

#6896 fix(module:affix): fix update position when target resize
  components/affix/affix.component.ts
Labels: PR: reviewed-approved

#6851 fix(module:autocomplete): resolve memory leak
  components/auto-complete/autocomplete.component.ts
Labels: PR: reviewed-approved

#6856 fix(module:image): resolve memory leak
  components/image/image-preview-ref.ts
  components/image/image.directive.ts
  components/image/image.spec.ts
Labels: PR: unreviewed

#6895 chore: fix ng lint fail
  package.json
Labels: PR: unreviewed

#7032 fix(module:upload): do not trigger change detection for `nz-upload-btn`
  components/upload/upload-btn.component.ts
  components/upload/upload.spec.ts
Labels: PR: reviewed-approved

#6850 fix(module:breadcrumb): do not re-enter the Angular zone when calling `navigate`
  components/breadcrumb/breadcrumb.component.ts
  components/breadcrumb/breadcrumb.spec.ts
Labels: PR: reviewed-approved

#6849 fix(module:button): do not trigger change detections on click events
  components/button/button.component.ts
  components/button/button.spec.ts
Labels: PR: partially-approved

#6858 perf(module:select): do not run change detection if the `triggerWidth` has not been changed
  components/select/select.component.ts
  components/select/select.spec.ts
Labels: PR: partially-approved

#6866 fix(module:popconfirm): add nzOkDanger option for nz-popconfirm
  components/popconfirm/doc/index.en-US.md
  components/popconfirm/doc/index.zh-CN.md
  components/popconfirm/popconfirm.spec.ts
  components/popconfirm/popconfirm.ts
Labels: PR: reviewed-approved

#6913 chore: limit object propertyies of mapped types
  components/core/overlay/overlay-position.ts
  components/pipes/nz-bytes.pipe.ts
  components/tooltip/base.ts
Labels: PR: partially-approved

#6919 fix(module: core): correct hidden behavior
  components/core/transition-patch/transition-patch.directive.ts
  components/core/transition-patch/transition-patch.spec.ts
Labels: PR: partially-approved

#6922 docs: fix the site dir toggle button
  scripts/site/_site/doc/app/header/header.component.ts
Labels: PR: unreviewed

#6928 fix(module:modal): footer onClick rethrow error in promise catch
  components/modal/modal-footer.component.ts
  components/modal/modal.spec.ts
Labels: PR: reviewed-approved

#7033 fix(module:code-editor): load Monaco only once
  components/code-editor/code-editor.service.ts
  components/code-editor/typings.ts
Labels: PR: reviewed-approved

#7034 fix(module:table): resolve leak within the `nz-table-fixed-row`
  components/table/src/table/table-fixed-row.component.ts
Labels: PR: partially-approved

#7026 fix(module:table): add measurement for nzWidth
  components/table/doc/index.en-US.md
Labels: PR: unreviewed

#6793 fix(module: pagination): the prevFiveItem should not be displayed
  components/pagination/pagination-default.component.ts
  components/pagination/pagination.spec.ts
Labels: PR: unreviewed

#7035 chore(release): release 12.0.2
  CHANGELOG.md
  components/package.json
  components/version/version.ts
  docs/changelog.en-US.md
  docs/changelog.zh-CN.md
Labels: PR: partially-approved

#7052 fix(module:graph): resolve minimap memory leaks
  components/graph/core/minimap.ts
  components/graph/graph-minimap.component.ts
Labels: PR: reviewed-approved

#7051 docs(module:select): typo error
  components/select/doc/index.zh-CN.md
Labels: PR: partially-approved

#7048 fix(module:auto-complete): do not run change detection on `mousedown` and `mouseenter` for `nz-auto-option`
  components/auto-complete/autocomplete-option.component.ts
  components/auto-complete/autocomplete.spec.ts
Labels: PR: reviewed-approved

#7037 fix(module:upload): do not trigger change detection for `nz-upload-btn`
  components/upload/upload-btn.component.ts
  components/upload/upload.spec.ts
Labels: PR: partially-approved

#7036 fix(module:resizable): reduce change detection cycles
  components/resizable/resizable.directive.ts
  components/resizable/resizable.spec.ts
  components/resizable/resize-handle.component.ts
Labels: PR: reviewed-approved

#7038 fix(module:select): reduce change detections for `nz-select-top-control`
  components/select/select-top-control.component.ts
  components/select/select.spec.ts
Labels: PR: partially-approved

#7056 perf(module:graph): reduce change detections on click events
  components/graph/graph-node.component.ts
  components/graph/graph.component.ts
Labels: PR: unreviewed

#7010 feat(module:tooltip, etc): add arrow point at center
  components/core/overlay/nz-connected-overlay.ts
  components/popconfirm/doc/index.en-US.md
  components/popconfirm/doc/index.zh-CN.md
  components/popconfirm/popconfirm.ts
  components/popover/demo/arrow-point-at-center.ts
  components/popover/doc/index.en-US.md
  components/popover/doc/index.zh-CN.md
  components/popover/popover.ts
  components/tooltip/base.ts
  components/tooltip/demo/arrow-point-at-center.md
  components/tooltip/demo/arrow-point-at-center.ts
  components/tooltip/doc/index.en-US.md
  components/tooltip/doc/index.zh-CN.md
  components/tooltip/tooltip.spec.ts
  components/tooltip/tooltip.ts
Labels: PR: unreviewed

#7067 fix(module:upload): previewing images should be cancellable when the component gets destroyed
  components/upload/upload-list.component.ts
  components/upload/upload.spec.ts
Labels: PR: reviewed-approved

#7068 perf(module:radio): reduce change detection cycles
  components/radio/radio.component.ts
  components/radio/radio.spec.ts
Labels: PR: partially-approved

#7076 fix(module:tabs): tabs add btn disappear after all tab closed
  components/tabs/style/patch.less
  components/tabs/tabset.component.spec.ts
  components/tabs/tabset.component.ts
Labels: PR: partially-approved

#6948 feat(module:tooltip): support tooltip template context
  components/tooltip/demo/template.md
  components/tooltip/demo/template.ts
  components/tooltip/doc/index.en-US.md
  components/tooltip/doc/index.zh-CN.md
  components/tooltip/tooltip.ts
Labels: PR: reviewed-approved, PR: target-minor

#7062 perf(module:core): do not run change detection when scrolling
  components/core/services/scroll.spec.ts
  components/core/services/scroll.ts
Labels: PR: reviewed-approved

#7070 perf(module:modal): do not run change detection when focusing element
  components/modal/modal-confirm-container.component.ts
  components/modal/modal-container.component.ts
  components/modal/modal-container.ts
Labels: PR: partially-approved

#6783 feat(module:core,dropdown,table): add config for backdrop
  components/core/config/config.ts
  components/dropdown/dropdown.directive.ts
  components/table/src/addon/filter-trigger.component.ts
Labels: PR: partially-approved

#7085 fix(module:tree-view): incorrect type of `trackBy`
  components/tree-view/tree-virtual-scroll-view.ts
Labels: PR: reviewed-approved

#7087 chore(release): release 12.1.0
  CHANGELOG.md
  components/package.json
  components/version/version.ts
  docs/changelog.en-US.md
  docs/changelog.zh-CN.md
Labels: PR: partially-approved
