Repository NG-ZORRO/ng-zorro-antd, pull requests merged in 2021-09, with the labels that each got.

#6966 chore: fix immer dependency security issue
  package.json
Labels: PR: unreviewed

#6934 fix(module:table): show empty state regardless of loading value
  components/table/src/table/table.component.ts
Labels: PR: partially-approved

#6965 fix(module:tooltip): fix tooltip for deeply wrapped focusable elements
  components/tooltip/base.ts
  components/tooltip/tooltip.spec.ts
Labels: PR: reviewed-approved

#6982 fix(module:i18n): update en_GB.ts translations
  components/i18n/languages/en_GB.ts
Labels: PR: unreviewed
