Repository NG-ZORRO/ng-zorro-antd, pull requests merged in 2022-02, with the labels that each got.

#7236 fix(module:date-picker): fix disable time when date changes
  components/date-picker/date-picker.component.spec.ts
  components/date-picker/date-range-popup.component.ts
Labels: PR: reviewed-approved

#7249 fix(module:i18n): update fa-IR.ts translations
  components/i18n/languages/fa_IR.ts
Labels: PR: unreviewed

#7252 fix(module:slider): fix keydown not trigger nzOnAfterChange
  components/slider/slider.component.ts
  components/slider/slider.spec.ts
Labels: PR: reviewed-approved, PR: target-patch

#7172 fix(module:date-picker): fix `z-index` to `auto` in inline mode
  components/date-picker/style/patch.less
Labels: PR: unreviewed

#7214 fix(module:input): do not set box-sizing when measuring
  components/input/autosize.spec.ts
  components/input/style/patch.less
Labels: PR: partially-approved

#7223 chore: add node v16 as part of engines field in package.json
  package.json
Labels: PR: unreviewed

#7261 feat(module:i18n): add kk_KZ to i18n
  components/i18n/languages/kk_KZ.ts
  components/i18n/public-api.ts
  docs/i18n.en-US.md
  docs/i18n.zh-CN.md
Labels: PR: reviewed-approved

#7185 perf(module:typography): do not run change detection on `input` and `keydown` events
  components/typography/text-edit.component.ts
  components/typography/typography.spec.ts
Labels: PR: partially-approved

#7222 fix(module:select): fix keyboard event error when option data is empty
  components/select/select.component.ts
  components/select/select.spec.ts
Labels: PR: partially-approved

#7181 perf(module:collapse): do not run change detection if the panel is disabled
  components/collapse/collapse-panel.component.ts
  components/collapse/collapse.component.ts
Labels: PR: partially-approved

#7218 fix(module:i18n): update pt_BR.ts translations
  components/i18n/languages/pt_BR.ts
Labels: PR: reviewed-approved

#7175 perf(module:select): do not run change detection unnecessarily on click events
  components/select/select.component.ts
Labels: PR: unreviewed

#7220 feat(module:i18n): add km_KH
  components/i18n/languages/km_KH.ts
  components/i18n/public-api.ts
  docs/i18n.en-US.md
  docs/i18n.zh-CN.md
Labels: PR: unreviewed

#7267 fix(module:button): prevent default event fire
  components/button/button.component.ts
  components/button/button.spec.ts
Labels: PR: partially-approved

#7147 perf(module:image): do not run change detection if there are no `containerClick` listeners
  components/image/image-preview.component.ts
Labels: PR: reviewed-approved

#7170 perf(module:resizable): do not run change detection on `mousedown` and `touchstart` events
  components/resizable/resizable.directive.ts
  components/resizable/resizable.service.ts
  components/resizable/resizable.spec.ts
  components/resizable/resize-handle.component.ts
  components/resizable/resize-handles.component.ts
Labels: PR: partially-approved

#7146 perf(module:mention): do not run change detection when the dropdown cannot be closed
  components/mention/mention.component.ts
Labels: PR: partially-approved

#7144 perf(module:tabs): do not run change detection when the promise resolves
  components/tabs/tabset.component.ts
Labels: PR: partially-approved

#7143 perf(module:time-picker): do not run change detection when the timer fires
  components/time-picker/time-picker-panel.component.ts
Labels: PR: partially-approved

#7227 feat(module:drawer): support new apis nzSize and nzExtra
  components/drawer/demo/module
  components/drawer/demo/service.ts
  components/drawer/demo/size.md
  components/drawer/demo/size.ts
  components/drawer/doc/index.en-US.md
  components/drawer/doc/index.zh-CN.md
  components/drawer/drawer-options.ts
  components/drawer/drawer.component.ts
  components/drawer/drawer.spec.ts
Labels: PR: unreviewed

#7275 docs: add ng-ant-admin website URL in EN(#7213)(#7230)
  docs/recommendation.en-US.md
Labels: PR: reviewed-approved

#7142 perf(module:table): do not unnecessarily re-enter the Angular zone
  components/table/src/table/tr-measure.component.ts
Labels: PR: partially-approved

#7140 perf(module:table): spawn timers and add listener outside of the zone
  components/table/src/table/table-inner-scroll.component.ts
Labels: PR: partially-approved

#7138 perf(module:auto-complete): do not run change detection when the promise resolves
  components/auto-complete/autocomplete-trigger.directive.ts
Labels: PR: partially-approved

#7270 fix(module:radio): emit `false` to the `ngModel` whenever the radio button is deselected
  components/radio/radio.component.ts
  components/radio/radio.spec.ts
Labels: PR: partially-approved

#7250 fix(module:input): incorrect background color in disabled state
  components/input/input-group.component.ts
Labels: PR: partially-approved

#7136 perf(module:carousel): do not run change detection when the timer fires
  components/carousel/carousel.component.ts
  components/carousel/strategies/experimental/flip-strategy.ts
  components/carousel/typings.ts
Labels: PR: partially-approved

#7135 perf(module:dropdown): do not run change detection if the dropdown has been clicked inside
  components/dropdown/context-menu.service.spec.ts
  components/dropdown/context-menu.service.ts
Labels: PR: partially-approved

#7133 perf(module:select): do not run change detection on events if the `nz-option-item` is disabled
  components/select/option-item.component.ts
Labels: PR: partially-approved

#7269 fix(module:resizable): fix demos of resizable
  components/resizable/demo/drawer.ts
  components/resizable/demo/table.ts
Labels: PR: reviewed-approved

#7154 test(module:*): fix testing styleUrls to make it faster
  angular.json
  components/avatar/avatar.spec.ts
  components/table/src/testing/table.spec.ts
  components/tabs/tabset.component.spec.ts
  components/time-picker/time-picker-panel.component.spec.ts
  components/transfer/transfer.spec.ts
  components/tree/tree.spec.ts
  custom-webpack-spec.config.js
  package.json
Labels: PR: partially-approved

#7246 feat(module:alert): support nzAction for customizing actions
  components/alert/alert.component.ts
  components/alert/alert.spec.ts
  components/alert/demo/action.md
  components/alert/demo/action.ts
  components/alert/demo/module
  components/alert/doc/index.en-US.md
  components/alert/doc/index.zh-CN.md
Labels: PR: partially-approved

#7130 perf(module:mention): do not trigger change detections if there are no event listeners
  components/mention/mention-trigger.ts
Labels: PR: partially-approved

#7224 chore: add pre-commit npm script to display command process stdout
  .husky/pre-commit
  package.json
Labels: PR: reviewed-approved

#7277 chore(release): release 13.1.0
  CHANGELOG.md
  components/package.json
  components/version/version.ts
  docs/changelog.en-US.md
  docs/changelog.zh-CN.md
Labels: PR: unreviewed
