Repository NG-ZORRO/ng-zorro-antd, pull requests merged in 2022-05, with the labels that each got.

#7415 docs: update `getting-started.en-US.md`
  docs/getting-started.en-US.md
Labels: PR: reviewed-approved

#7417 docs(module:tooltip): update `index.en-US.md`
  components/tooltip/doc/index.en-US.md
Labels: PR: reviewed-approved

#7418 docs(module:upload): update `index.en-US.md`
  components/upload/doc/index.en-US.md
Labels: PR: partially-approved

#7416 docs(module:transfer): update `index.en-US.md`
  components/transfer/doc/index.en-US.md
Labels: PR: reviewed-approved

#7426 fix(module:tree-view): trigger markforcheck after nodes changed
  components/tree-view/tree-virtual-scroll-view.ts
Labels: PR: partially-approved

#7427 chore(release): release 13.2.2
  CHANGELOG.md
  components/package.json
  components/version/version.ts
  docs/changelog.en-US.md
  docs/changelog.zh-CN.md
Labels: PR: reviewed-approved

#7437 docs(module: mention): fix API docs button to bottom
  components/mention/doc/index.zh-CN.md
Labels: PR: unreviewed

#7404 feat(module:segmented): implement new component
  .github/CODEOWNERS
  components/components.less
  components/core/animation/public-api.ts
  components/core/animation/thumb.ts
  components/core/config/config.ts
  components/segmented/demo/basic.md
  components/segmented/demo/basic.ts
  components/segmented/demo/block.md
  components/segmented/demo/block.ts
  components/segmented/demo/custom.md
  components/segmented/demo/custom.ts
  components/segmented/demo/disabled.md
  components/segmented/demo/disabled.ts
  components/segmented/demo/dynamic.md
  components/segmented/demo/dynamic.ts
  components/segmented/demo/icon.md
  components/segmented/demo/icon.ts
  components/segmented/demo/module
  components/segmented/demo/size.md
  components/segmented/demo/size.ts
  components/segmented/demo/value.md
  components/segmented/demo/value.ts
  components/segmented/doc/index.en-US.md
  components/segmented/doc/index.zh-CN.md
  components/segmented/index.ts
  components/segmented/ng-package.json
  components/segmented/public-api.ts
  components/segmented/segmented.component.ts
  components/segmented/segmented.module.ts
  components/segmented/segmented.spec.ts
  components/segmented/style/entry.less
  components/segmented/style/index.less
  components/segmented/style/mixins.less
  components/segmented/style/rtl.less
  components/segmented/types.ts
  components/style/themes/dark.less
  components/style/themes/default.less
  scripts/site/_site/doc/app/online-ide/files/ng-zorro-antd.module.ts
  scripts/site/template/ng-zorro-antd.module.template.ts
Labels: :star: New Component, PR: unreviewed, PR: partially-approved

#7452 feat(module:cascader): support setting status
  components/cascader/cascader.component.ts
  components/cascader/cascader.spec.ts
  components/cascader/demo/status.md
  components/cascader/demo/status.ts
  components/cascader/doc/index.en-US.md
  components/cascader/doc/index.zh-CN.md
  components/core/types/public-api.ts
  components/core/types/status.ts
  components/core/types/type.ts
  components/core/util/public-api.ts
  components/core/util/status-util.ts
Labels: PR: partially-approved

#7462 feat(module:input-number): support setting status
  components/cascader/cascader.spec.ts
  components/input-number/demo/status.md
  components/input-number/demo/status.ts
  components/input-number/doc/index.en-US.md
  components/input-number/doc/index.zh-CN.md
  components/input-number/input-number.component.ts
  components/input-number/input-number.spec.ts
Labels: PR: partially-approved

#7446 docs(module:skeleton): update `index.en-US.md`
  components/skeleton/doc/index.en-US.md
Labels: PR: partially-approved

#7413 fix(module:transfer): `submit` behavior for button inside form
  components/transfer/transfer.component.ts
Labels: PR: reviewed-approved

#7464 fix(module:date-picker): fix position of picker popup
  components/date-picker/style/patch.less
Labels: PR: unreviewed

#7465 refactor(module:mention): change dom to fit antd
  components/mention/mention.component.ts
  components/mention/mention.module.ts
  components/mention/nz-mention.spec.ts
  components/mention/style/patch.less
Labels: PR: partially-approved

#7476 fix(module:tabs): fix inconsistent animation behavior with previous
  components/tabs/doc/index.zh-CN.md
  components/tabs/style/patch.less
Labels: PR: partially-approved

#7442 fix(module:18n): updating es_ES translations
  components/i18n/languages/es_ES.ts
Labels: PR: partially-approved

#7467 feat(module:mentions): support setting status
  components/mention/demo/async.ts
  components/mention/demo/avatar.md
  components/mention/demo/avatar.ts
  components/mention/demo/basic.ts
  components/mention/demo/custom-tag.md
  components/mention/demo/custom-tag.ts
  components/mention/demo/form.md
  components/mention/demo/form.ts
  components/mention/demo/multilines.md
  components/mention/demo/placement.md
  components/mention/demo/placement.ts
  components/mention/demo/prefix.md
  components/mention/demo/prefix.ts
  components/mention/demo/readonly.md
  components/mention/demo/readonly.ts
  components/mention/demo/status.md
  components/mention/demo/status.ts
  components/mention/doc/index.en-US.md
  components/mention/doc/index.zh-CN.md
  components/mention/mention.component.ts
  components/mention/nz-mention.spec.ts
  components/mention/style/patch.less
Labels: PR: partially-approved

#7475 feat(module:transfer): support setting status
  components/transfer/demo/module
  components/transfer/demo/status.md
  components/transfer/demo/status.ts
  components/transfer/doc/index.en-US.md
  components/transfer/doc/index.zh-CN.md
  components/transfer/transfer.component.ts
  components/transfer/transfer.spec.ts
Labels: PR: reviewed-approved

#7478 feat(module:select): support setting status
  components/select/demo/module
  components/select/demo/status.md
  components/select/demo/status.ts
  components/select/doc/index.en-US.md
  components/select/doc/index.zh-CN.md
  components/select/select.component.ts
  components/select/select.spec.ts
Labels: PR: reviewed-approved

#7479 feat(module:date-picker): support setting status
  components/date-picker/date-picker.component.spec.ts
  components/date-picker/date-picker.component.ts
  components/date-picker/demo/status.md
  components/date-picker/demo/status.ts
  components/date-picker/doc/index.en-US.md
  components/date-picker/doc/index.zh-CN.md
  components/date-picker/range-picker.component.spec.ts
Labels: PR: unreviewed

#7473 feat(module:time-picker): support setting status
  components/time-picker/demo/module
  components/time-picker/demo/status.md
  components/time-picker/demo/status.ts
  components/time-picker/doc/index.en-US.md
  components/time-picker/doc/index.zh-CN.md
  components/time-picker/time-picker.component.spec.ts
  components/time-picker/time-picker.component.ts
Labels: PR: partially-approved

#7472 feat(module:input): support setting status
  components/input/demo/module
  components/input/demo/status.md
  components/input/demo/status.ts
  components/input/doc/index.en-US.md
  components/input/doc/index.zh-CN.md
  components/input/input-group.component.ts
  components/input/input-group.spec.ts
  components/input/input.directive.ts
  components/input/input.spec.ts
Labels: PR: partially-approved

#7477 feat(module:tree-select): add status
  components/tree-select/demo/module
  components/tree-select/demo/status.md
  components/tree-select/demo/status.ts
  components/tree-select/doc/index.en-US.md
  components/tree-select/doc/index.zh-CN.md
  components/tree-select/tree-select.component.ts
  components/tree-select/tree-select.spec.ts
Labels: PR: unreviewed
