Repository NG-ZORRO/ng-zorro-antd, pull requests merged in 2022-12, with the labels that each got.

#7741 docs(module:table): update wrong parameter name
  components/table/doc/index.en-US.md
Labels: PR: partially-approved

#7709 fix(module:input): textarea-count combined with nzHasFeedback location
  components/form/demo/validate-reactive.ts
  components/input/style/patch.less
Labels: PR: partially-approved

#7750 feat(module:cron-expression): Optimize cron result display & support custom rendering cron time
  components/cron-expression/cron-expression-input.component.ts
  components/cron-expression/cron-expression-label.component.ts
  components/cron-expression/cron-expression-preview.component.ts
  components/cron-expression/cron-expression.component.ts
  components/cron-expression/cron-expression.module.ts
  components/cron-expression/demo/semantic.md
  components/cron-expression/demo/semantic.ts
  components/cron-expression/demo/use.md
  components/cron-expression/doc/index.en-US.md
  components/cron-expression/doc/index.zh-CN.md
  components/cron-expression/style/index.less
Labels: ✏️ Style, PR: unreviewed, PR: reviewed-approved, PR: target-major

#7721 feat(module:date-picker): add ElementRef type to nzSeparator
  components/date-picker/date-picker.component.ts
  components/date-picker/doc/index.en-US.md
  components/date-picker/doc/index.zh-CN.md
  components/date-picker/range-picker.component.spec.ts
Labels: PR: target-major, PR: partially-approved

#7385 fix(module:tree): tree select search slow in virtual mode
  components/tree-select/demo/virtual-scroll.ts
  components/tree/tree.component.ts
  components/tree/tree.spec.ts
Labels: PR: target-minor, PR: partially-approved

#7579 fix(module: tree): nz-tree-drop-indicator for custom tree node templates
  components/tree/tree-node-title.component.ts
Labels: PR: reviewed-approved

#7756 fix(list): specify template ref context on input to match instantiation
  components/list/list.component.ts
Labels: PR: partially-approved

#7728 feat(module:select): select on Tab support
  components/select/doc/index.en-US.md
  components/select/doc/index.zh-CN.md
  components/select/select.component.ts
  components/select/select.spec.ts
Labels: PR: target-major, PR: partially-approved

#7686 fix(module:select): disabled option can be selected by Enter
  components/select/select.component.ts
  components/select/select.spec.ts
Labels: PR: partially-approved

#7551 fix(module:tree-select): update nzPlacement demo
  components/tree-select/demo/module
  components/tree-select/demo/placement.md
  components/tree-select/demo/placement.ts
  components/tree-select/doc/index.en-US.md
  components/tree-select/doc/index.zh-CN.md
  components/tree-select/tree-select.component.ts
Labels: PR: partially-approved

#7765 chore(release): release 14.3.0
  CHANGELOG.md
  components/package.json
  components/version/version.ts
  docs/changelog.en-US.md
  docs/changelog.zh-CN.md
Labels: PR: unreviewed

#7767 perf(module:date-picker): remove unused variable
  components/date-picker/date-picker.component.ts
Labels: PR: unreviewed

#7773 docs: replace the QR code of the DingTalk group
  docs/introduce.zh-CN.md
Labels: PR: reviewed-approved

#7775 test(module:date-picker): fix typo
  components/time-picker/time-picker-panel.component.spec.ts
Labels: PR: unreviewed

#7778 docs(popconfirm): remove nzOkType danger
  components/popconfirm/doc/index.zh-CN.md
Labels: PR: partially-approved

#7766 perf(module:form): remove a unused variable
  components/form/form-control.component.ts
Labels: PR: reviewed-approved

#7781 chore(module:components): update angular icons version for v15
  components/package.json
Labels: PR: reviewed-approved

#7668 fix(module:drawer): fix `nzContentParams` definition error
  components/drawer/drawer.component.ts
Labels: PR: partially-approved

#7782 chore(release): release 15.0.0
  CHANGELOG.md
  components/package.json
  components/version/version.ts
  docs/changelog.en-US.md
  docs/changelog.zh-CN.md
Labels: PR: unreviewed

#7792 chore: update site for v15
  README-zh_CN.md
  README.md
  components/icon/page/index.ts
  docs/introduce.en-US.md
  docs/introduce.zh-CN.md
  docs/join.zh-CN.md
  docs/migration-v15.en-US.md
  docs/migration-v15.zh-CN.md
  package.json
  scripts/prerender/route-paths.txt
  scripts/site/_site/doc/app/header/header.component.ts
  scripts/site/_site/doc/app/online-ide/files/angular.json.ts
  scripts/site/_site/doc/app/online-ide/files/ng-zorro-antd.module.ts
  scripts/site/_site/doc/app/online-ide/online-ide.service.ts
Labels: PR: unreviewed
