Repository NG-ZORRO/ng-zorro-antd, pull requests merged in 2022-08, with the labels that each got.

#7582 fix(module:steps): remove top-level redundant `div` element
  components/steps/demo/nav.ts
  components/steps/steps.component.ts
  components/steps/steps.spec.ts
Labels: 💔 Breaking Change, PR: reviewed-approved, PR: target-major

#7533 feat(module: popconfirm): support async close
  components/popconfirm/demo/async.md
  components/popconfirm/demo/async.ts
  components/popconfirm/demo/promise.md
  components/popconfirm/demo/promise.ts
  components/popconfirm/doc/index.en-US.md
  components/popconfirm/doc/index.zh-CN.md
  components/popconfirm/popconfirm.spec.ts
  components/popconfirm/popconfirm.ts
Labels: PR: reviewed-approved

#7471 docs(module:cascader): add an FAQ section
  components/cascader/doc/index.en-US.md
  components/cascader/doc/index.zh-CN.md
Labels: PR: reviewed-approved

#7599 docs(module:popconfirm): fix `nzPopconfirmTrigger` default value to `click`
  components/popconfirm/doc/index.en-US.md
  components/popconfirm/doc/index.zh-CN.md
Labels: PR: reviewed-approved

#7604 fix(module:cascader): fix wrong format of docs
  components/cascader/doc/index.en-US.md
Labels: PR: unreviewed

#7605 test: add RouterTestingModule to spec files
  components/breadcrumb/breadcrumb.spec.ts
  components/dropdown/context-menu.service.spec.ts
  components/dropdown/dropdown.directive.spec.ts
  components/menu/menu.spec.ts
  components/table/src/testing/th.spec.ts
  components/tabs/tabset.component.spec.ts
Labels: PR: partially-approved

#7500 fix(module:pagination): add ul tag
  components/pagination/pagination-default.component.ts
  components/pagination/pagination-options.component.ts
  components/pagination/pagination-simple.component.ts
  components/pagination/pagination.spec.ts
Labels: PR: partially-approved

#7608 chore(release): release 14.0.0
  CHANGELOG.md
  README-zh_CN.md
  README.md
  components/graph/graph.module.ts
  components/package.json
  components/tsconfig.lib.json
  components/version/version.ts
  docs/changelog.en-US.md
  docs/changelog.zh-CN.md
  docs/introduce.en-US.md
  docs/introduce.zh-CN.md
  docs/migration-v14.en-US.md
  docs/migration-v14.zh-CN.md
  package.json
  schematics/migration.json
  schematics/ng-update/index.ts
  scripts/gulp/tasks/site.ts
  scripts/prerender/route-paths.txt
  scripts/site/_site/doc/app/app.module.ts
  scripts/site/_site/doc/app/app.routing.module.ts
  scripts/site/_site/doc/app/header/header.component.ts
  scripts/site/_site/doc/app/online-ide/files/ng-zorro-antd.module.ts
  scripts/site/_site/doc/app/online-ide/online-ide.service.ts
  scripts/site/_site/doc/style/demo.less
  scripts/site/_site/doc/style/markdown.less
  scripts/site/_site/tsconfig.app.json
  scripts/site/template/demo-module.template.ts
  scripts/site/utils/generate-demo.js
  scripts/site/utils/generate-docs.js
  tsconfig.json
Labels: PR: partially-approved
