Repository NG-ZORRO/ng-zorro-antd, pull requests merged in 2022-09, with the labels that each got.

#7646 fix(module:i18n): update it_IT.ts
  components/i18n/languages/it_IT.ts
Labels: PR: unreviewed

#7621 feat(module:date-picker): add nzShowWeekNumber property
  components/date-picker/date-picker.component.spec.ts
  components/date-picker/date-picker.component.ts
  components/date-picker/date-range-popup.component.ts
  components/date-picker/demo/week-number.md
  components/date-picker/demo/week-number.ts
  components/date-picker/doc/index.en-US.md
  components/date-picker/doc/index.zh-CN.md
  components/date-picker/inner-popup.component.ts
  components/date-picker/lib/abstract-table.ts
  components/date-picker/lib/date-table.component.ts
  components/date-picker/style/patch.less
Labels: PR: reviewed-approved, PR: target-minor, PR: partially-approved

#7642 fix(module:select): fix broken cdk virtual scroll integration
  components/select/style/patch.less
Labels: PR: target-major, PR: partially-approved

#7537 feat(module: select): support placement
  components/select/demo/placement.md
  components/select/demo/placement.ts
  components/select/doc/index.en-US.md
  components/select/doc/index.zh-CN.md
  components/select/select.component.ts
  components/select/select.spec.ts
  components/select/select.types.ts
Labels: PR: target-major, PR: partially-approved

#7408 docs(module:*): debug demos
  components/progress/demo/dashboard-layout.md
  components/progress/demo/dashboard-layout.ts
  package.json
  scripts/site/generate-site.js
  scripts/site/utils/get-meta.js
Labels: PR: unreviewed

#7420 feat(module:menu): add support nzPlacement for nz-submenu
  components/core/overlay/overlay-position.ts
  components/menu/demo/horizontal-position.md
  components/menu/demo/horizontal-position.ts
  components/menu/doc/index.en-US.md
  components/menu/doc/index.zh-CN.md
  components/menu/submenu.component.ts
Labels: PR: target-major, PR: partially-approved

#7353 docs(module:table): update `multiple-sorter.ts`
  components/table/demo/multiple-sorter.ts
Labels: PR: unreviewed

#7643 feat(module:select): add string array support for nzDropdownClassName
  components/select/doc/index.en-US.md
  components/select/doc/index.zh-CN.md
  components/select/select.component.ts
Labels: PR: partially-approved

#7626 fix(module:select): input field length restricted to 82px
  components/select/select-search.component.ts
Labels: PR: partially-approved

#7320 fix(module:typography): focus the element and set the value even if the zone is already stable
  components/typography/text-edit.component.ts
  components/typography/typography.spec.ts
Labels: PR: partially-approved
