Repository NG-ZORRO/ng-zorro-antd, pull requests merged in 2022-03, with the labels that each got.

#7284 fix(module:collapse): markForCheck after collapse title clicked
  components/collapse/collapse-panel.component.ts
Labels: PR: partially-approved

#7290 fix(module:icon): do not try to load SVG on the Node.js side since it will throw an error
  components/icon/icon.directive.ts
  components/icon/icon.service.ts
  package.json
Labels: PR: partially-approved

#7285 docs: remove warnings caused by wrong spelling while building lib
  components/grid/demo/gutter.ts
  components/space/demo/align.ts
Labels: PR: partially-approved

#7206 fix(module:upload): fix the problem that the transformed file is lost
  components/upload/upload-btn.component.ts
Labels: PR: partially-approved

#6816 fix(module:select): exact match while searching should be active
  components/select/select.component.ts
Labels: PR: partially-approved

#7291 chore(release): release 13.1.1
  CHANGELOG.md
  components/package.json
  components/version/version.ts
  docs/changelog.en-US.md
  docs/changelog.zh-CN.md
Labels: PR: partially-approved

#7297 docs(module:modal): fix typo
  components/modal/doc/index.en-US.md
  components/modal/doc/index.zh-CN.md
Labels: PR: partially-approved

#7305 docs(module:skeleton): fix typo
  components/skeleton/doc/index.zh-CN.md
Labels: PR: unreviewed

#7314 fix(module:list): re-enter the Angular zone when the `NgZone.onStable` emits
  components/list/list-item-cell.ts
Labels: PR: reviewed-approved

#7190 fix(module:upload): fix upload drag drop will open new tab in firefox 91 and 92
  components/upload/upload.component.ts
Labels: PR: unreviewed

#7326 fix(module:carousel): fix nzAfterChange callback value not correctly
  components/carousel/carousel.component.ts
  components/carousel/carousel.spec.ts
Labels: PR: reviewed-approved, PR: target-patch
