Repository NG-ZORRO/ng-zorro-antd, pull requests merged in 2022-01, with the labels that each got.

#7188 fix(module:icon): fix old icon element not removed
  components/icon/icon.directive.ts
Labels: PR: reviewed-approved, PR: target-patch

#7182 perf(module:rate): do not run change detection on `focus` and `blur` events if there are no output listeners
  components/rate/rate.component.ts
Labels: PR: reviewed-approved

#7176 fix(module:drawer): fix close icon position without title property
  components/drawer/drawer.component.ts
Labels: PR: partially-approved

#7169 perf(module:modal): do not run change detection on mouse events
  components/modal/modal-confirm-container.component.ts
  components/modal/modal-container.component.ts
  components/modal/modal-container.directive.ts
Labels: PR: reviewed-approved

#7151 fix(module:code-editor): always initialize outside of the Angular zone
  components/code-editor/code-editor.component.ts
Labels: PR: reviewed-approved

#7150 fix(module:tree-view): fix innerTrackBy function #7118
  components/tree-view/node.ts
  components/tree-view/tree-virtual-scroll-view.ts
Labels: PR: reviewed-approved

#7132 perf(module:graph): do not run change detection on animation frame
  components/graph/core/minimap.ts
  components/graph/graph-minimap.component.ts
Labels: PR: reviewed-approved, PR: target-patch

#7125 fix(module:core): remove `resize` listener when the app is destroyed
  components/core/services/breakpoint.ts
Labels: PR: reviewed-approved, PR: target-patch

#7123 fix(module:modal): resolve memory leaks
  components/modal/modal-ref.ts
Labels: PR: reviewed-approved, PR: target-patch

#7112 fix(module:auto-complete): memory leak
  components/auto-complete/autocomplete-trigger.directive.ts
Labels: PR: reviewed-approved, PR: target-patch

#6931 docs(module:icon): support upload image to search icon (#5170)
  components/icon/demo/module
  components/icon/page/en-US.txt
  components/icon/page/index.ts
  components/icon/page/zh-CN.txt
Labels: PR: reviewed-approved

#7129 perf(module:input-number): reduce change detection cycles
  components/input-number/input-number.component.ts
  components/input-number/input-number.spec.ts
Labels: PR: target-patch, PR: partially-approved

#7127 perf(module:checkbox): reduce change detection cycles
  components/checkbox/checkbox.component.ts
  components/checkbox/checkbox.spec.ts
Labels: PR: target-patch, PR: partially-approved

#7124 perf(module:transfer): do not trigger change detection when the checkbox is clicked
  components/transfer/transfer-list.component.ts
  components/transfer/transfer.spec.ts
Labels: PR: target-patch, PR: partially-approved

#7102 fix(module:image): unsubscribe old src
  components/image/image.directive.ts
  components/image/image.spec.ts
Labels: PR: target-patch, PR: partially-approved

#7149 perf(module:*): add tsconfig noImplicitOverride
  azure-pipelines.yml
  components/carousel/strategies/experimental/flip-strategy.ts
  components/carousel/strategies/experimental/transform-no-loop-strategy.ts
  components/carousel/strategies/opacity-strategy.ts
  components/carousel/strategies/transform-strategy.ts
  components/comment/comment-cells.ts
  components/core/testing/mock-ng-zone.ts
  components/date-picker/lib/date-table.component.ts
  components/date-picker/lib/decade-header.component.ts
  components/date-picker/lib/decade-table.component.ts
  components/date-picker/lib/month-table.component.ts
  components/date-picker/lib/year-header.component.ts
  components/date-picker/lib/year-table.component.ts
  components/form/demo/auto-tips.ts
  components/form/form-control.spec.ts
  components/icon/icon.directive.ts
  components/message/message-container.component.ts
  components/message/message.component.ts
  components/message/message.service.ts
  components/modal/modal-confirm-container.component.ts
  components/modal/modal-container.component.ts
  components/notification/notification-container.component.ts
  components/notification/notification.component.ts
  components/notification/notification.service.ts
  components/popconfirm/popconfirm.ts
  components/popover/popover.ts
  components/statistic/countdown.component.ts
  components/tooltip/tooltip.ts
  components/tree-view/node.ts
  components/tree-view/padding.ts
  components/tree-view/toggle.ts
  components/tree-view/tree-virtual-scroll-view.ts
  components/tree-view/tree.ts
  tsconfig.json
Labels: PR: unreviewed

#7137 fix(module:statistic): re-enter the Angular zone when the `nzCountdownFinish` emits
  components/statistic/countdown.component.ts
Labels: PR: partially-approved

#7139 fix(module:cdk): resolve leak
  components/cdk/overflow/overflow-container.component.ts
Labels: PR: reviewed-approved

#7183 perf(module:steps): do not run change detection if there are no `nzIndexChange` listeners
  components/steps/step.component.ts
  components/steps/steps.component.ts
Labels: PR: reviewed-approved

#7208 fix(module:back-top): fix more reliable scrolling listener
  components/back-top/back-top.component.ts
  components/back-top/back-top.spec.ts
Labels: PR: reviewed-approved

#7211 chore: bump marked from 2.0.0 to 4.0.10
  package.json
  scripts/site/utils/generate-docs.js
  scripts/site/utils/get-meta.js
  scripts/site/utils/parse-demo-md.js
  scripts/site/utils/parse-doc-md.js
Labels: PR: unreviewed

#7215 chore(release): release 13.0.1
  CHANGELOG.md
  components/package.json
  components/version/version.ts
  docs/changelog.en-US.md
  docs/changelog.zh-CN.md
Labels: PR: partially-approved

#7230 docs: add ng-ant-admin website URL (#7213)
  docs/recommendation.zh-CN.md
Labels: PR: partially-approved
