Repository NG-ZORRO/ng-zorro-antd, pull requests merged in 2023-03, with the labels that each got.

#7867 docs(module:modal): update `index.en-US.md`
  components/modal/doc/index.en-US.md
Labels: PR: partially-approved

#7860 perf(module:date-picker): do not trigger change detection on `mousedown`
  components/date-picker/date-picker.component.ts
Labels: PR: partially-approved

#7862 perf(module:avatar): do not run change detection on timer and update styles directly
  components/avatar/avatar.component.ts
  components/avatar/avatar.spec.ts
Labels: PR: unreviewed

#7889 docs(module:qrcode): update index.en-US.md
  components/qr-code/doc/index.en-US.md
Labels: PR: reviewed-approved

#7849 feat(module:modal): pass data to modal component through injection token
  components/date-picker/date-picker.component.spec.ts
  components/modal/demo/service.md
  components/modal/demo/service.ts
  components/modal/doc/index.en-US.md
  components/modal/modal-config.ts
  components/modal/modal-types.ts
  components/modal/modal.service.ts
  components/modal/modal.spec.ts
  components/qr-code/qrcode.component.spec.ts
  components/tooltip/tooltip.spec.ts
Labels: Component: Modal, PR: unreviewed, PR: target-major, PR: partially-approved

#7890 docs: migration description
  docs/migration-v15.en-US.md
Labels: PR: reviewed-approved

#7893 fix(module:tooltip): fix tooltip.spec.ts
  components/tooltip/tooltip.spec.ts
Labels: PR: unreviewed

#7870 feat(module:form): support form label align
  components/form/demo/label-align.md
  components/form/demo/label-align.ts
  components/form/doc/index.en-US.md
  components/form/doc/index.zh-CN.md
  components/form/form-label.component.ts
  components/form/form-label.spec.ts
  components/form/form.directive.ts
Labels: PR: reviewed-approved, PR: target-major
