Repository NG-ZORRO/ng-zorro-antd, pull requests merged in 2023-01, with the labels that each got.

#7786 fix: some forms component can't be disable
  components/cascader/cascader.component.ts
  components/checkbox/checkbox.component.ts
  components/checkbox/checkbox.spec.ts
  components/date-picker/date-picker.component.spec.ts
  components/date-picker/date-picker.component.ts
  components/input-number/input-number.component.ts
  components/input-number/input-number.spec.ts
  components/radio/radio.component.ts
  components/radio/radio.spec.ts
  components/rate/rate.component.ts
  components/rate/rate.spec.ts
  components/select/select.component.ts
  components/select/select.spec.ts
  components/slider/slider.component.ts
  components/slider/slider.spec.ts
  components/switch/switch.component.ts
  components/switch/switch.spec.ts
  components/time-picker/time-picker.component.spec.ts
  components/time-picker/time-picker.component.ts
  package.json
Labels: PR: reviewed-approved, PR: target-minor

#7800 docs(module:code-editor): fix typo
  components/code-editor/doc/index.en-US.md
  components/code-editor/doc/index.zh-CN.md
Labels: PR: reviewed-approved

#7806 fix(module:checkbox): chebox group can't be disable initially
  components/checkbox/checkbox-group.component.ts
  components/checkbox/checkbox.spec.ts
  components/radio/radio-group.component.ts
  components/radio/radio.spec.ts
Labels: PR: partially-approved

#7810 chore(release): release 15.0.2
  CHANGELOG.md
  components/menu/submenu.component.ts
  components/package.json
  components/version/version.ts
  docs/changelog.en-US.md
  docs/changelog.zh-CN.md
Labels: PR: unreviewed

#7812 fix(module:radio): invalid disable state
  components/radio/radio.component.ts
  components/radio/radio.spec.ts
Labels: Component: Radio, PR: unreviewed

#7813 chore(release): release 15.0.3
  CHANGELOG.md
  components/package.json
  components/version/version.ts
  docs/changelog.en-US.md
  docs/changelog.zh-CN.md
Labels: PR: reviewed-approved
