Repository NG-ZORRO/ng-zorro-antd, pull requests merged in 2023-12, with the labels that each got.

#8228 feat(module:qr-code): support standalone component
  components/qr-code/doc/index.en-US.md
  components/qr-code/doc/index.zh-CN.md
  components/qr-code/qrcode.component.ts
  components/qr-code/qrcode.module.ts
Labels: PR: reviewed-approved

#8204 feat(module:typography): support standalone component
  components/typography/doc/index.en-US.md
  components/typography/doc/index.zh-CN.md
  components/typography/text-copy.component.ts
  components/typography/text-edit.component.ts
  components/typography/typography.component.ts
  components/typography/typography.module.ts
Labels: PR: reviewed-approved, PR: target-minor

#8203 feat(module:upload): support standalone component
  components/upload/doc/index.en-US.md
  components/upload/doc/index.zh-CN.md
  components/upload/upload-btn.component.ts
  components/upload/upload-list.component.ts
  components/upload/upload.component.ts
  components/upload/upload.module.ts
  components/upload/upload.spec.ts
Labels: PR: reviewed-approved, PR: target-minor

#8200 feat(module:image): support standalone component
  components/image/doc/index.en-US.md
  components/image/doc/index.zh-CN.md
  components/image/image-group.component.ts
  components/image/image-preview.component.ts
  components/image/image.directive.ts
  components/image/image.module.ts
Labels: PR: reviewed-approved, PR: target-minor

#8235 feat(module:page-header): support standalone component
  components/page-header/doc/index.en-US.md
  components/page-header/doc/index.zh-CN.md
  components/page-header/page-header-cells.ts
  components/page-header/page-header.component.ts
  components/page-header/page-header.module.ts
Labels: PR: reviewed-approved

#8233 feat(module:pipes): support standalone component
  components/pipes/doc/index.en-US.md
  components/pipes/doc/index.zh-CN.md
  components/pipes/nz-aggregate.pipe.ts
  components/pipes/nz-bytes.pipe.ts
  components/pipes/nz-css-unit.pipe.ts
  components/pipes/nz-ellipsis.pipe.ts
  components/pipes/nz-pipes.module.ts
  components/pipes/nz-safe-null.pipe.ts
  components/pipes/nz-sanitizer.pipe.ts
  components/pipes/nz-trim.pipe.ts
Labels: PR: reviewed-approved

#8231 feat(module:popover): support standalone component
  components/popover/doc/index.en-US.md
  components/popover/doc/index.zh-CN.md
  components/popover/popover.module.ts
  components/popover/popover.ts
Labels: PR: reviewed-approved

#8232 feat(module:pop-confirm): support standalone component
  components/popconfirm/doc/index.en-US.md
  components/popconfirm/doc/index.zh-CN.md
  components/popconfirm/popconfirm.module.ts
  components/popconfirm/popconfirm.ts
Labels: PR: reviewed-approved

#8185 feat(module:anchor): support standalone component
  components/anchor/anchor-link.component.ts
  components/anchor/anchor.component.ts
  components/anchor/anchor.module.ts
  components/anchor/doc/index.en-US.md
  components/anchor/doc/index.zh-CN.md
Labels: PR: reviewed-approved, PR: target-minor

#8202 feat(module:breadcrumb): support standalone component
  components/breadcrumb/breadcrumb-item.component.ts
  components/breadcrumb/breadcrumb-separator.component.ts
  components/breadcrumb/breadcrumb.component.ts
  components/breadcrumb/breadcrumb.module.ts
  components/breadcrumb/doc/index.en-US.md
  components/breadcrumb/doc/index.zh-CN.md
Labels: PR: reviewed-approved, PR: reviewed-changes-requested, PR: target-minor

#8197 feat(module:water-mark): nzWaterMark is a block element && standalone
  components/water-mark/doc/index.en-US.md
  components/water-mark/doc/index.zh-CN.md
  components/water-mark/style/index.less
  components/water-mark/typings.ts
  components/water-mark/water-mark.component.ts
  components/water-mark/water-mark.module.ts
Labels: PR: reviewed-approved, PR: target-minor

#8259 refactor(module:core): remove componentFactorResolver
  components/popconfirm/popconfirm.ts
  components/popover/popover.ts
  components/tooltip/base.ts
  components/tooltip/tooltip.ts
Labels: PR: target-minor, PR: partially-approved

#8277 fix(build): warning cron parser common js dependencies
  angular.json
Labels: 🖨 Build, PR: reviewed-approved, PR: target-minor

#8252 feat(module:form): support standalone component
  components/form/doc/index.en-US.md
  components/form/doc/index.zh-CN.md
  components/form/form-control.component.ts
  components/form/form-item.component.ts
  components/form/form-label.component.ts
  components/form/form-label.spec.ts
  components/form/form-split.component.ts
  components/form/form-split.spec.ts
  components/form/form-text.component.ts
  components/form/form-text.spec.ts
  components/form/form.directive.ts
  components/form/form.module.ts
  components/form/form.spec.ts
Labels: PR: reviewed-approved, PR: target-minor

#8248 feat(module:icon): support standalone component
  components/icon/doc/index.en-US.md
  components/icon/doc/index.zh-CN.md
  components/icon/icon.directive.ts
  components/icon/icon.module.ts
Labels: PR: reviewed-approved, PR: target-minor

#8247 feat(module:input): support standalone component
  components/input/autosize.directive.ts
  components/input/doc/index.en-US.md
  components/input/doc/index.zh-CN.md
  components/input/input-group-slot.component.ts
  components/input/input-group.component.ts
  components/input/input.directive.ts
  components/input/input.module.ts
  components/input/textarea-count.component.ts
Labels: PR: reviewed-approved, PR: target-minor

#8262 feat(module:description): support standalone component
  components/descriptions/descriptions-item.component.ts
  components/descriptions/descriptions.component.ts
  components/descriptions/descriptions.module.ts
  components/descriptions/doc/index.en-US.md
  components/descriptions/doc/index.zh-CN.md
Labels: PR: reviewed-approved, Component: Descriptions, PR: target-minor

#8225 feat(module:resizable): support standalone component
  components/resizable/doc/index.en-US.md
  components/resizable/doc/index.zh-CN.md
  components/resizable/resizable.directive.ts
  components/resizable/resizable.module.ts
  components/resizable/resize-handle.component.ts
  components/resizable/resize-handles.component.ts
Labels: PR: reviewed-approved, PR: target-minor

#8250 feat(module:grid): support standalone component
  components/grid/col.directive.ts
  components/grid/doc/index.en-US.md
  components/grid/doc/index.zh-CN.md
  components/grid/grid.module.ts
  components/grid/row.directive.ts
Labels: Component: Grid, PR: reviewed-approved, PR: target-minor

#8251 feat(module:graph): support standalone component
  components/graph/doc/index.en-US.md
  components/graph/doc/index.zh-CN.md
  components/graph/graph-defs.component.ts
  components/graph/graph-edge.component.ts
  components/graph/graph-edge.directive.ts
  components/graph/graph-group-node.directive.ts
  components/graph/graph-minimap.component.ts
  components/graph/graph-node.component.ts
  components/graph/graph-node.directive.ts
  components/graph/graph-zoom.directive.ts
  components/graph/graph.component.ts
  components/graph/graph.module.ts
Labels: PR: reviewed-approved, PR: target-minor

#8275 feat(module:button): support standalone component
  components/button/button-group.component.ts
  components/button/button-group.spec.ts
  components/button/button.component.ts
  components/button/button.module.ts
  components/button/button.spec.ts
  components/button/doc/index.en-US.md
  components/button/doc/index.zh-CN.md
Labels: Component: Button, PR: reviewed-approved, PR: target-minor

#8265 feat(module:core): support standalone component
  components/core/element-patch/element-patch.directive.ts
  components/core/element-patch/element-patch.module.ts
  components/core/highlight/highlight.module.ts
  components/core/highlight/highlight.pipe.ts
  components/core/no-animation/nz-no-animation.directive.ts
  components/core/no-animation/nz-no-animation.module.ts
  components/core/outlet/outlet.module.ts
  components/core/outlet/string_template_outlet.directive.ts
  components/core/pipe/nz-pipe.module.ts
  components/core/pipe/time-range.pipe.ts
  components/core/trans-button/nz-trans-button.directive.ts
  components/core/trans-button/nz-trans-button.module.ts
  components/core/transition-patch/transition-patch.directive.ts
  components/core/transition-patch/transition-patch.module.ts
  components/core/wave/nz-wave.directive.ts
  components/core/wave/nz-wave.module.ts
Labels: PR: reviewed-approved, PR: target-minor

#8270 feat(module:cdk): support standalone component
  components/cdk/overflow/overflow-container.component.ts
  components/cdk/overflow/overflow-item.directive.ts
  components/cdk/overflow/overflow-rest.directive.ts
  components/cdk/overflow/overflow-suffix.directive.ts
  components/cdk/overflow/overflow.module.ts
  components/cdk/resize-observer/resize-observer.directive.ts
  components/cdk/resize-observer/resize-observer.module.ts
Labels: PR: reviewed-approved, PR: target-minor

#8255 feat(module:dropdown): support standalone component #8254
  components/dropdown/doc/index.en-US.md
  components/dropdown/doc/index.zh-CN.md
  components/dropdown/dropdown-a.directive.ts
  components/dropdown/dropdown-button.directive.ts
  components/dropdown/dropdown-menu.component.ts
  components/dropdown/dropdown.directive.ts
  components/dropdown/dropdown.module.ts
  components/tabs/tab-nav-operation.component.ts
Labels: Component: Dropdown, PR: reviewed-approved, PR: target-minor

#8273 feat(module:card): component support standalone
  components/card/card-grid.directive.ts
  components/card/card-loading.component.ts
  components/card/card-meta.component.ts
  components/card/card-tab.component.ts
  components/card/card.component.ts
  components/card/card.module.ts
  components/card/doc/index.en-US.md
  components/card/doc/index.zh-CN.md
Labels: Component: Card, PR: reviewed-approved, PR: target-minor

#8145 feat(module:flex): add flex component
  .github/CODEOWNERS
  components/components.less
  components/flex/demo/align.md
  components/flex/demo/align.ts
  components/flex/demo/basic.md
  components/flex/demo/basic.ts
  components/flex/demo/combination.md
  components/flex/demo/combination.ts
  components/flex/demo/gap.md
  components/flex/demo/gap.ts
  components/flex/demo/module
  components/flex/demo/wrap.md
  components/flex/demo/wrap.ts
  components/flex/doc/index.en-US.md
  components/flex/doc/index.zh-CN.md
  components/flex/flex.module.ts
  components/flex/flex.spec.ts
  components/flex/index.ts
  components/flex/ng-package.json
  components/flex/nz-flex.directive.ts
  components/flex/public-api.ts
  components/flex/style/entry.less
  components/flex/style/index.less
  components/flex/typings.ts
  components/grid/doc/index.en-US.md
  components/grid/doc/index.zh-CN.md
  scripts/prerender/route-paths.txt
  scripts/site/template/ng-zorro-antd.module.template.ts
Labels: PR: reviewed-approved, PR: target-minor

#8267 feat(module:collapse): support standalone component
  components/collapse/collapse-panel.component.ts
  components/collapse/collapse.component.ts
  components/collapse/collapse.module.ts
  components/collapse/doc/index.en-US.md
  components/collapse/doc/index.zh-CN.md
Labels: Component: Collapse, PR: unreviewed, PR: target-minor

#8266 feat(module:comment): support standalone component
  components/comment/comment-cells.ts
  components/comment/comment.component.ts
  components/comment/comment.module.ts
  components/comment/doc/index.en-US.md
  components/comment/doc/index.zh-CN.md
Labels: PR: reviewed-approved, PR: target-minor

#8274 feat(module:calendar): support standalone component
  components/calendar/calendar-cells.ts
  components/calendar/calendar-header.component.ts
  components/calendar/calendar-header.spec.ts
  components/calendar/calendar.component.ts
  components/calendar/calendar.module.ts
  components/calendar/doc/index.en-US.md
  components/calendar/doc/index.zh-CN.md
Labels: Component: Calendar, PR: reviewed-approved, PR: target-minor

#8271 feat(module:cascader): support standalone component
  components/cascader/cascader-li.component.ts
  components/cascader/cascader.component.ts
  components/cascader/cascader.module.ts
  components/cascader/doc/index.en-US.md
  components/cascader/doc/index.zh-CN.md
Labels: Component: Cascader, PR: unreviewed, PR: target-minor

#8264 feat(module:cron-expression): support standalone component
  components/cron-expression/cron-expression-input.component.ts
  components/cron-expression/cron-expression-label.component.ts
  components/cron-expression/cron-expression-preview.component.ts
  components/cron-expression/cron-expression.component.ts
  components/cron-expression/cron-expression.module.ts
  components/cron-expression/doc/index.en-US.md
  components/cron-expression/doc/index.zh-CN.md
Labels: PR: reviewed-approved, PR: target-minor, Component: CronExpression

#8268 feat(module:code-editor): support standalone component
  components/code-editor/code-editor.component.ts
  components/code-editor/code-editor.module.ts
  components/code-editor/doc/index.en-US.md
  components/code-editor/doc/index.zh-CN.md
Labels: PR: reviewed-approved, Component: CodeEditor, PR: target-minor

#8256 feat(module:drawer): support standalone component
  components/drawer/doc/index.en-US.md
  components/drawer/doc/index.zh-CN.md
  components/drawer/drawer-content.directive.ts
  components/drawer/drawer.component.ts
  components/drawer/drawer.module.ts
Labels: Component: Drawer, PR: reviewed-approved, PR: target-minor

#8189 fix(module:cron-expression): output type error
  components/cron-expression/cron-expression.component.ts
Labels: PR: reviewed-approved, PR: target-patch

#8234 feat(module:pagination): support standalone component
  components/pagination/doc/index.en-US.md
  components/pagination/doc/index.zh-CN.md
  components/pagination/pagination-default.component.ts
  components/pagination/pagination-item.component.ts
  components/pagination/pagination-options.component.ts
  components/pagination/pagination-simple.component.ts
  components/pagination/pagination.component.ts
  components/pagination/pagination.module.ts
Labels: Component: Pagination, PR: reviewed-approved, PR: target-minor

#8240 feat(module:modal): support standalone component
  components/modal/doc/index.en-US.md
  components/modal/doc/index.zh-CN.md
  components/modal/modal-close.component.ts
  components/modal/modal-confirm-container.component.ts
  components/modal/modal-container.component.ts
  components/modal/modal-content.directive.ts
  components/modal/modal-footer.component.ts
  components/modal/modal-footer.directive.ts
  components/modal/modal-title.component.ts
  components/modal/modal-title.directive.ts
  components/modal/modal.component.ts
  components/modal/modal.module.ts
Labels: PR: reviewed-approved, PR: target-minor

#8272 feat(module:carousel): support standalone component
  components/carousel/carousel-content.directive.ts
  components/carousel/carousel.component.ts
  components/carousel/carousel.module.ts
  components/carousel/doc/index.en-US.md
  components/carousel/doc/index.zh-CN.md
Labels: Component: Carousel, PR: reviewed-approved, PR: target-minor

#8242 feat(module:menu): support standalone component
  components/menu/doc/index.en-US.md
  components/menu/doc/index.zh-CN.md
  components/menu/menu-divider.directive.ts
  components/menu/menu-group.component.ts
  components/menu/menu-item.component.ts
  components/menu/menu.directive.ts
  components/menu/menu.module.ts
  components/menu/submenu-inline-child.component.ts
  components/menu/submenu-non-inline-child.component.ts
  components/menu/submenu-title.component.ts
  components/menu/submenu.component.ts
Labels: Component: Menu, PR: reviewed-approved, PR: target-minor

#8182 feat(module:alert): support standalone component
  components/alert/alert.component.ts
  components/alert/alert.module.ts
  components/alert/doc/index.en-US.md
  components/alert/doc/index.zh-CN.md
Labels: PR: reviewed-approved, Component: Alert, PR: target-minor

#8241 feat(module:message): support standalone component
  components/message/message-container.component.ts
  components/message/message.component.ts
  components/message/message.module.ts
Labels: PR: reviewed-approved, PR: target-minor

#8244 feat(module:list): support standalone component
  components/list/doc/index.en-US.md
  components/list/doc/index.zh-CN.md
  components/list/list-cell.ts
  components/list/list-item-cell.ts
  components/list/list-item-meta-cell.ts
  components/list/list-item-meta.component.ts
  components/list/list-item.component.ts
  components/list/list.component.ts
  components/list/list.module.ts
Labels: Component: List, PR: target-minor, PR: partially-approved

#8206 feat(module:tree-select): support standalone component
  components/tree-select/doc/index.en-US.md
  components/tree-select/doc/index.zh-CN.md
  components/tree-select/tree-select.component.ts
  components/tree-select/tree-select.module.ts
Labels: PR: reviewed-approved, PR: target-minor

#8211 feat(module:time-picker): support standalone component
  components/time-picker/doc/index.en-US.md
  components/time-picker/doc/index.zh-CN.md
  components/time-picker/time-picker-panel.component.spec.ts
  components/time-picker/time-picker-panel.component.ts
  components/time-picker/time-picker.component.spec.ts
  components/time-picker/time-picker.component.ts
  components/time-picker/time-picker.module.ts
Labels: Component: TimePicker, PR: reviewed-approved, PR: target-minor

#8263 feat(module:date-picker): support standalone component
  components/date-picker/calendar-footer.component.ts
  components/date-picker/date-picker.component.ts
  components/date-picker/date-picker.module.ts
  components/date-picker/date-range-popup.component.ts
  components/date-picker/doc/index.en-US.md
  components/date-picker/doc/index.zh-CN.md
  components/date-picker/inner-popup.component.ts
  components/date-picker/lib/abstract-panel-header.ts
  components/date-picker/lib/abstract-table.html
  components/date-picker/lib/abstract-table.ts
  components/date-picker/lib/date-header.component.ts
  components/date-picker/lib/date-table.component.ts
  components/date-picker/lib/decade-header.component.ts
  components/date-picker/lib/decade-table.component.ts
  components/date-picker/lib/lib-packer.module.ts
  components/date-picker/lib/lib-packer.spec.ts
  components/date-picker/lib/month-header.component.ts
  components/date-picker/lib/month-table.component.ts
  components/date-picker/lib/year-header.component.ts
  components/date-picker/lib/year-table.component.ts
  components/date-picker/month-picker.component.ts
  components/date-picker/range-picker.component.ts
  components/date-picker/week-picker.component.ts
  components/date-picker/year-picker.component.ts
Labels: Component: DatePicker, 🤚 Blocked, PR: unreviewed, PR: reviewed-changes-requested, PR: target-minor

#8276 feat(module:table): support standalone component
  components/table/doc/index.en-US.md
  components/table/doc/index.zh-CN.md
  components/table/src/addon/filter-trigger.component.ts
  components/table/src/addon/filter.component.ts
  components/table/src/addon/row-expand-button.directive.ts
  components/table/src/addon/row-indent.directive.ts
  components/table/src/addon/selection.component.ts
  components/table/src/addon/sorters.component.ts
  components/table/src/cell/cell-fixed.directive.ts
  components/table/src/cell/cell.directive.ts
  components/table/src/cell/custom-column.directive.ts
  components/table/src/cell/td-addon.component.ts
  components/table/src/cell/th-addon.component.ts
  components/table/src/cell/th-measure.directive.ts
  components/table/src/cell/th-selection.component.ts
  components/table/src/styled/align.directive.ts
  components/table/src/styled/ellipsis.directive.ts
  components/table/src/styled/word-break.directive.ts
  components/table/src/table.module.ts
  components/table/src/table/table-content.component.ts
  components/table/src/table/table-fixed-row.component.ts
  components/table/src/table/table-inner-default.component.ts
  components/table/src/table/table-inner-scroll.component.ts
  components/table/src/table/table-virtual-scroll.directive.ts
  components/table/src/table/table.component.ts
  components/table/src/table/tbody.component.ts
  components/table/src/table/thead.component.ts
  components/table/src/table/title-footer.component.ts
  components/table/src/table/tr-expand.directive.ts
  components/table/src/table/tr-measure.component.ts
  components/table/src/table/tr.directive.ts
Labels: Component: Table, PR: reviewed-approved, PR: target-minor

#8257 feat(module:core): make no-animation standalone
  components/auto-complete/autocomplete.component.ts
  components/badge/badge-sup.component.ts
  components/badge/badge.spec.ts
  components/cascader/cascader.component.ts
  components/date-picker/date-picker.component.ts
  components/drawer/drawer.component.ts
  components/drawer/drawer.spec.ts
  components/dropdown/dropdown-menu.component.ts
  components/graph/demo/module
  components/menu/submenu.component.ts
  components/popconfirm/popconfirm.ts
  components/popover/popover.ts
  components/select/select.component.ts
  components/tooltip/tooltip.ts
  components/tree-select/tree-select.component.ts
  components/tree-view/demo/module
  components/tree/tree.component.ts
Labels: PR: reviewed-approved, PR: target-minor

#8289 refactor(module:alert): implement new control flow
  components/alert/alert.component.ts
Labels: PR: reviewed-approved, Component: Alert, PR: target-minor

#8288 refactor(module:avatar): implement new control flow
  components/avatar/avatar.component.ts
Labels: Component: Avatar, PR: reviewed-approved, PR: target-minor

#8298 fix(module:calendar): style radio button not apply
  components/calendar/calendar-header.component.ts
Labels: :bug: Bug, Component: Calendar, PR: reviewed-approved, PR: target-minor

#8291 refactor(module:anchor): implement new control flow
  components/anchor/anchor-link.component.ts
  components/anchor/anchor.component.ts
Labels: Component: Anchor, PR: reviewed-approved, PR: target-minor

#8292 refactor(module:back-top): implement new control flow
  components/back-top/back-top.component.ts
Labels: PR: reviewed-approved, PR: target-minor, Component: BackTop

#8293 refactor(module:badge): implement new control flow
  components/badge/badge-sup.component.ts
  components/badge/badge.component.ts
  components/badge/badge.spec.ts
  components/badge/demo/colorful.ts
Labels: Component: Badge, PR: reviewed-approved, PR: target-minor

#8294 refactor(module:breadcrumb): implement new control flow
  components/breadcrumb/breadcrumb-item.component.ts
  components/breadcrumb/breadcrumb.component.ts
Labels: Component: BreadCrumb, PR: reviewed-approved, PR: target-minor

#8296 refactor(module:button): implement new control flow
  components/button/button.component.ts
Labels: Component: Button, PR: reviewed-approved, PR: target-minor

#8297 refactor(module:calendar): implement new control flow
  components/calendar/calendar-header.component.ts
  components/calendar/calendar.component.ts
  components/calendar/demo/notice-calendar.ts
Labels: Component: Calendar, PR: reviewed-approved, PR: target-minor

#8301 refactor(module:card): implement new control flow
  components/card/card-loading.component.ts
  components/card/card-meta.component.ts
  components/card/card.component.ts
Labels: Component: Card, PR: reviewed-approved, PR: target-minor

#8302 refactor(module:carousel): implement new control flow
  components/carousel/carousel.component.ts
  components/carousel/carousel.spec.ts
  components/carousel/demo/autoplay.ts
  components/carousel/demo/basic.ts
  components/carousel/demo/custom.ts
  components/carousel/demo/fade.ts
  components/carousel/demo/loop.ts
  components/carousel/demo/position.ts
Labels: Component: Carousel, PR: reviewed-approved, PR: target-minor

#8303 refactor(module:cascader): implement new control flow
  components/cascader/cascader-li.component.ts
  components/cascader/cascader.component.ts
  components/cascader/cascader.spec.ts
  components/cascader/demo/custom-render.ts
Labels: Component: Cascader, PR: reviewed-approved, PR: target-minor

#8304 refactor(module:checkbox): implement new control flow
  components/checkbox/checkbox-group.component.ts
Labels: Component: Checkbox, PR: reviewed-approved, PR: target-minor

#8305 refactor(module:code-editor): implement new control flow
  components/code-editor/code-editor.component.ts
Labels: PR: reviewed-approved, Component: CodeEditor, PR: target-minor

#8309 refactor(module:collapse): implement new control flow
  components/collapse/collapse-panel.component.ts
  components/collapse/demo/accordion.ts
  components/collapse/demo/basic.ts
  components/collapse/demo/borderless.ts
  components/collapse/demo/custom.ts
  components/collapse/demo/extra.ts
  components/collapse/demo/ghost.ts
  components/collapse/demo/mix.ts
  components/collapse/demo/noarrow.ts
Labels: Component: Collapse, PR: reviewed-approved, PR: target-minor

#8310 fix(module:tabs): change tab trigger ngSubmit function
  components/tabs/tabset.component.ts
Labels: :bug: Bug, Component: Tabs, PR: reviewed-approved, PR: target-patch

#8313 refactor(module:color-picker): refactor control flow
  components/color-picker/color-format.component.ts
  components/color-picker/color-picker.component.ts
Labels: PR: reviewed-approved, PR: target-minor
