Repository NG-ZORRO/ng-zorro-antd, pull requests merged in 2023-07, with the labels that each got.

#7987 feat(module:resizable): add direction parameter in NzResizeEvent
  components/resizable/demo/basic.ts
  components/resizable/doc/index.en-US.md
  components/resizable/doc/index.zh-CN.md
  components/resizable/resizable.directive.ts
  components/resizable/resizable.spec.ts
Labels: PR: target-minor

#7958 fix(module: list): fix the bug that synchrone action item are not displayed in the item
  components/list/list-item-cell.ts
  components/list/list.spec.ts
Labels: :bug: Bug

#7930 feat(module:modal): Remove nzComponentParams in v16
  components/modal/demo/service.md
  components/modal/demo/service.ts
  components/modal/doc/index.en-US.md
  components/modal/doc/index.zh-CN.md
  components/modal/modal-footer.component.ts
  components/modal/modal-types.ts
  components/modal/modal.component.ts
  components/modal/modal.service.ts
  components/modal/modal.spec.ts
  components/modal/utils.ts
Labels: PR: reviewed-approved

#7915 feat(module:dropdown): close context menu on escape
  components/dropdown/context-menu.service.spec.ts
  components/dropdown/context-menu.service.ts
Labels: Component: Dropdown, PR: unreviewed

#7850 perf(module:select): remove unused types
  components/select/select-top-control.component.ts
Labels: PR: unreviewed

#7892 feat(module:form): support form label wrap
  components/form/demo/label-wrap.md
  components/form/demo/label-wrap.ts
  components/form/doc/index.en-US.md
  components/form/doc/index.zh-CN.md
  components/form/form-label.component.ts
  components/form/form-label.spec.ts
  components/form/form.directive.ts
Labels: PR: unreviewed, PR: target-major

#7768 feat(module:dropdown): improve `NzContextMenuService#create()`
  components/dropdown/context-menu.service.spec.ts
  components/dropdown/context-menu.service.ts
  components/dropdown/doc/index.en-US.md
  components/dropdown/doc/index.zh-CN.md
Labels: PR: unreviewed, PR: target-minor, PR: partially-approved
