Repository NG-ZORRO/ng-zorro-antd, pull requests merged in 2023-11, with the labels that each got.

#8071 chore: bump to angular 16.2
  components/tsconfig.json
  package.json
  schematics/ng-add/index.spec.ts
  schematics/tsconfig.json
  tsconfig.json
Labels: PR: target-minor

#8143 fix(module:i18n): update fa_IR translations
  components/i18n/languages/fa_IR.ts
Labels: PR: reviewed-approved

#7907 fix(module:autocomplete): fix the wrong value of internal nz-auto-option
  components/auto-complete/autocomplete.component.ts
Labels: PR: unreviewed, PR: target-patch

#8073 refactor(module:*): use inject function to simplify code
  components/i18n/date-config.ts
  components/i18n/date-helper.service.ts
  components/menu/menu-group.component.ts
  components/menu/menu.directive.ts
  components/tree-select/tree-select.component.ts
  components/tree/tree.component.ts
  docs/global-config.en-US.md
  docs/global-config.zh-CN.md
  docs/i18n.en-US.md
  docs/i18n.zh-CN.md
Labels: PR: reviewed-approved

#8114 fix(module:cron-expression): exception error & cancel format prompt copy
  components/cron-expression/cron-expression-label.component.ts
  components/cron-expression/cron-expression-preview.component.ts
  components/cron-expression/cron-expression.component.ts
  components/cron-expression/doc/index.en-US.md
  components/cron-expression/doc/index.zh-CN.md
  components/cron-expression/style/index.less
  components/cron-expression/typings.ts
  components/i18n/languages/en_US.ts
  components/i18n/languages/fa_IR.ts
  components/i18n/languages/zh_CN.ts
  components/i18n/nz-i18n.interface.ts
Labels: PR: target-minor

#7820 fix(module:slider): step can not click the problem
  components/slider/step.component.ts
Labels: PR: reviewed-approved, PR: target-minor

#8038 fix(module:tree): nzCheckBoxChange never emitting
  components/core/tree/nz-tree-base.service.ts
  components/tree/tree.component.ts
Labels: PR: target-minor

#7886 feat(module:table): nzExpand supports custom icon
  components/table/demo/colspan-rowspan.md
  components/table/demo/expand-icon.md
  components/table/demo/expand-icon.ts
  components/table/doc/index.en-US.md
  components/table/doc/index.zh-CN.md
  components/table/src/cell/td-addon.component.ts
Labels: PR: unreviewed

#7903 feat(module:table): add `nzLabel` to include aria-label in checkboxes
  components/table/demo/row-selection-and-operation.ts
  components/table/doc/index.en-US.md
  components/table/doc/index.zh-CN.md
  components/table/src/addon/selection.component.ts
  components/table/src/cell/td-addon.component.ts
  components/table/src/cell/th-selection.component.ts
  components/table/src/testing/td.spec.ts
Labels: PR: unreviewed

#8044 fix(module:table): custom column styles collapse when using nzScroll
  components/table/style/index.less
  components/table/style/patch.less
Labels: :bug: Bug, PR: target-patch, PR: target-minor

#8046 feat(module:notification): support for more custom templates
  components/notification/demo/template.md
  components/notification/demo/with-btn.ts
  components/notification/doc/index.en-US.md
  components/notification/doc/index.zh-CN.md
  components/notification/notification.component.ts
  components/notification/notification.service.ts
  components/notification/typings.ts
Labels: 💔 Breaking Change, PR: reviewed-approved, PR: target-major

#7505 feat(module:slider): add the ability to use a template
  components/slider/demo/tip-formatter.ts
  components/slider/doc/index.en-US.md
  components/slider/doc/index.zh-CN.md
  components/slider/handle.component.ts
  components/slider/slider.component.ts
  components/slider/slider.spec.ts
  components/tooltip/tooltip.ts
Labels: PR: unreviewed

#8174 chore: added nx cache to gitignore
  .gitignore
Labels: PR: reviewed-approved

#8173 refactor(module:image): follow nz-zorro conventions
  components/image/image-preview.component.ts
  components/image/image.directive.ts
  components/image/image.service.ts
Labels: PR: reviewed-approved

#8171 fix: fix logic for generating directive tags
  scripts/site/utils/marked.js
Labels: PR: reviewed-approved, PR: target-patch
