Repository NG-ZORRO/ng-zorro-antd, pull requests merged in 2025-01, with the labels that each got.

#8954 docs: update dingtalk qrcode
  docs/introduce.zh-CN.md
Labels: :scroll: Doc

#8955 fix(module:input-number): fix NG0600 error
  components/input-number/input-number.component.ts
Labels: Component: InputNumber, PR: unreviewed, PR: target-patch

#8958 chore: add @ctrl/tinycolor to dependencies
  components/ng-package.json
  components/package.json
Labels: PR: reviewed-approved, PR: target-patch

#8960 fix(module:transfer): correctly set the transfer-list-body class
  components/transfer/transfer-list.component.ts
Labels: Component: Transfer, PR: reviewed-approved, PR: target-patch

#8962 fix(module:progress): fix NG0956 error
  components/progress/progress.component.ts
Labels: Component: Progress, PR: reviewed-approved, PR: target-patch

#8878 feat(module:popover): add `nzPopoverOverlayClickable` to disable click on mask
  components/popconfirm/doc/index.en-US.md
  components/popover/demo/overlay.md
  components/popover/demo/overlay.ts
  components/popover/doc/index.en-US.md
  components/popover/doc/index.zh-CN.md
  components/popover/popover.spec.ts
  components/popover/popover.ts
  components/tooltip/base.ts
Labels: Component: Popover, PR: reviewed-approved, PR: target-minor

#8718 refactor(module:*): use ECMAScript standard class field
  components/avatar/avatar.component.ts
  components/cascader/cascader.spec.ts
  components/cascader/demo/reactive-form.ts
  components/cdk/overflow/overflow-container.component.ts
  components/cdk/overflow/overflow-item.directive.ts
  components/cdk/overflow/overflow-rest.directive.ts
  components/cdk/overflow/overflow-suffix.directive.ts
  components/color-picker/color-picker.component.ts
  components/color-picker/demo/use.ts
  components/cron-expression/demo/use.ts
  components/date-picker/date-picker.component.spec.ts
  components/date-picker/lib/abstract-table.ts
  components/date-picker/lib/date-table.component.ts
  components/date-picker/lib/lib-packer.spec.ts
  components/date-picker/lib/month-table.component.ts
  components/dropdown/dropdown-menu.component.ts
  components/dropdown/dropdown.directive.ts
  components/form/demo/advanced-search.ts
  components/form/demo/auto-tips.ts
  components/form/demo/coordinated.ts
  components/form/demo/dynamic-form-item.ts
  components/form/demo/dynamic-rule.ts
  components/form/demo/horizontal-login.ts
  components/form/demo/label-align.ts
  components/form/demo/label-wrap.ts
  components/form/demo/layout.ts
  components/form/demo/normal-login.ts
  components/form/demo/register.ts
  components/form/demo/time-related-controls.ts
  components/form/demo/validate-reactive.ts
  components/form/form-control.spec.ts
  components/input/autosize.directive.ts
  components/input/demo/textarea-with-character-count.ts
  components/list/demo/infinite-load.ts
  components/mention/demo/form.ts
  components/menu/submenu.component.ts
  components/menu/submenu.service.ts
  components/message/base.ts
  components/message/message-container.component.ts
  components/message/message.component.ts
  components/message/message.service.ts
  components/message/message.spec.ts
  components/modal/modal-confirm-container.component.ts
  components/modal/modal-container.component.ts
  components/notification/notification-container.component.ts
  components/notification/notification.component.ts
  components/notification/notification.service.ts
  components/popconfirm/popconfirm.ts
  components/popover/popover.ts
  components/tooltip/base.ts
  components/tooltip/tooltip.ts
  components/tree-view/indent.ts
  components/tree-view/node.ts
  components/tree-view/tree-virtual-scroll-view.ts
  components/tree-view/tree.ts
  components/typography/text-copy.component.ts
  components/typography/text-edit.component.ts
  components/water-mark/demo/custom.ts
  tsconfig.json
Labels: PR: reviewed-approved, PR: target-minor

#8970 refactor: enable isolatedModules compiler option
  components/core/time/public-api.ts
  components/date-picker/public-api.ts
  components/slider/public-api.ts
  components/timeline/public-api.ts
  components/tree/public-api.ts
  scripts/site/_site/tsconfig.app.json
Labels: 🖨 Build, PR: reviewed-approved, PR: target-minor

#8971 chore: bump angular to 19.1
  package-lock.json
  package.json
Labels: PR: reviewed-approved, PR: target-minor

#8972 feat(module:popover,popconfirm,tooltip): overlayClassName supports space delimited classes
  components/popconfirm/popconfirm.spec.ts
  components/popover/popover.spec.ts
  components/tooltip/base.ts
  components/tooltip/tooltip.spec.ts
  components/tooltip/tooltip.ts
Labels: Component: Tooltip, Component: Popconfirm, Component: Popover, PR: reviewed-approved, PR: target-minor

#8977 docs: fix typo
  components/rate/doc/index.en-US.md
  components/rate/doc/index.zh-CN.md
  components/timeline/doc/index.en-US.md
  components/timeline/doc/index.zh-CN.md
Labels: PR: reviewed-approved, PR: target-patch

#8984 fix(module:tree-select): fix tree select error
  components/tree-select/tree-select.component.ts
Labels: Component: TreeSelect, PR: unreviewed, PR: target-patch

#8979 fix(module:input-number,checkbox): accept the disabled change from ng control
  components/checkbox/checkbox-group.component.ts
  components/checkbox/checkbox-group.spec.ts
  components/input-number/input-number.component.spec.ts
  components/input-number/input-number.component.ts
Labels: Component: InputNumber, Component: Checkbox, PR: reviewed-approved, PR: target-patch

#8988 refactor(module:hash-code): modify component style name
  components/hash-code/hash-code.component.spec.ts
  components/hash-code/hash-code.component.ts
  components/hash-code/style/index.less
Labels: PR: reviewed-approved, PR: target-minor, Component: HashCode

#8986 chore: upgrade dev dependencies
  .stylelintrc.json
  package-lock.json
  package.json
  schematics/utils/ng-update/elements.ts
  scripts/gulp/tasks/site.ts
  scripts/prerender/sitemap.ts
  scripts/release/release.ts
  scripts/site/replace-scope-prefix.js
  scripts/site/utils/get-meta.js
Labels: 🖨 Build, PR: draft, dependencies

#8990 refactor(module:docs): bump marked to latest version
  components/affix/doc/index.en-US.md
  components/affix/doc/index.zh-CN.md
  components/pipes/doc/index.en-US.md
  components/pipes/doc/index.zh-CN.md
  components/tree-view/doc/index.en-US.md
  components/tree-view/doc/index.zh-CN.md
  docs/animations.en-US.md
  docs/animations.zh-CN.md
  package-lock.json
  package.json
  scripts/site/_site/doc/app/app.component.ts
  scripts/site/_site/doc/style/markdown.less
  scripts/site/utils/angular-language-marked.js
  scripts/site/utils/generate-demo-code-files.js
  scripts/site/utils/generate-demo.js
  scripts/site/utils/generate-docs.js
  scripts/site/utils/get-meta.js
  scripts/site/utils/marked.js
  scripts/site/utils/parse-demo-md.js
  scripts/site/utils/parse-doc-md.js
  scripts/site/utils/prism.js
Labels: :scroll: Doc, 🖨 Build, PR: target-minor

#8991 chore: bump html-minifier-terser to 7.2.0
  package-lock.json
  package.json
  scripts/prerender/minify.ts
Labels: :scroll: Doc, 🖨 Build, PR: target-minor

#8992 chore: bump less to 4.2.2
  package-lock.json
  package.json
  scripts/build/compile-styles.ts
Labels: 🖨 Build, ✏️ Style, PR: target-minor
